import { QuestionTemplate } from '@/types/question-template';

/**
 * Buddhism Question Templates - Grade 3
 * Extracted from Lyceum GRADE 3 Buddhism papers with mark schemes
 * (March 2021, 2022, 2023; July 2021, 2022, 2023)
 */

export const BUDDHISM_CATEGORIES = [
  'Buddha and His Life',
  'Temple and Worship',
  'Precepts and Morality',
  'Buddhist History - Sri Lanka',
  'Jataka Stories',
  'Good Qualities',
] as const;

export const buddhismTemplates: QuestionTemplate[] = [
  // ========== March 2021 (MS: i)c (ii)a (iii)b (iv)b (v)a (vi)c (vii)a (viii)c (ix)c (x)b ==========
  {
    id: 'bud-mar21-therini-sister',
    topic: 'Sanghamitta Therani',
    category: 'Buddhist History - Sri Lanka',
    difficulty: 'Easy',
    questionTemplate: 'Therini _______ was the sister of Arahath Mahinda Thero.',
    correctAnswerFormula: 'Sanghamitta',
    wrongAnswers: ['Yashodara', 'Anula'],
    methodSteps: ['Sanghamitta Therani was the sister of Arahath Mahinda Thero.', 'She brought the Bo sapling of Jaya Sri Maha Bodhi to Sri Lanka.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'bud-mar21-buddhagaya',
    topic: 'Buddha',
    category: 'Buddha and His Life',
    difficulty: 'Easy',
    questionTemplate: 'Buddha attained Buddhahood under _______ at Buddhagaya.',
    correctAnswerFormula: 'Sri. Maha Bodhi',
    wrongAnswers: ['Nuga tree', 'Ashoka bodhi'],
    methodSteps: ['The Buddha attained Enlightenment under the Sri Maha Bodhi tree at Buddhagaya.', 'This sacred tree is still in India.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'bud-mar21-first-worship',
    topic: 'Temple',
    category: 'Temple and Worship',
    difficulty: 'Easy',
    questionTemplate: 'We should first worship the _______ when we go to the temple.',
    correctAnswerFormula: 'Pagoda',
    wrongAnswers: ['Bodhi tree', 'Buddha Image'],
    methodSteps: ['Different temples may have different orders of worship.', 'The mark scheme indicates Pagoda for this question.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'bud-mar21-teacher-prince',
    topic: 'Prince Siddhartha',
    category: 'Buddha and His Life',
    difficulty: 'Easy',
    questionTemplate: 'Ascetic _______ was the teacher of Prince Siddhartha.',
    correctAnswerFormula: 'Sarvamitra',
    wrongAnswers: ['Asita', 'Kondanna'],
    methodSteps: ['Brahmin Sarvamitra (Ascetic Sarvamitra) was the teacher of Prince Siddhartha.', 'He taught the prince various subjects.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'bud-mar21-triple-gem',
    topic: 'Triple Gem',
    category: 'Buddha and His Life',
    difficulty: 'Easy',
    questionTemplate: 'Buddha, Dhamma and Sangha is known as the _______.',
    correctAnswerFormula: 'Triple Gem',
    wrongAnswers: ['Trilakkana', 'Thrishiksha'],
    methodSteps: ['The three refuges are Buddha, Dhamma, and Sangha.', 'Together they are called the Triple Gem (Thunuwila).'],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },
  {
    id: 'bud-mar21-good-quality-child',
    topic: 'Good Qualities',
    category: 'Good Qualities',
    difficulty: 'Easy',
    questionTemplate: '_______ is a good quality of a child.',
    correctAnswerFormula: 'Speak the truth to parents',
    wrongAnswers: ['Telling lies', 'Not obedient'],
    methodSteps: ['A good Buddhist child speaks the truth.', 'Being obedient and honest are important qualities.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'bud-mar21-loweda-author',
    topic: 'Loweda Sangarawa',
    category: 'Buddhist History - Sri Lanka',
    difficulty: 'Medium',
    questionTemplate: 'Loweda Sangarawa is a book of poems written by _______ Thero.',
    correctAnswerFormula: 'Weedagama Maithriya',
    wrongAnswers: ['Rerukane chandawimala', 'Welivita Saranankara'],
    methodSteps: ['Loweda Sangarawa was written by Venerable Weedagama Maithriya Thero during the Kotte Period.', 'It teaches us to take care of animals.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'bud-mar21-not-good-friend',
    topic: 'Good Friend',
    category: 'Good Qualities',
    difficulty: 'Easy',
    questionTemplate: '_______ is not a quality of a good friend.',
    correctAnswerFormula: 'Being with you only in happiness',
    wrongAnswers: ['Helping others', 'Explaining what is bad and good'],
    methodSteps: ['A good friend is with you in both happiness and sadness.', 'Being with you only when things are good is not a true quality of friendship.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'bud-mar21-not-take-temple',
    topic: 'Temple',
    category: 'Temple and Worship',
    difficulty: 'Easy',
    questionTemplate: '_______ is not a thing we take to the temple.',
    correctAnswerFormula: 'Candles',
    wrongAnswers: ['Joss-sticks', 'Flowers'],
    methodSteps: ['We take flowers, joss sticks, oil, and gilanpasa to the temple.', 'Candles are not typically taken (we use oil lamps).'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'bud-mar21-precepts-daily',
    topic: 'Precepts',
    category: 'Precepts and Morality',
    difficulty: 'Easy',
    questionTemplate: 'We observe _______ precepts daily.',
    correctAnswerFormula: '5',
    wrongAnswers: ['8', '10'],
    methodSteps: ['We observe the five precepts (Pansil) daily.', 'On Poya days we observe eight or ten precepts.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },
  {
    id: 'bud-mar21-jataka-thittira',
    topic: 'Jataka',
    category: 'Jataka Stories',
    difficulty: 'Easy',
    questionTemplate: 'Which Jataka story has the Vatu bird and the Elephant who respected elders?',
    correctAnswerFormula: 'Thittira',
    wrongAnswers: ['Sama', 'Temiya'],
    methodSteps: ['Thittira (Tittira) Jataka is about respecting elders.', 'The Vatu bird received respect from the two friends.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'bud-mar21-bo-sapling-brought',
    topic: 'Sri Maha Bodhi',
    category: 'Buddhist History - Sri Lanka',
    difficulty: 'Easy',
    questionTemplate: 'Who brought the Bo sapling of Sri Maha Bodhi to Sri Lanka?',
    correctAnswerFormula: 'Arahath Sanghamitta Therani',
    wrongAnswers: ['Arahath Mahinda Thero', 'King Devanampiyatissa'],
    methodSteps: ['Arahath Sanghamitta Therani brought the Bo sapling to Sri Lanka.', 'It was planted on an Unduvap Poya day in Mahamevna Park, Anuradhapura.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'bud-mar21-first-bhikkuni',
    topic: 'Bhikkuni Sasana',
    category: 'Buddhist History - Sri Lanka',
    difficulty: 'Easy',
    questionTemplate: 'Who was the first Bhikkuni of the Bhikkuni Sasana of Sri Lanka?',
    correctAnswerFormula: 'Anula Devi',
    wrongAnswers: ['Yashodara Devi', 'Mahamaya Devi'],
    methodSteps: ['Queen Anula Devi was ordained as the first Bhikkuni in Sri Lanka.', 'The Bhikkuni order was started by Sanghamitta Therani.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  // ========== March 2022 ==========
  {
    id: 'bud-mar22-first-worship',
    topic: 'Temple',
    category: 'Temple and Worship',
    difficulty: 'Easy',
    questionTemplate: '_______ is the first place we worship in the temple.',
    correctAnswerFormula: 'Bo-tree',
    wrongAnswers: ['Buddha Image', 'Pagoda'],
    methodSteps: ['We usually worship the Bo tree first when we go to the temple.', 'Then we worship the Buddha image and the Pagoda.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'bud-mar22-bo-planted-poya',
    topic: 'Sri Maha Bodhi',
    category: 'Buddhist History - Sri Lanka',
    difficulty: 'Easy',
    questionTemplate: 'On the _______ Poya day, the Bo sapling of Jaya Sri Maha Bodhi was planted in the Mahamevna Park.',
    correctAnswerFormula: 'Unduvap',
    wrongAnswers: ['Esala', 'Vap'],
    methodSteps: ['The Bo sapling was brought on an Unduvap Poya day.', 'It was planted in Mahamevna Uyana (Park), Anuradhapura.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'bud-mar22-birthday-good',
    topic: 'Merit',
    category: 'Good Qualities',
    difficulty: 'Easy',
    questionTemplate: '_______ is a good thing we can do on our birthday.',
    correctAnswerFormula: 'Going to the temple',
    wrongAnswers: ['Watching cartoons', 'Playing with friends'],
    methodSteps: ['As Buddhist children we can do merit on our birthday.', 'Going to the temple, offering dana, and helping the poor are good.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'bud-mar22-horse-siddhartha',
    topic: 'Prince Siddhartha',
    category: 'Buddha and His Life',
    difficulty: 'Easy',
    questionTemplate: 'The horse of Prince Siddhartha was _______.',
    correctAnswerFormula: 'Kanthaka',
    wrongAnswers: ['Asura', 'Kandula'],
    methodSteps: ['Kanthaka was the horse of Prince Siddhartha.', 'The prince left the palace on Kanthaka on the night of the Great Renunciation.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'bud-mar22-king-sanghamitta',
    topic: 'Sanghamitta',
    category: 'Buddhist History - Sri Lanka',
    difficulty: 'Easy',
    questionTemplate: '_______ was ruling in Sri Lanka when Arahath Sanghamitta Therani arrived.',
    correctAnswerFormula: 'King Devanampiyatissa',
    wrongAnswers: ['King Dutugemunu', 'King Dharmashoka'],
    methodSteps: ['King Devanampiyatissa was the king when Mahinda Thero and Sanghamitta Therani came to Sri Lanka.', 'Dharmashoka was the Indian emperor, father of Sanghamitta.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'bud-mar22-buddhist-flag',
    topic: 'Symbols',
    category: 'Temple and Worship',
    difficulty: 'Easy',
    questionTemplate: 'This is the _______ (symbol with six colours).',
    correctAnswerFormula: 'Buddhist flag',
    wrongAnswers: ['Dhamma Chakra', 'Tripitaka'],
    methodSteps: ['The Buddhist flag has six colours.', 'The Dhamma Chakra has eight spokes.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },
  {
    id: 'bud-mar22-good-friend-quality',
    topic: 'Good Friend',
    category: 'Good Qualities',
    difficulty: 'Easy',
    questionTemplate: '_______ is a quality of a good friend.',
    correctAnswerFormula: 'Be in happiness and sadness',
    wrongAnswers: ['Not helping the other', 'Not explain what is wrong'],
    methodSteps: ['A good friend is with you in both good and bad times.', 'They help and explain what is right and wrong.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'bud-mar22-not-in-temple',
    topic: 'Temple',
    category: 'Temple and Worship',
    difficulty: 'Easy',
    questionTemplate: 'A thing we should not do in the temple is _______.',
    correctAnswerFormula: 'shout',
    wrongAnswers: ['meditate', 'sweep'],
    methodSteps: ['We should be quiet and respectful in the temple.', 'Shouting is not appropriate. We meditate and can help sweep.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },
  {
    id: 'bud-mar22-precepts-five',
    topic: 'Precepts',
    category: 'Precepts and Morality',
    difficulty: 'Easy',
    questionTemplate: 'We observe _______ precepts daily.',
    correctAnswerFormula: '5',
    wrongAnswers: ['8', '10'],
    methodSteps: ['The five precepts (Pansil) are observed daily by Buddhists.', 'On Poya days we observe eight precepts.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },
  {
    id: 'bud-mar22-jataka-thittira',
    topic: 'Jataka',
    category: 'Jataka Stories',
    difficulty: 'Easy',
    questionTemplate: 'This is the _______ Jathaka story (Vatu bird and Elephant).',
    correctAnswerFormula: 'Thittira',
    wrongAnswers: ['Sama', 'Temiya'],
    methodSteps: ['Thittira Jataka teaches us to respect elders.', 'The Vatu bird was respected by the Elephant and the Monkey.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'bud-mar22-respected-elders',
    topic: 'Jataka',
    category: 'Jataka Stories',
    difficulty: 'Easy',
    questionTemplate: '_______ received due respect from the two friends in the Thittira Jataka.',
    correctAnswerFormula: 'Elephant',
    wrongAnswers: ['Vatu bird', 'Monkey'],
    methodSteps: ['In the story, the Elephant showed respect to the Vatu bird (elder).', 'The Elephant was respected by the others for his behaviour.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'bud-mar22-moral-story',
    topic: 'Jataka',
    category: 'Jataka Stories',
    difficulty: 'Easy',
    questionTemplate: 'The moral we learn from the Thittira Jataka story is _______.',
    correctAnswerFormula: 'Respecting Elders',
    wrongAnswers: ['Helping a friend in need', 'Looking after animals'],
    methodSteps: ['Thittira Jataka teaches us to respect elders.', 'The Vatu bird was the elder who received respect.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'bud-mar22-father-siddhartha',
    topic: 'Prince Siddhartha',
    category: 'Buddha and His Life',
    difficulty: 'Easy',
    questionTemplate: 'Who was the father of Prince Siddhartha?',
    correctAnswerFormula: 'King Suddhodana',
    wrongAnswers: ['King Dharmashoka', 'Brahmin Sarvamithra'],
    methodSteps: ['King Suddhodana was the father of Prince Siddhartha.', 'Queen Mahamaya was his mother.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'bud-mar22-teacher-siddhartha',
    topic: 'Prince Siddhartha',
    category: 'Buddha and His Life',
    difficulty: 'Easy',
    questionTemplate: 'Who was the teacher of Prince Siddhartha?',
    correctAnswerFormula: 'Brahmin Sarvamithra',
    wrongAnswers: ['King Suddhodana', 'King Dharmashoka'],
    methodSteps: ['Brahmin (Ascetic) Sarvamitra was the teacher of Prince Siddhartha.', 'He taught the prince reading, writing, and other subjects.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'bud-mar22-loweda-author',
    topic: 'Loweda Sangarawa',
    category: 'Buddhist History - Sri Lanka',
    difficulty: 'Medium',
    questionTemplate: 'Who wrote Loweda Sangarawa?',
    correctAnswerFormula: 'Weedagama Maithriya Maha Thero',
    wrongAnswers: ['Rerukane Chandawimala', 'Welivita Saranankara'],
    methodSteps: ['Loweda Sangarawa was written by Venerable Weedagama Maithriya Thero.', 'It teaches us to be kind to animals.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  // ========== March 2023 ==========
  {
    id: 'bud-mar23-dhamma-chakra-parts',
    topic: 'Dhamma Chakra',
    category: 'Temple and Worship',
    difficulty: 'Easy',
    questionTemplate: 'There are _______ parts in the Dhamma Chakra.',
    correctAnswerFormula: 'eight',
    wrongAnswers: ['six', 'seven'],
    methodSteps: ['The Dhamma Chakra (Dharmachakra) has eight spokes.', 'They represent the Noble Eightfold Path.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },
  {
    id: 'bud-mar23-migara-mata',
    topic: 'Visakha',
    category: 'Buddhist History - Sri Lanka',
    difficulty: 'Easy',
    questionTemplate: '_______ was known as Migara Mata.',
    correctAnswerFormula: 'Visakha',
    wrongAnswers: ['Yashodara', 'Anula'],
    methodSteps: ['Visakha was known as Migara Mata (mother of Migara).', 'She was the chief female lay disciple (Upasika) of the Buddha.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'bud-mar23-ploughing-ceremony',
    topic: 'Prince Siddhartha',
    category: 'Buddha and His Life',
    difficulty: 'Easy',
    questionTemplate: 'On the ploughing ceremony day, King Suddhodana worshipped Prince Siddhartha for the _______ time.',
    correctAnswerFormula: 'first',
    wrongAnswers: ['second', 'third'],
    methodSteps: ['During the ploughing ceremony, the young prince sat under a tree in meditation.', 'King Suddhodana worshipped him for the first time then.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'bud-mar23-kisagotami',
    topic: 'Buddha',
    category: 'Buddha and His Life',
    difficulty: 'Easy',
    questionTemplate: 'Buddha preached Dhamma and helped _______ to overcome her problem.',
    correctAnswerFormula: 'Kisagotami',
    wrongAnswers: ['Rajjumala', 'Mahamaya'],
    methodSteps: ['Kisagotami had lost her child and was in grief.', 'The Buddha helped her understand the nature of life and death through the mustard seed story.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'bud-mar23-not-good-student',
    topic: 'Good Qualities',
    category: 'Good Qualities',
    difficulty: 'Easy',
    questionTemplate: '_______ is not a quality of a good student.',
    correctAnswerFormula: 'Getting up late in the morning',
    wrongAnswers: ['Worshipping Buddha', 'Following the advices of parents'],
    methodSteps: ['A good student wakes up early and follows discipline.', 'Getting up late is not a good habit.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'bud-mar23-buddha-grateful-bodhi',
    topic: 'Buddha',
    category: 'Buddha and His Life',
    difficulty: 'Easy',
    questionTemplate: 'Buddha was grateful to Sri Maha Bodhi and _______.',
    correctAnswerFormula: 'recited gathas for one whole week',
    wrongAnswers: ['was gazing at the Bodhi tree one whole week', 'watered the Bodhi tree for one whole week'],
    methodSteps: ['The Buddha spent one week gazing at the Bodhi tree in gratitude (Gatha Bandima).', 'He recited gathas (verses) in praise of the tree.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'bud-mar23-medicinal-plants-benefit',
    topic: 'Medicinal Plants',
    category: 'Good Qualities',
    difficulty: 'Easy',
    questionTemplate: '_______ is a benefit of planting medicinal plants in our garden.',
    correctAnswerFormula: 'Becoming healthy',
    wrongAnswers: ['Spreading diseases', 'Not beautifying the skin'],
    methodSteps: ['Medicinal plants help us stay healthy and cure illnesses.', 'They also beautify the garden.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'bud-mar23-destroying-life-sin',
    topic: 'Precepts',
    category: 'Precepts and Morality',
    difficulty: 'Easy',
    questionTemplate: '_______ states that destroying the life of living beings is a great sin.',
    correctAnswerFormula: 'Loweda Sangarawa',
    wrongAnswers: ['Buduguna Alankaraya', 'Sirith Maldama'],
    methodSteps: ['The first precept is to abstain from killing.', 'Loweda Sangarawa (and the five precepts) teach that destroying life is wrong.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'bud-mar23-quality-good-friend',
    topic: 'Good Friend',
    category: 'Good Qualities',
    difficulty: 'Easy',
    questionTemplate: '_______ is a quality of a good friend.',
    correctAnswerFormula: 'Explaining what is wrong and what is correct',
    wrongAnswers: ['Doing bad things with the friend', 'Being with the friend only in happiness'],
    methodSteps: ['A good friend helps you understand right and wrong.', 'They stay with you in both happiness and sadness.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'bud-mar23-visakha-father',
    topic: 'Visakha',
    category: 'Buddhist History - Sri Lanka',
    difficulty: 'Easy',
    questionTemplate: 'Father of Visakha was _______.',
    correctAnswerFormula: 'Dananjaya',
    wrongAnswers: ['Migara', 'Punnawardana'],
    methodSteps: ['Visakha\'s father was Dananjaya.', 'Migara was her son (she was called Migara Mata - mother of Migara).'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'bud-mar23-visakha-sotapanna',
    topic: 'Visakha',
    category: 'Buddhist History - Sri Lanka',
    difficulty: 'Easy',
    questionTemplate: 'Visakha attained Sotapanna at the age of _______.',
    correctAnswerFormula: 'eight',
    wrongAnswers: ['seven', 'nine'],
    methodSteps: ['Visakha attained Sotapanna at a young age.', 'She was a devoted follower of the Buddha.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'bud-mar23-visakha-married',
    topic: 'Visakha',
    category: 'Buddhist History - Sri Lanka',
    difficulty: 'Easy',
    questionTemplate: 'Visakha married _______.',
    correctAnswerFormula: 'Punnawardana',
    wrongAnswers: ['Anepidu', 'Migara'],
    methodSteps: ['Visakha married Punnawardana.', 'She offered Poorvarama (Purvarama) temple to the Buddha.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'bud-mar23-visakha-offered',
    topic: 'Visakha',
    category: 'Buddhist History - Sri Lanka',
    difficulty: 'Easy',
    questionTemplate: 'Visakha offered _______ to Buddha.',
    correctAnswerFormula: 'Poorvarama',
    wrongAnswers: ['Jetawanarama', 'Nigrodharamaya'],
    methodSteps: ['Visakha offered the Poorvarama (Purvarama) temple to the Buddha.', 'She was known as the chief female lay disciple.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'bud-mar23-salikedara-jataka',
    topic: 'Jataka',
    category: 'Jataka Stories',
    difficulty: 'Easy',
    questionTemplate: 'This is _______ (Jataka about bird and elephant).',
    correctAnswerFormula: 'Tittira Jatakaya',
    wrongAnswers: ['Salikedara Jataka', 'Sama Jataka'],
    methodSteps: ['Tittira (Thittira) Jatakaya teaches respecting elders.', 'Salikedara is another Jataka; the picture question referred to Tittira.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'bud-mar23-moral-respecting',
    topic: 'Jataka',
    category: 'Jataka Stories',
    difficulty: 'Easy',
    questionTemplate: 'The moral of the Tittira Jataka story is _______.',
    correctAnswerFormula: 'respecting elders',
    wrongAnswers: ['listening to parents', 'helping friends'],
    methodSteps: ['Tittira Jataka teaches us to respect elders.', 'The Vatu bird was the elder who received respect.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'bud-mar23-bo-planted-where',
    topic: 'Sri Maha Bodhi',
    category: 'Buddhist History - Sri Lanka',
    difficulty: 'Easy',
    questionTemplate: 'Where is the Bo sapling of Sri Maha Bodhi planted in Anuradhapura?',
    correctAnswerFormula: 'Mahamewna Uyana',
    wrongAnswers: ['Kelaniya', 'Kandy'],
    methodSteps: ['The Bo sapling was planted in Mahamevna (Mahamewna) Uyana, Anuradhapura.', 'It was planted on an Unduvap Poya day.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  // ========== July 2021 ==========
  {
    id: 'bud-jul21-flag-colours',
    topic: 'Buddhist Flag',
    category: 'Temple and Worship',
    difficulty: 'Easy',
    questionTemplate: 'There are _______ colours in the Buddhist flag.',
    correctAnswerFormula: 'six',
    wrongAnswers: ['five', 'seven'],
    methodSteps: ['The Buddhist flag has six colours: blue, yellow, red, white, orange, and the sixth band (combined).', 'Each colour has a meaning.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },
  {
    id: 'bud-jul21-buddha-second-visit',
    topic: 'Buddha Visits',
    category: 'Buddhist History - Sri Lanka',
    difficulty: 'Easy',
    questionTemplate: 'The Buddha visited _______ during his second visit to Sri Lanka.',
    correctAnswerFormula: 'Kelaniya',
    wrongAnswers: ['Mahiyanganaya', 'Nagadeepa'],
    methodSteps: ['Buddha visited Mahiyanganaya on the first visit, Nagadeepa on the third.', 'Kelaniya was the second visit, invited by King Maniakkika.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'bud-jul21-devadatta',
    topic: 'Buddha',
    category: 'Buddha and His Life',
    difficulty: 'Easy',
    questionTemplate: '_______ tried to take revenge from the Buddha.',
    correctAnswerFormula: 'Devadatta',
    wrongAnswers: ['Kondanna', 'Upali'],
    methodSteps: ['Devadatta was the Buddha\'s cousin who tried to harm him.', 'Kondanna was one of the first five disciples; Upali was a barber who became an arahant.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'bud-jul21-take-to-temple',
    topic: 'Temple',
    category: 'Temple and Worship',
    difficulty: 'Easy',
    questionTemplate: 'We take _______ to the temple.',
    correctAnswerFormula: 'flowers',
    wrongAnswers: ['candles', 'kites'],
    methodSteps: ['We offer flowers, joss sticks, oil, and gilanpasa to the Buddha at the temple.', 'Flowers are a common offering.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },
  {
    id: 'bud-jul21-loving-kindness',
    topic: 'Metta',
    category: 'Precepts and Morality',
    difficulty: 'Easy',
    questionTemplate: 'Instead of _______ we must spread loving kindness.',
    correctAnswerFormula: 'anger',
    wrongAnswers: ['happiness', 'patience'],
    methodSteps: ['Metta (loving kindness) is the opposite of anger and hatred.', 'We spread metta to all living beings.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'bud-jul21-first-bhikkuni',
    topic: 'Bhikkuni',
    category: 'Buddhist History - Sri Lanka',
    difficulty: 'Easy',
    questionTemplate: '_______ was the first Bhikkuni of the Bhikkuni Sasana of Sri Lanka.',
    correctAnswerFormula: 'Anula Devi',
    wrongAnswers: ['Yashodara Devi', 'Mahamaya Devi'],
    methodSteps: ['Queen Anula Devi was ordained as the first Bhikkuni in Sri Lanka.', 'Sanghamitta Therani started the Bhikkuni order here.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'bud-jul21-tooth-relic-king',
    topic: 'Tooth Relic',
    category: 'Buddhist History - Sri Lanka',
    difficulty: 'Medium',
    questionTemplate: '_______ was ruling in Sri Lanka when the Sacred Tooth Relic was brought to Sri Lanka.',
    correctAnswerFormula: 'King Kithsiri Mewan',
    wrongAnswers: ['King Kawantissa', 'King Devanampiyatissa'],
    methodSteps: ['The Sacred Tooth Relic was brought during the reign of King Kithsiri Mevan (Kirtti Sri Meghavanna).', 'Prince Danta and Princess Hemamala brought it.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'bud-jul21-dalada-maligawa',
    topic: 'Temple',
    category: 'Buddhist History - Sri Lanka',
    difficulty: 'Easy',
    questionTemplate: 'The Temple of the Sacred Tooth Relic is called _______.',
    correctAnswerFormula: 'Dalada Maligawa',
    wrongAnswers: ['Kelaniya Temple', 'Mahiyangana Temple'],
    methodSteps: ['Dalada Maligawa is in Kandy and enshrines the Tooth Relic.', 'It was brought by Prince Danta and Princess Hemamala.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'bud-jul21-dalada-situated',
    topic: 'Temple',
    category: 'Buddhist History - Sri Lanka',
    difficulty: 'Easy',
    questionTemplate: 'Dalada Maligawa is situated in _______.',
    correctAnswerFormula: 'Kandy',
    wrongAnswers: ['Anuradhapura', 'Kelaniya'],
    methodSteps: ['The Temple of the Tooth is in Kandy.', 'It is a UNESCO World Heritage site.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },
  {
    id: 'bud-jul21-prince-siddhartha-born',
    topic: 'Prince Siddhartha',
    category: 'Buddha and His Life',
    difficulty: 'Easy',
    questionTemplate: 'Prince Siddhartha was born on a _______ Poya day.',
    correctAnswerFormula: 'Vesak',
    wrongAnswers: ['Unduvap', 'Esala'],
    methodSteps: ['Prince Siddhartha was born on a Vesak full moon day in Lumbini.', 'Vesak celebrates the Birth, Enlightenment, and Passing Away of the Buddha.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'bud-jul21-precepts-poya',
    topic: 'Precepts',
    category: 'Precepts and Morality',
    difficulty: 'Easy',
    questionTemplate: 'We observe _______ precepts on Poya days.',
    correctAnswerFormula: 'eight',
    wrongAnswers: ['five', 'ten'],
    methodSteps: ['On Poya days Buddhists often observe eight precepts (Atasil).', 'Daily we observe five precepts.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'bud-jul21-girls-meditation',
    topic: 'Meditation',
    category: 'Temple and Worship',
    difficulty: 'Easy',
    questionTemplate: '_______ is the way girls sit to do meditation.',
    correctAnswerFormula: 'Ardha Paryanka',
    wrongAnswers: ['Baddha Paryanka', 'Padmasana'],
    methodSteps: ['Ardha Paryanka is the sitting posture for girls during meditation.', 'Baddha Paryanka is for boys.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'bud-jul21-boys-meditation',
    topic: 'Meditation',
    category: 'Temple and Worship',
    difficulty: 'Easy',
    questionTemplate: '_______ is the way boys sit to do meditation.',
    correctAnswerFormula: 'Baddha Paryanka',
    wrongAnswers: ['Ardha Paryanka', 'Padmasana'],
    methodSteps: ['Baddha Paryanka is the sitting posture for boys during meditation.', 'Ardha Paryanka is for girls.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'bud-jul21-kelaniya-visit',
    topic: 'Kelaniya',
    category: 'Buddhist History - Sri Lanka',
    difficulty: 'Easy',
    questionTemplate: 'Buddha visited Kelaniya Temple during His _______ visit to Sri Lanka.',
    correctAnswerFormula: 'third',
    wrongAnswers: ['second', 'first'],
    methodSteps: ['Buddha visited Sri Lanka three times.', 'First: Mahiyanganaya, Second: Nagadeepa, Third: Kelaniya (invited by King Maniakkika).'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  // ========== July 2022 ==========
  {
    id: 'bud-jul22-buddha-visits-times',
    topic: 'Buddha Visits',
    category: 'Buddhist History - Sri Lanka',
    difficulty: 'Easy',
    questionTemplate: 'Buddha visited Sri Lanka _______ times.',
    correctAnswerFormula: 'three',
    wrongAnswers: ['two', 'four'],
    methodSteps: ['The Buddha visited Sri Lanka three times.', 'Mahiyanganaya, Nagadeepa, and Kelaniya.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },
  {
    id: 'bud-jul22-father-sanghamitta',
    topic: 'Sanghamitta',
    category: 'Buddhist History - Sri Lanka',
    difficulty: 'Easy',
    questionTemplate: 'King _______ was the father of Sangamitta Therani.',
    correctAnswerFormula: 'Dharmashoka',
    wrongAnswers: ['Devanampiyatissa', 'Dutugemunu'],
    methodSteps: ['King Dharmashoka (Ashoka) of India was the father of Sanghamitta Therani.', 'King Devanampiyatissa was ruling Sri Lanka when she arrived.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'bud-jul22-rajjumala',
    topic: 'Buddha',
    category: 'Buddha and His Life',
    difficulty: 'Easy',
    questionTemplate: 'Buddha preached to _______ that destroying human life is a foolish act.',
    correctAnswerFormula: 'Rajjumala',
    wrongAnswers: ['Sanghamitta', 'Visakha'],
    methodSteps: ['Rajjumala had tried to take her life in grief.', 'The Buddha taught her that human life is precious and difficult to obtain.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'bud-jul22-precepts-poya',
    topic: 'Precepts',
    category: 'Precepts and Morality',
    difficulty: 'Easy',
    questionTemplate: 'On Poya days we observe _______ precepts.',
    correctAnswerFormula: 'eight',
    wrongAnswers: ['five', 'nine'],
    methodSteps: ['On Poya days we observe eight precepts (Atasil).', 'Daily we observe five precepts.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'bud-jul22-migara-mata',
    topic: 'Visakha',
    category: 'Buddhist History - Sri Lanka',
    difficulty: 'Easy',
    questionTemplate: 'Who was known as Migara Mata?',
    correctAnswerFormula: 'Visakha',
    wrongAnswers: ['Anula', 'Yashodara'],
    methodSteps: ['Visakha was known as Migara Mata (mother of Migara).', 'She offered Poorvarama temple to the Buddha.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'bud-jul22-temple-visakha',
    topic: 'Visakha',
    category: 'Buddhist History - Sri Lanka',
    difficulty: 'Easy',
    questionTemplate: 'What was the temple offered by Visakha to the Buddha?',
    correctAnswerFormula: 'Poorvarama',
    wrongAnswers: ['Jetawanarama', 'Nigrodharamaya'],
    methodSteps: ['Visakha offered Poorvarama (Purvarama) to the Buddha.', 'She was the chief female lay disciple.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'bud-jul22-triple-gem-order',
    topic: 'Triple Gem',
    category: 'Buddha and His Life',
    difficulty: 'Easy',
    questionTemplate: 'Name the Triple Gem in order.',
    correctAnswerFormula: 'Buddha, Dhamma, Sangha',
    wrongAnswers: ['Sangha, Buddha, Dhamma', 'Dhamma, Sangha, Buddha'],
    methodSteps: ['The Triple Gem is Buddha, Dhamma, and Sangha in that order.', 'We take refuge in them in this order.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'bud-jul22-flag-five-colours',
    topic: 'Buddhist Flag',
    category: 'Temple and Worship',
    difficulty: 'Easy',
    questionTemplate: 'There are five colours in the Buddhist flag. True or False?',
    correctAnswerFormula: 'False',
    wrongAnswers: ['True'],
    methodSteps: ['The Buddhist flag has six colours, not five.', 'Blue, yellow, red, white, orange, and the sixth band.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },
  {
    id: 'bud-jul22-tooth-relic-poya',
    topic: 'Tooth Relic',
    category: 'Buddhist History - Sri Lanka',
    difficulty: 'Easy',
    questionTemplate: 'The Tooth Relic of Buddha was brought to Sri Lanka on a _______ Poya day.',
    correctAnswerFormula: 'Esala',
    wrongAnswers: ['Vesak', 'Unduvap'],
    methodSteps: ['The Sacred Tooth Relic was brought on an Esala Poya day.', 'Prince Danta and Princess Hemamala brought it.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'bud-jul22-kelaniya-poya',
    topic: 'Kelaniya',
    category: 'Buddhist History - Sri Lanka',
    difficulty: 'Easy',
    questionTemplate: 'Buddha visited Kelaniya on a _______ Poya day.',
    correctAnswerFormula: 'Vesak',
    wrongAnswers: ['Esala', 'Poson'],
    methodSteps: ['Buddha visited Kelaniya on a Vesak Poya day.', 'King Maniakkika invited him.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'bud-jul22-dalada-brought-by',
    topic: 'Tooth Relic',
    category: 'Buddhist History - Sri Lanka',
    difficulty: 'Easy',
    questionTemplate: 'The Tooth Relic was brought to Sri Lanka by _______.',
    correctAnswerFormula: 'Prince Danta and Princess Hemamala',
    wrongAnswers: ['Prince Aritta and Princess Swarnamali', 'Arahath Mahinda'],
    methodSteps: ['Prince Danta (Dantha) and Princess Hemamala brought the Sacred Tooth Relic.', 'They hid it in Princess Hemamala\'s hair.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  // ========== July 2023 ==========
  {
    id: 'bud-jul23-we-take-temple',
    topic: 'Temple',
    category: 'Temple and Worship',
    difficulty: 'Easy',
    questionTemplate: 'We take _______ to the temple.',
    correctAnswerFormula: 'flowers',
    wrongAnswers: ['toys', 'weapons'],
    methodSteps: ['We offer flowers, joss sticks, oil, and gilanpasa at the temple.', 'These are traditional offerings.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },
  {
    id: 'bud-jul23-yassa-muule',
    topic: 'Gatha',
    category: 'Temple and Worship',
    difficulty: 'Easy',
    questionTemplate: 'We chant the Gatha \'Yassa Muule Nissinnova\' to salute the _______.',
    correctAnswerFormula: 'Bo tree',
    wrongAnswers: ['Chaithya', 'Buddha statue'],
    methodSteps: ['This gatha is chanted when worshipping the Bo tree.', 'We pay respect to the Sri Maha Bodhi.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'bud-jul23-metta-meditation',
    topic: 'Meditation',
    category: 'Temple and Worship',
    difficulty: 'Easy',
    questionTemplate: 'We spread loving kindness to all living beings when we are doing _______ meditation.',
    correctAnswerFormula: 'Metta',
    wrongAnswers: ['Anapanasathi', 'Sakman'],
    methodSteps: ['Metta Bhavana is loving kindness meditation.', 'We wish all beings to be well and happy.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'bud-jul23-brother-sanghamitta',
    topic: 'Sanghamitta',
    category: 'Buddhist History - Sri Lanka',
    difficulty: 'Easy',
    questionTemplate: '_______ was the brother of Sangamitta Therani.',
    correctAnswerFormula: 'Arahant Mahinda Thero',
    wrongAnswers: ['King Dharmashoka', 'Prince Siddhartha'],
    methodSteps: ['Arahath Mahinda Thero was the brother of Sanghamitta Therani.', 'He brought Buddhism to Sri Lanka; she brought the Bo sapling.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'bud-jul23-birthday-alms',
    topic: 'Merit',
    category: 'Good Qualities',
    difficulty: 'Easy',
    questionTemplate: 'We can _______ on our birthday as Buddhist children.',
    correctAnswerFormula: 'give alms to the poor',
    wrongAnswers: ['have a grand party', 'not go to the temple'],
    methodSteps: ['Doing merit on our birthday is a good practice.', 'We can offer dana, go to the temple, or help the poor.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'bud-jul23-flag-no-green',
    topic: 'Buddhist Flag',
    category: 'Temple and Worship',
    difficulty: 'Easy',
    questionTemplate: 'Which colour is not in the Buddhist flag?',
    correctAnswerFormula: 'Green',
    wrongAnswers: ['Red', 'Blue'],
    methodSteps: ['The Buddhist flag has blue, yellow, red, white, and orange.', 'Green is not one of the six colours.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },
  {
    id: 'bud-jul23-loweda-true',
    topic: 'Loweda Sangarawa',
    category: 'Buddhist History - Sri Lanka',
    difficulty: 'Easy',
    questionTemplate: '\'Loweda Sangarawa\' is a book of kavi which gives us good advice. True or False?',
    correctAnswerFormula: 'True',
    wrongAnswers: ['False'],
    methodSteps: ['Loweda Sangarawa is a book of poems (kavi) that gives good advice about caring for animals.', 'It was written by Weedagama Maithriya Thero.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'bud-jul23-tooth-relic-esala',
    topic: 'Tooth Relic',
    category: 'Buddhist History - Sri Lanka',
    difficulty: 'Easy',
    questionTemplate: 'On _______ Poya day the Sacred Tooth Relic of Buddha was brought to Sri Lanka.',
    correctAnswerFormula: 'Esala',
    wrongAnswers: ['Unduvap', 'Vesak'],
    methodSteps: ['The Tooth Relic was brought on an Esala Poya day.', 'The Bo sapling was brought on an Unduvap Poya day.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'bud-jul23-nagadeepa-visit',
    topic: 'Buddha Visits',
    category: 'Buddhist History - Sri Lanka',
    difficulty: 'Easy',
    questionTemplate: 'Buddha\'s _______ visit to Sri Lanka was to Nagadeepa.',
    correctAnswerFormula: 'second',
    wrongAnswers: ['first', 'third'],
    methodSteps: ['First visit: Mahiyanganaya. Second: Nagadeepa (to settle a dispute). Third: Kelaniya.', 'So Nagadeepa was the second visit.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
];

export function getBuddhismTemplates(): QuestionTemplate[] {
  return buddhismTemplates;
}
