import { QuestionTemplate } from '@/types/question-template';

/**
 * Computing Question Templates - Grade 3
 * Extracted from 2024-2025 Computing papers
 * Total: 92 questions
 */

export const COMPUTING_CATEGORIES = [
  'Internet and Web',
  'Internet Safety',
  'Storage Devices',
  'Printers',
  'Input Devices',
  'File Management',
  'Software Applications',
  'Hardware',
] as const;

export const computingTemplates: QuestionTemplate[] = [
  // ========== Formative Assessment - January 2025 ==========
  {
    id: 'comp_2025_jan_01',
    topic: 'Internet',
    category: 'Internet and Web',
    difficulty: 'Easy',
    questionTemplate: 'You can search and find information on any subject using the ___.',
    correctAnswerFormula: 'internet',
    wrongAnswers: ['computer', 'keyboard', 'printer'],
    methodSteps: ['The internet is a global network that allows you to search and find information on any subject using search engines and websites.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'comp_2025_jan_02a',
    topic: 'Wiki',
    category: 'Internet and Web',
    difficulty: 'Medium',
    questionTemplate: 'Examples of Wiki\'s are ___ and ___.',
    correctAnswerFormula: 'Wikibooks and Wikinews',
    wrongAnswers: ['Wikipedia and Facebook', 'Google and Yahoo', 'YouTube and Instagram'],
    methodSteps: ['Wikis are collaborative websites. Examples include Wikibooks (a collection of educational textbooks) and Wikinews (a news source), along with Wikipedia, Wiktionary, and others in the Wiki family.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'comp_2025_jan_03',
    topic: 'Search',
    category: 'Internet and Web',
    difficulty: 'Easy',
    questionTemplate: 'You can type keywords inside the ___ to find what you are looking for.',
    correctAnswerFormula: 'search box',
    wrongAnswers: ['text box', 'folder', 'email'],
    methodSteps: ['A search box is a text field where you type keywords to search for information on websites or search engines like Google.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'comp_2025_jan_04',
    topic: 'Wikipedia',
    category: 'Internet and Web',
    difficulty: 'Easy',
    questionTemplate: 'Wikipedia is a free ___.',
    correctAnswerFormula: 'encyclopedia',
    wrongAnswers: ['game', 'software', 'computer'],
    methodSteps: ['Wikipedia is a free online encyclopedia that anyone can edit and access. It contains millions of articles on various topics.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'comp_2025_jan_05',
    topic: 'Virus',
    category: 'Internet Safety',
    difficulty: 'Easy',
    questionTemplate: 'Virus is a programme that can get into the computer and cause problems.',
    correctAnswerFormula: 'True',
    wrongAnswers: ['False'],
    methodSteps: ['A computer virus is malicious software that can infect your computer and cause various problems like data loss, slow performance, or system crashes.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'comp_2025_jan_06',
    topic: 'Virus Protection',
    category: 'Internet Safety',
    difficulty: 'Easy',
    questionTemplate: 'Virus can protect your computer.',
    correctAnswerFormula: 'False',
    wrongAnswers: ['True'],
    methodSteps: ['Viruses are harmful programs that damage computers. They do not protect your computer. Anti-virus programs protect your computer from viruses.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'comp_2025_jan_07',
    topic: 'Virus Theft',
    category: 'Internet Safety',
    difficulty: 'Easy',
    questionTemplate: 'Virus can not steal information from computers.',
    correctAnswerFormula: 'False',
    wrongAnswers: ['True'],
    methodSteps: ['Viruses can steal personal information, passwords, and important data from your computer. This is why it\'s important to use anti-virus software.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'comp_2025_jan_08',
    topic: 'Anti-virus',
    category: 'Internet Safety',
    difficulty: 'Easy',
    questionTemplate: 'An Anti-virus programme can protect your computer.',
    correctAnswerFormula: 'True',
    wrongAnswers: ['False'],
    methodSteps: ['Anti-virus programs are designed to detect, prevent, and remove viruses and other malicious software from your computer, keeping it safe.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'comp_2025_jan_09',
    topic: 'Personal Information',
    category: 'Internet Safety',
    difficulty: 'Easy',
    questionTemplate: 'Always give personal information to strangers when you chat with them.',
    correctAnswerFormula: 'False',
    wrongAnswers: ['True'],
    methodSteps: ['You should never give personal information (like your address, phone number, or school name) to strangers online. This is an important safety rule.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  // ========== First Semester Examination - March 2025 ==========
  {
    id: 'comp_2025_mar_01',
    topic: 'Storage Devices',
    category: 'Storage Devices',
    difficulty: 'Medium',
    questionTemplate: 'What is the storage device that cannot store a movie?',
    correctAnswerFormula: 'CD',
    wrongAnswers: ['DVD', 'USB flash memory', 'external hard disk'],
    methodSteps: ['A CD (Compact Disc) typically holds 700MB of data, which is not enough to store a full movie. DVDs, USB drives, and external hard disks have much larger storage capacities suitable for movies.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'comp_2025_mar_02',
    topic: 'Printers',
    category: 'Printers',
    difficulty: 'Medium',
    questionTemplate: 'What is the oldest type of printer?',
    correctAnswerFormula: 'dot matrix',
    wrongAnswers: ['the plotter', 'thermal printer', 'inkjet printer'],
    methodSteps: ['The dot matrix printer is the oldest type of printer listed here. It uses a print head that strikes an ink ribbon to print dots on paper, creating characters and images.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'comp_2025_mar_03',
    topic: 'Microphone',
    category: 'Input Devices',
    difficulty: 'Easy',
    questionTemplate: 'What device can be used to capture your voice?',
    correctAnswerFormula: 'microphone',
    wrongAnswers: ['laser printer', 'camera', 'DVD'],
    methodSteps: ['A microphone is an input device that captures sound and voice. It converts sound waves into electrical signals that the computer can process.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'comp_2025_mar_04',
    topic: 'File Types',
    category: 'File Management',
    difficulty: 'Easy',
    questionTemplate: 'Your family photo can be saved as',
    correctAnswerFormula: 'an image file',
    wrongAnswers: ['a document file', 'a text file', 'an audio file'],
    methodSteps: ['Photos and pictures are saved as image files with extensions like .jpg, .png, or .gif. These formats are designed specifically for storing visual images.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'comp_2025_mar_05',
    topic: 'Inkjet Colors',
    category: 'Printers',
    difficulty: 'Hard',
    questionTemplate: 'Choose the correct pair of colours used in the inkjet printer.',
    correctAnswerFormula: 'black, yellow',
    wrongAnswers: ['orange, cyan', 'magenta, blue', 'black, green'],
    methodSteps: ['Inkjet printers use four basic ink colors: Cyan, Magenta, Yellow, and Black (CMYK). Black and yellow are both part of this standard color set.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 30,
  },
  {
    id: 'comp_2025_mar_06',
    topic: 'Smartphone Storage',
    category: 'Storage Devices',
    difficulty: 'Easy',
    questionTemplate: 'What is the storage device that can be found in a smartphone?',
    correctAnswerFormula: 'memory card',
    wrongAnswers: ['CD', 'external hard disk', 'DVD'],
    methodSteps: ['Smartphones use memory cards (like SD cards or microSD cards) for additional storage. CDs, DVDs, and external hard disks are too large to fit in smartphones.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'comp_2025_mar_07',
    topic: 'Web Browser',
    category: 'Internet and Web',
    difficulty: 'Easy',
    questionTemplate: 'To access the internet, you need to have a',
    correctAnswerFormula: 'web browser',
    wrongAnswers: ['printer', 'DVD', 'plotter'],
    methodSteps: ['A web browser (like Chrome, Firefox, or Safari) is software that allows you to access and view websites on the internet.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'comp_2025_mar_08',
    topic: 'Email',
    category: 'Internet and Web',
    difficulty: 'Medium',
    questionTemplate: 'An e-mail needs to contain',
    correctAnswerFormula: 'subject title',
    wrongAnswers: ['pictures', 'videos', 'emoticons'],
    methodSteps: ['While emails can include pictures, videos, and emoticons, the most important required element is a subject title that describes what the email is about.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'comp_2025_mar_09',
    topic: 'Folder Naming',
    category: 'File Management',
    difficulty: 'Medium',
    questionTemplate: 'Choose the correct folder name?',
    correctAnswerFormula: 'My Photo',
    wrongAnswers: ['Holiday?', '<My School>', '#My Country#'],
    methodSteps: ['Folder names cannot contain special characters like ?, <, >, or #. \'My Photo\' is a valid folder name that follows naming rules.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'comp_2025_mar_10',
    topic: 'Web Browser Examples',
    category: 'Internet and Web',
    difficulty: 'Easy',
    questionTemplate: 'Which of the following is an example of a web browser?',
    correctAnswerFormula: 'internet explorer',
    wrongAnswers: ['file explorer', 'memory stick', 'dot matrix'],
    methodSteps: ['Internet Explorer is a web browser. File Explorer is for managing files on your computer, while memory stick and dot matrix are hardware devices.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'comp_2025_mar_11',
    topic: 'Privacy',
    category: 'Internet Safety',
    difficulty: 'Easy',
    questionTemplate: 'Which of the following information you should not share with a stranger?',
    correctAnswerFormula: 'your home address',
    wrongAnswers: ['your favourite food', 'your favourite subject', 'your favourite colour'],
    methodSteps: ['Personal information like your home address should never be shared with strangers online as it could compromise your safety. General preferences like favorite food or color are less risky.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'comp_2025_mar_12',
    topic: 'File Management',
    category: 'File Management',
    difficulty: 'Easy',
    questionTemplate: 'If you don\'t want a file any longer, you can',
    correctAnswerFormula: 'delete the file',
    wrongAnswers: ['edit the file', 'copy the file', 'paste the file'],
    methodSteps: ['Deleting a file removes it from your computer when you no longer need it. Editing, copying, and pasting are for modifying or duplicating files.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'comp_2025_mar_13',
    topic: 'CD vs DVD',
    category: 'Storage Devices',
    difficulty: 'Medium',
    questionTemplate: 'CD is the evolution of DVD.',
    correctAnswerFormula: 'False',
    wrongAnswers: ['True'],
    methodSteps: ['DVD (Digital Versatile Disc) is actually the evolution of CD (Compact Disc). DVDs came after CDs and have more storage capacity.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'comp_2025_mar_14',
    topic: 'Thermal Printer',
    category: 'Printers',
    difficulty: 'Medium',
    questionTemplate: 'Architectural plans can be printed using a thermal printer.',
    correctAnswerFormula: 'False',
    wrongAnswers: ['True'],
    methodSteps: ['Architectural plans are large format documents that require a plotter to print, not a thermal printer. Thermal printers are typically used for receipts.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'comp_2025_mar_15',
    topic: 'Subfolder',
    category: 'File Management',
    difficulty: 'Easy',
    questionTemplate: 'A sub folder is a folder inside a folder.',
    correctAnswerFormula: 'True',
    wrongAnswers: ['False'],
    methodSteps: ['A subfolder (or subdirectory) is a folder that exists inside another folder, helping to organize files in a hierarchical structure.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'comp_2025_mar_16',
    topic: 'File Transfer',
    category: 'File Management',
    difficulty: 'Medium',
    questionTemplate: 'A file in your computer can be transferred to your mobile phone.',
    correctAnswerFormula: 'True',
    wrongAnswers: ['False'],
    methodSteps: ['Files can be transferred between computers and mobile phones using various methods like USB cables, Bluetooth, cloud storage, or email.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'comp_2025_mar_17',
    topic: 'Microsoft Word',
    category: 'Software Applications',
    difficulty: 'Easy',
    questionTemplate: 'Microsoft Word is a word processor.',
    correctAnswerFormula: 'True',
    wrongAnswers: ['False'],
    methodSteps: ['Microsoft Word is a word processing application used for creating, editing, and formatting text documents.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'comp_2025_mar_18',
    topic: 'File Extensions',
    category: 'File Management',
    difficulty: 'Medium',
    questionTemplate: 'Every file does not have a file extension.',
    correctAnswerFormula: 'False',
    wrongAnswers: ['True'],
    methodSteps: ['Every file has a file extension (like .docx, .jpg, .mp3) that indicates the file type and which program should open it.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'comp_2025_mar_19',
    topic: 'Virus Theft',
    category: 'Internet Safety',
    difficulty: 'Easy',
    questionTemplate: 'A computer virus cannot steal your information.',
    correctAnswerFormula: 'False',
    wrongAnswers: ['True'],
    methodSteps: ['Computer viruses can steal personal information, passwords, and sensitive data from your computer. This is why cybersecurity is important.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'comp_2025_mar_20',
    topic: 'Zoom',
    category: 'Software Applications',
    difficulty: 'Easy',
    questionTemplate: 'You can zoom in and zoom out your document on the screen.',
    correctAnswerFormula: 'True',
    wrongAnswers: ['False'],
    methodSteps: ['Most applications allow you to zoom in (make content larger) or zoom out (make content smaller) to view documents more comfortably on screen.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'comp_2025_mar_21',
    topic: 'Emoticons',
    category: 'Internet Safety',
    difficulty: 'Easy',
    questionTemplate: 'You can use emoticons to show your feelings in a chat room.',
    correctAnswerFormula: 'True',
    wrongAnswers: ['False'],
    methodSteps: ['Emoticons (like :) or :() are symbols used in chat rooms and messages to express emotions and feelings in text-based communication.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'comp_2025_mar_22',
    topic: 'Anti-virus Protection',
    category: 'Internet Safety',
    difficulty: 'Easy',
    questionTemplate: 'An anti-virus program is one of the most powerful weapons to protect your computer.',
    correctAnswerFormula: 'True',
    wrongAnswers: ['False'],
    methodSteps: ['Anti-virus software is essential for protecting your computer from viruses, malware, and other security threats by detecting and removing harmful programs.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'comp_2025_mar_23',
    topic: 'File Explorer',
    category: 'Internet and Web',
    difficulty: 'Medium',
    questionTemplate: 'File explorer is an example of a web browser.',
    correctAnswerFormula: 'False',
    wrongAnswers: ['True'],
    methodSteps: ['File Explorer is a file management tool for browsing files on your computer. Web browsers (like Chrome or Firefox) are used to access the internet.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'comp_2025_mar_24',
    topic: 'Search Engines',
    category: 'Internet and Web',
    difficulty: 'Easy',
    questionTemplate: 'You cannot use search engines to find information.',
    correctAnswerFormula: 'False',
    wrongAnswers: ['True'],
    methodSteps: ['Search engines like Google, Bing, and Yahoo are specifically designed to help you find information on the internet by searching through billions of web pages.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'comp_2025_mar_25',
    topic: 'Google',
    category: 'Internet and Web',
    difficulty: 'Easy',
    questionTemplate: '___ is the most common search engine.',
    correctAnswerFormula: 'Google',
    wrongAnswers: ['Yahoo', 'Bing', 'Wikipedia'],
    methodSteps: ['Google is the world\'s most popular and widely used search engine, processing billions of searches every day.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'comp_2025_mar_26',
    topic: 'Safari',
    category: 'Internet and Web',
    difficulty: 'Easy',
    questionTemplate: 'You can use ___ web browser to search on the internet.',
    correctAnswerFormula: 'safari',
    wrongAnswers: ['calculator', 'notepad', 'paint'],
    methodSteps: ['Safari is a web browser developed by Apple that can be used to search and browse the internet, along with other browsers like Chrome and Firefox.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'comp_2025_mar_27',
    topic: 'Netiquette',
    category: 'Internet Safety',
    difficulty: 'Medium',
    questionTemplate: '___ is a set of rules for proper online behaviour.',
    correctAnswerFormula: 'Netiquette',
    wrongAnswers: ['Internet', 'Email', 'Password'],
    methodSteps: ['Netiquette (network etiquette) refers to the rules and guidelines for polite and appropriate behavior when communicating online.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'comp_2025_mar_28',
    topic: 'Thermal Printer',
    category: 'Printers',
    difficulty: 'Medium',
    questionTemplate: '___ uses a long narrow paper to print.',
    correctAnswerFormula: 'Thermal printer',
    wrongAnswers: ['Inkjet printer', 'Laser printer', '3D printer'],
    methodSteps: ['Thermal printers use long rolls of narrow thermal paper and are commonly used in cash registers, ATMs, and receipt printing.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'comp_2025_mar_29',
    topic: 'Wikipedia',
    category: 'Internet and Web',
    difficulty: 'Easy',
    questionTemplate: '___ is a virtual encyclopedia.',
    correctAnswerFormula: 'Wikipedia',
    wrongAnswers: ['Google', 'Facebook', 'YouTube'],
    methodSteps: ['Wikipedia is a free online encyclopedia that contains millions of articles written and edited collaboratively by volunteers around the world.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'comp_2025_mar_30',
    topic: 'URL',
    category: 'Internet and Web',
    difficulty: 'Medium',
    questionTemplate: 'A web address is also called ___.',
    correctAnswerFormula: 'URL',
    wrongAnswers: ['HTML', 'HTTP', 'WWW'],
    methodSteps: ['URL stands for Uniform Resource Locator, which is the address of a webpage on the internet (like www.example.com).'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  // ========== Formative Assessment - November 2024 ==========
  {
    id: 'comp_2024_nov_01',
    topic: 'Online Behavior',
    category: 'Internet Safety',
    difficulty: 'Easy',
    questionTemplate: 'You must be ___ online, just like in real life.',
    correctAnswerFormula: 'polite',
    wrongAnswers: ['rude', 'angry', 'careless'],
    methodSteps: ['It\'s important to be polite and respectful when communicating online, just as you would be in face-to-face interactions.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'comp_2024_nov_02',
    topic: 'Netiquette',
    category: 'Internet Safety',
    difficulty: 'Medium',
    questionTemplate: '___ are the list of rules for proper behaviour on the internet.',
    correctAnswerFormula: 'Netiquette',
    wrongAnswers: ['Websites', 'Browsers', 'Passwords'],
    methodSteps: ['Netiquette (internet etiquette) is a set of rules that guide proper and respectful behavior when using the internet and communicating online.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'comp_2024_nov_03',
    topic: 'Instant Messaging',
    category: 'Internet and Web',
    difficulty: 'Easy',
    questionTemplate: '___ is a communication method.',
    correctAnswerFormula: 'Instant messaging',
    wrongAnswers: ['Printing', 'Saving', 'Deleting'],
    methodSteps: ['Instant messaging allows people to send text messages to each other in real-time over the internet, like WhatsApp or text messaging.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'comp_2024_nov_04',
    topic: 'Chat Room Etiquette',
    category: 'Internet Safety',
    difficulty: 'Easy',
    questionTemplate: 'Never use ___ in chat rooms.',
    correctAnswerFormula: 'bad language',
    wrongAnswers: ['keyboards', 'computers', 'internet'],
    methodSteps: ['Using bad language or inappropriate words in chat rooms is disrespectful and goes against proper online behavior (netiquette).'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'comp_2024_nov_05',
    topic: 'Email Subject',
    category: 'Internet and Web',
    difficulty: 'Easy',
    questionTemplate: 'Always use a ___ for emails.',
    correctAnswerFormula: 'subject title',
    wrongAnswers: ['password only', 'picture', 'video'],
    methodSteps: ['A subject title tells the recipient what the email is about, making it easier to organize and understand the purpose of the message.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'comp_2024_nov_06',
    topic: 'Calculator Operations',
    category: 'Software Applications',
    difficulty: 'Medium',
    questionTemplate: 'Match: 25 add 35',
    correctAnswerFormula: '25 + 35 =',
    wrongAnswers: ['25 - 35 =', '25 * 35 =', '25 / 35 ='],
    methodSteps: ['In calculator programs, the plus symbol (+) is used to represent addition. So \'25 add 35\' is written as \'25 + 35 =\'.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'comp_2024_nov_07',
    topic: 'Calculator Division',
    category: 'Software Applications',
    difficulty: 'Medium',
    questionTemplate: 'Match: 24 divided by 8',
    correctAnswerFormula: '24 / 8 =',
    wrongAnswers: ['24 + 8 =', '24 - 8 =', '24 * 8 ='],
    methodSteps: ['In calculator programs, the forward slash (/) is used to represent division. So \'24 divided by 8\' is written as \'24 / 8 =\'.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'comp_2024_nov_08',
    topic: 'Calculator Subtraction',
    category: 'Software Applications',
    difficulty: 'Medium',
    questionTemplate: 'Match: 78 subtract 12',
    correctAnswerFormula: '78 − 12 =',
    wrongAnswers: ['78 + 12 =', '78 * 12 =', '78 / 12 ='],
    methodSteps: ['In calculator programs, the minus symbol (−) is used to represent subtraction. So \'78 subtract 12\' is written as \'78 − 12 =\'.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'comp_2024_nov_09',
    topic: 'Calculator Multiplication',
    category: 'Software Applications',
    difficulty: 'Medium',
    questionTemplate: 'Match: 5 multiply by 4',
    correctAnswerFormula: '5 * 4 =',
    wrongAnswers: ['5 + 4 =', '5 - 4 =', '5 / 4 ='],
    methodSteps: ['In calculator programs, the asterisk (*) is used to represent multiplication. So \'5 multiply by 4\' is written as \'5 * 4 =\'.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  // ========== Formative Assessment - September 2024 ==========
  {
    id: 'comp_2024_sep_01',
    topic: 'Hard Disk',
    category: 'Storage Devices',
    difficulty: 'Easy',
    questionTemplate: 'The biggest storage device is ___.',
    correctAnswerFormula: 'Hard Disk Drive',
    wrongAnswers: ['CD', 'USB Flash Drive', 'Memory Card'],
    methodSteps: ['Hard Disk Drives (HDDs) have the largest storage capacity among common storage devices, capable of storing terabytes of data.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'comp_2024_sep_02',
    topic: 'USB Flash Drive',
    category: 'Storage Devices',
    difficulty: 'Medium',
    questionTemplate: 'The storage device that can store or transfer data quickly is ___.',
    correctAnswerFormula: 'USB Flash Drive',
    wrongAnswers: ['CD', 'DVD', 'Floppy Disk'],
    methodSteps: ['USB Flash Drives (also called memory sticks) can quickly transfer data between computers using USB ports, making them very convenient.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'comp_2024_sep_03',
    topic: 'Compact Disk',
    category: 'Storage Devices',
    difficulty: 'Easy',
    questionTemplate: 'CD is known as ___.',
    correctAnswerFormula: 'Compact Disk',
    wrongAnswers: ['Computer Disk', 'Central Disk', 'Common Disk'],
    methodSteps: ['CD stands for Compact Disc. It\'s a flat, circular disc used to store digital data, music, or computer files.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'comp_2024_sep_04',
    topic: 'DVD Evolution',
    category: 'Storage Devices',
    difficulty: 'Medium',
    questionTemplate: 'DVD is the evolution of ___.',
    correctAnswerFormula: 'CD',
    wrongAnswers: ['USB', 'Hard Disk', 'Floppy Disk'],
    methodSteps: ['DVD (Digital Versatile Disc) evolved from CD technology with much greater storage capacity, allowing it to store movies and large files.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'comp_2024_sep_05',
    topic: 'Memory Card',
    category: 'Storage Devices',
    difficulty: 'Easy',
    questionTemplate: 'The storage device that can be used in Digital Cameras is ___.',
    correctAnswerFormula: 'Memory card',
    wrongAnswers: ['CD', 'DVD', 'Hard Disk Drive'],
    methodSteps: ['Memory cards (like SD cards) are small, portable storage devices used in digital cameras, smartphones, and other portable devices to store photos and data.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  // ========== Formative Assessment - October 2024 ==========
  {
    id: 'comp_2024_oct_01',
    topic: 'File Naming',
    category: 'File Management',
    difficulty: 'Easy',
    questionTemplate: 'A suitable file name for your family photo is ___.',
    correctAnswerFormula: 'My family',
    wrongAnswers: ['Family?!', '<Family>', 'Family***'],
    methodSteps: ['File names should be descriptive and not contain special characters like ?, !, <, >, or *. \'My family\' is a clear and valid file name.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'comp_2024_oct_02',
    topic: 'Folder Icon',
    category: 'File Management',
    difficulty: 'Easy',
    questionTemplate: 'What does the 📁 icon represent on your computer?',
    correctAnswerFormula: 'folder',
    wrongAnswers: ['file', 'printer', 'computer'],
    methodSteps: ['The folder icon represents a container for organizing and storing files on your computer, similar to a physical folder that holds papers.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'comp_2024_oct_03',
    topic: 'Delete File',
    category: 'File Management',
    difficulty: 'Easy',
    questionTemplate: 'If you don\'t need a file any longer you can ___ it.',
    correctAnswerFormula: 'delete',
    wrongAnswers: ['open', 'copy', 'rename'],
    methodSteps: ['Deleting a file removes it from your computer when you no longer need it, freeing up storage space.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'comp_2024_oct_04',
    topic: 'File Extension',
    category: 'File Management',
    difficulty: 'Medium',
    questionTemplate: 'The extension of the file \'My country.docx\' is ___.',
    correctAnswerFormula: '.docx',
    wrongAnswers: ['.doc', '.txt', '.pdf'],
    methodSteps: ['File extensions appear after the dot in a filename and indicate the file type. .docx is a Microsoft Word document format.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'comp_2024_oct_05',
    topic: 'Subfolder',
    category: 'File Management',
    difficulty: 'Easy',
    questionTemplate: 'A sub folder is a ___ inside a ___.',
    correctAnswerFormula: 'folder inside a folder',
    wrongAnswers: ['file inside a file', 'folder inside a file', 'computer inside a computer'],
    methodSteps: ['A subfolder is a folder contained within another folder, helping to organize files in a hierarchical structure.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'comp_2024_oct_06',
    topic: 'Laser Printer',
    category: 'Printers',
    difficulty: 'Medium',
    questionTemplate: 'The printer that uses laser rays to print on paper is ___.',
    correctAnswerFormula: 'laser printer',
    wrongAnswers: ['inkjet printer', 'dot matrix', 'thermal printer'],
    methodSteps: ['Laser printers use laser beams to create an image on a drum, which then transfers toner (powdered ink) onto paper to produce high-quality prints.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'comp_2024_oct_07',
    topic: 'Dot Matrix',
    category: 'Printers',
    difficulty: 'Easy',
    questionTemplate: 'The oldest type of printer is ___.',
    correctAnswerFormula: 'dot matrix',
    wrongAnswers: ['laser printer', 'inkjet printer', '3D printer'],
    methodSteps: ['Dot matrix printers are the oldest type of printer still in use. They print by striking pins against an ink ribbon to create characters made of dots.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'comp_2024_oct_08',
    topic: 'Plotter',
    category: 'Printers',
    difficulty: 'Medium',
    questionTemplate: '___ is used for printing architectural plans and advertising banners.',
    correctAnswerFormula: 'Plotter',
    wrongAnswers: ['Inkjet printer', 'Thermal printer', 'Dot matrix'],
    methodSteps: ['Plotters are large-format printers designed to print wide graphics like architectural plans, engineering drawings, and advertising banners.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'comp_2024_oct_09',
    topic: 'Thermal Printer',
    category: 'Printers',
    difficulty: 'Easy',
    questionTemplate: '___ is used in shops, banks and restaurants.',
    correctAnswerFormula: 'Thermal printer',
    wrongAnswers: ['Laser printer', 'Plotter', 'Inkjet printer'],
    methodSteps: ['Thermal printers are commonly used to print receipts in shops, banks, and restaurants because they are fast and quiet.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'comp_2024_oct_10',
    topic: 'Inkjet Printer Colors',
    category: 'Printers',
    difficulty: 'Hard',
    questionTemplate: '___ uses cyan, yellow, magenta and black ink colours.',
    correctAnswerFormula: 'Inkjet printer',
    wrongAnswers: ['Laser printer', 'Dot matrix', 'Thermal printer'],
    methodSteps: ['Inkjet printers spray tiny droplets of liquid ink onto paper. They use four colors (CMYK: Cyan, Magenta, Yellow, and Black) to create full-color images.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 30,
  },
  // ========== Second Semester Examination - July 2025 ==========
  {
    id: 'comp_2025_jul_02',
    topic: 'Folder Naming',
    category: 'File Management',
    difficulty: 'Easy',
    questionTemplate: 'What is a suitable name for a birthday folder?',
    correctAnswerFormula: 'Birthday / My Birthday / Birthday Party',
    wrongAnswers: ['Birthday?!', '<Birthday>', 'Birth*day'],
    methodSteps: ['Folder names should be descriptive and not contain special characters. Simple names like \'Birthday\' or \'My Birthday\' are appropriate.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'comp_2025_jul_03a',
    topic: 'File Types',
    category: 'File Management',
    difficulty: 'Easy',
    questionTemplate: 'What type of file is used to store music and sound?',
    correctAnswerFormula: 'Audio file',
    wrongAnswers: ['Image file', 'Video file', 'Document file'],
    methodSteps: ['Audio files store sound and music. Common audio file types include .mp3, .wav, and .aac.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'comp_2025_jul_03b',
    topic: 'File Types',
    category: 'File Management',
    difficulty: 'Easy',
    questionTemplate: 'What type of file is used to store photos and pictures?',
    correctAnswerFormula: 'Image file',
    wrongAnswers: ['Audio file', 'Video file', 'Text file'],
    methodSteps: ['Image files store photos and pictures. Common image file types include .jpg, .png, and .gif.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'comp_2025_jul_03c',
    topic: 'File Types',
    category: 'File Management',
    difficulty: 'Easy',
    questionTemplate: 'What type of file is used to store movies and recordings?',
    correctAnswerFormula: 'Video file',
    wrongAnswers: ['Audio file', 'Image file', 'Presentation file'],
    methodSteps: ['Video files store movies and video recordings. Common video file types include .mp4, .avi, and .mov.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'comp_2025_jul_04',
    topic: 'File Name',
    category: 'File Management',
    difficulty: 'Medium',
    questionTemplate: 'What is the file name of \'My School.docx\'?',
    correctAnswerFormula: 'My School',
    wrongAnswers: ['.docx', 'My School.docx', 'School'],
    methodSteps: ['The file name is the part before the extension. In \'My School.docx\', \'My School\' is the file name and \'.docx\' is the extension.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'comp_2025_jul_05',
    topic: 'File Extension',
    category: 'File Management',
    difficulty: 'Medium',
    questionTemplate: 'What is the file extension of \'My School.docx\'?',
    correctAnswerFormula: '.docx',
    wrongAnswers: ['.doc', '.txt', '.pdf'],
    methodSteps: ['The file extension is the part after the dot that indicates the file type. .docx is the extension for Microsoft Word documents.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'comp_2025_jul_06',
    topic: 'Chat Room',
    category: 'Internet and Web',
    difficulty: 'Easy',
    questionTemplate: '___ is a place where people can chat online in real-time.',
    correctAnswerFormula: 'chat room',
    wrongAnswers: ['classroom', 'living room', 'storage room'],
    methodSteps: ['A chat room is a virtual space on the internet where multiple people can communicate with each other in real-time through text messages.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'comp_2025_jul_07',
    topic: 'Laser Printer',
    category: 'Printers',
    difficulty: 'Medium',
    questionTemplate: '___ uses laser rays to print high-quality documents.',
    correctAnswerFormula: 'Laser printer',
    wrongAnswers: ['Inkjet printer', 'Thermal printer', 'Dot matrix printer'],
    methodSteps: ['Laser printers use laser technology to produce high-quality, fast prints, commonly used in offices for text documents.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'comp_2025_jul_08',
    topic: 'Computer Viruses',
    category: 'Internet Safety',
    difficulty: 'Easy',
    questionTemplate: 'Computer ___ are harmful programs that can damage your computer.',
    correctAnswerFormula: 'viruses',
    wrongAnswers: ['games', 'folders', 'files'],
    methodSteps: ['Computer viruses are malicious programs that can infect your computer, steal data, or cause damage to your files and system.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'comp_2025_jul_09',
    topic: 'Dot Matrix Printer',
    category: 'Printers',
    difficulty: 'Easy',
    questionTemplate: '___ is the oldest type of printer that uses pins to print.',
    correctAnswerFormula: 'Dot matrix',
    wrongAnswers: ['Laser printer', 'Inkjet printer', '3D printer'],
    methodSteps: ['Dot matrix printers are the oldest printer type, using a print head with pins that strike an ink ribbon to create characters.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'comp_2025_jul_10',
    topic: 'Webcams',
    category: 'Input Devices',
    difficulty: 'Medium',
    questionTemplate: '___ are cameras connected to computers for video calls.',
    correctAnswerFormula: 'webcams',
    wrongAnswers: ['digital cameras', 'video recorders', 'smartphones'],
    methodSteps: ['Webcams are video cameras that connect to computers or are built into laptops, used for video calls, online meetings, and recording videos.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'comp_2025_jul_11',
    topic: 'Trackball',
    category: 'Input Devices',
    difficulty: 'Medium',
    questionTemplate: '___ is a pointing device with a ball on top.',
    correctAnswerFormula: 'Trackball',
    wrongAnswers: ['Mouse', 'Keyboard', 'Joystick'],
    methodSteps: ['A trackball is an input device with a ball that you roll with your fingers to move the cursor on screen, similar to an upside-down mouse.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'comp_2025_jul_12',
    topic: 'Search Engine',
    category: 'Internet and Web',
    difficulty: 'Easy',
    questionTemplate: 'A ___ helps you find information on the internet.',
    correctAnswerFormula: 'search engine',
    wrongAnswers: ['web browser', 'website', 'computer'],
    methodSteps: ['Search engines like Google, Bing, and Yahoo help you find information by searching through billions of web pages based on your keywords.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'comp_2025_jul_13',
    topic: 'Programming Languages',
    category: 'Software Applications',
    difficulty: 'Medium',
    questionTemplate: 'Computers can understand many programming ___.',
    correctAnswerFormula: 'languages',
    wrongAnswers: ['keyboards', 'mice', 'printers'],
    methodSteps: ['Programming languages (like Python, Java, or JavaScript) are special languages used to give instructions to computers and create software.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'comp_2025_jul_14',
    topic: 'Trackball Device',
    category: 'Input Devices',
    difficulty: 'Medium',
    questionTemplate: 'Which device has a ball on top that you rotate with your fingers to control the cursor?',
    correctAnswerFormula: 'Trackball',
    wrongAnswers: ['Mouse', 'Keyboard', 'Joystick'],
    methodSteps: ['A trackball is a pointing device that has a ball on top which you rotate with your fingers to control the cursor. It works like an upside-down mouse.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'comp_2025_jul_15',
    topic: 'Memory Card Device',
    category: 'Storage Devices',
    difficulty: 'Easy',
    questionTemplate: 'Which small storage device is commonly used in digital cameras and smartphones?',
    correctAnswerFormula: 'Memory card',
    wrongAnswers: ['USB drive', 'CD', 'Hard disk'],
    methodSteps: ['Memory cards are small portable storage devices used in cameras, phones, and other devices to store data.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'comp_2025_jul_16',
    topic: 'Digitizer',
    category: 'Input Devices',
    difficulty: 'Hard',
    questionTemplate: 'Which device allows artists to draw on a computer using a special pen?',
    correctAnswerFormula: 'Digitizer/Graphic Tablet',
    wrongAnswers: ['Keyboard', 'Mouse', 'Scanner'],
    methodSteps: ['A digitizer or graphic tablet is an input device that allows artists and designers to draw directly on a surface using a special pen.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 30,
  },
  {
    id: 'comp_2025_jul_17',
    topic: 'Dot Matrix Device',
    category: 'Printers',
    difficulty: 'Medium',
    questionTemplate: 'Which printer uses pins striking an ink ribbon to create characters?',
    correctAnswerFormula: 'Dot Matrix Printer',
    wrongAnswers: ['Laser Printer', 'Inkjet Printer', 'Thermal Printer'],
    methodSteps: ['A dot matrix printer is the oldest type of printer that uses pins striking an ink ribbon to create characters on paper.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'comp_2025_jul_18',
    topic: 'Joystick Device',
    category: 'Input Devices',
    difficulty: 'Easy',
    questionTemplate: 'Which input device has a stick that can be moved in different directions and is commonly used for gaming?',
    correctAnswerFormula: 'Joystick',
    wrongAnswers: ['Mouse', 'Keyboard', 'Trackball'],
    methodSteps: ['A joystick is an input device with a stick that can be moved in different directions, commonly used for gaming and controlling movement in games.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'comp_2025_jul_19',
    topic: 'Portable Devices',
    category: 'Hardware',
    difficulty: 'Medium',
    questionTemplate: 'Name two portable computing devices.',
    correctAnswerFormula: 'smartphone and tablet computer',
    wrongAnswers: ['desktop and monitor', 'printer and scanner', 'keyboard and mouse'],
    methodSteps: ['Smartphones and tablet computers are portable computing devices you can carry and use anywhere, unlike desktop computers.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'comp_2025_jul_20',
    topic: 'Video Camera',
    category: 'Input Devices',
    difficulty: 'Medium',
    questionTemplate: 'What device can capture moving images?',
    correctAnswerFormula: 'Video camera',
    wrongAnswers: ['Regular camera', 'Microphone', 'Scanner'],
    methodSteps: ['A video camera records moving images (videos), unlike a regular camera which captures still photographs.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'comp_2025_jul_21',
    topic: 'VR Devices',
    category: 'Input Devices',
    difficulty: 'Hard',
    questionTemplate: 'Name two Virtual Reality (VR) devices.',
    correctAnswerFormula: 'VR Glove and VR Headset',
    wrongAnswers: ['Keyboard and Mouse', 'Camera and Microphone', 'Printer and Scanner'],
    methodSteps: ['VR (Virtual Reality) devices like VR gloves and VR headsets allow users to interact with and experience computer-generated 3D environments.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 30,
  },
  {
    id: 'comp_2025_jul_22',
    topic: 'Portable Computers',
    category: 'Hardware',
    difficulty: 'Easy',
    questionTemplate: 'Name two types of portable computers.',
    correctAnswerFormula: 'Laptop and Notebook computer',
    wrongAnswers: ['Desktop and Tower', 'Smartphone and Watch', 'Tablet and Calculator'],
    methodSteps: ['Laptops and notebook computers are portable PCs that can be carried and used in different locations, running on battery power.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'comp_2025_jul_23',
    topic: 'Word Processing',
    category: 'Software Applications',
    difficulty: 'Easy',
    questionTemplate: 'Name software for creating text documents.',
    correctAnswerFormula: 'Microsoft Word',
    wrongAnswers: ['Microsoft Excel', 'Microsoft PowerPoint', 'Adobe Photoshop'],
    methodSteps: ['Microsoft Word is word processing software used to create, edit, and format text documents like letters, reports, and essays.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'comp_2025_jul_24',
    topic: 'Presentation Software',
    category: 'Software Applications',
    difficulty: 'Easy',
    questionTemplate: 'Name software for creating presentations.',
    correctAnswerFormula: 'Microsoft PowerPoint',
    wrongAnswers: ['Microsoft Word', 'Microsoft Excel', 'Paint'],
    methodSteps: ['Microsoft PowerPoint is presentation software used to create slideshows with text, images, and animations for presentations.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
];

export function getComputingTemplates(): QuestionTemplate[] {
  return computingTemplates;
}
