import { QuestionTemplate } from '@/types/question-template';

/**
 * English Question Templates - Grade 3
 * From Lyceum GRADE 3 English papers with mark schemes (Formative, Monthly, Semester)
 * Categories: Listening Comprehension, Grammar, Vocabulary, Comprehension, Wh-questions, Prepositions
 */

export const ENGLISH_CATEGORIES = [
  'Listening Comprehension',
  'Grammar - Verbs',
  'Grammar - Adjectives',
  'Grammar - Pronouns',
  'Grammar - Tenses',
  'Grammar - Modals',
  'Vocabulary - Opposites',
  'Wh-questions',
  'Prepositions',
  'Comprehension',
] as const;

export const englishTemplates: QuestionTemplate[] = [
  // ========== FROM EXAM PAPERS (with mark schemes) ==========
  // October 2022 - Listening (Monkeys)
  {
    id: 'eng-oct22-listening-monkeys-where',
    topic: 'Listening',
    category: 'Listening Comprehension',
    difficulty: 'Easy',
    questionTemplate: 'Where do monkeys live?',
    correctAnswerFormula: 'trees',
    wrongAnswers: ['kennel', 'den', 'stable'],
    methodSteps: ['Monkeys are animals that live in forests.', 'They live in trees.', 'A kennel is for dogs, a den for lions, a stable for horses.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },
  {
    id: 'eng-oct22-listening-monkeys-eat',
    topic: 'Listening',
    category: 'Listening Comprehension',
    difficulty: 'Easy',
    questionTemplate: 'What do monkeys like to eat?',
    correctAnswerFormula: 'banana',
    wrongAnswers: ['fish', 'orange', 'insects'],
    methodSteps: ['Monkeys love fruits.', 'Banana is a favourite food of monkeys.', 'Fish and insects are not typical monkey food.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },
  {
    id: 'eng-oct22-listening-monkeys-group',
    topic: 'Listening',
    category: 'Listening Comprehension',
    difficulty: 'Easy',
    questionTemplate: 'What is a group of monkeys called?',
    correctAnswerFormula: 'troop',
    wrongAnswers: ['bunch', 'pride', 'school'],
    methodSteps: ['A group of monkeys is called a troop.', 'Bunch is for bananas, pride for lions, school for fish.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },
  {
    id: 'eng-oct22-listening-monkeys-long',
    topic: 'Listening',
    category: 'Listening Comprehension',
    difficulty: 'Easy',
    questionTemplate: 'Monkeys have a long ________?',
    correctAnswerFormula: 'tail',
    wrongAnswers: ['nose', 'arm', 'ear'],
    methodSteps: ['Monkeys have long tails that help them balance.', 'They use their tails to swing from branch to branch.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },
  // January 2022 - Listening (Jade by the water) - from paper; answers from context
  {
    id: 'eng-jan22-listening-jade-doing',
    topic: 'Listening',
    category: 'Listening Comprehension',
    difficulty: 'Easy',
    questionTemplate: 'What is Jade doing?',
    correctAnswerFormula: 'She is walking by the water.',
    wrongAnswers: ['She is reading.', 'She is sleeping.', 'She is drawing.'],
    methodSteps: ['Listen to the passage about Jade.', 'She is near the water.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'eng-jan22-listening-heartbeat',
    topic: 'Listening',
    category: 'Listening Comprehension',
    difficulty: 'Easy',
    questionTemplate: "Jade's heartbeat quickens as she sees _____.",
    correctAnswerFormula: 'dolphin fins cutting the surface of the water.',
    wrongAnswers: ['a big ship', 'A drowning child.', 'a whale'],
    methodSteps: ['Her heartbeat quickens when she sees something exciting.', 'Dolphin fins are the exciting sight in the story.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  // January 2025 Formative - Action verbs (from mark scheme)
  {
    id: 'eng-jan25-action-verb-throwing',
    topic: 'Verbs',
    category: 'Grammar - Verbs',
    difficulty: 'Easy',
    questionTemplate: 'What is the action verb in: "Tim is throwing the ball."?',
    correctAnswerFormula: 'throwing',
    wrongAnswers: ['Tim', 'is', 'ball'],
    methodSteps: ['An action verb shows what someone does.', 'Throwing is the action in this sentence.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },
  {
    id: 'eng-jan25-action-verb-slept',
    topic: 'Verbs',
    category: 'Grammar - Verbs',
    difficulty: 'Easy',
    questionTemplate: 'What is the action verb in: "She slept all night."?',
    correctAnswerFormula: 'slept',
    wrongAnswers: ['She', 'all', 'night'],
    methodSteps: ['Slept is the action (past tense of sleep).', 'She did the action of sleeping.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },
  {
    id: 'eng-jan25-action-verb-barked',
    topic: 'Verbs',
    category: 'Grammar - Verbs',
    difficulty: 'Easy',
    questionTemplate: 'What is the action verb in: "My dog barked."?',
    correctAnswerFormula: 'barked',
    wrongAnswers: ['My', 'dog', 'barked is not a verb'],
    methodSteps: ['Barked is what the dog did.', 'It is the action verb.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },
  // Singular/Plural pronouns - Jan 2025 MS
  {
    id: 'eng-jan25-pronoun-he',
    topic: 'Pronouns',
    category: 'Grammar - Pronouns',
    difficulty: 'Easy',
    questionTemplate: '"He is my best friend." Is the pronoun singular or plural?',
    correctAnswerFormula: 'Singular',
    wrongAnswers: ['Plural', 'Neither', 'Both'],
    methodSteps: ['He refers to one person.', 'Pronouns for one person are singular.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },
  {
    id: 'eng-jan25-pronoun-they',
    topic: 'Pronouns',
    category: 'Grammar - Pronouns',
    difficulty: 'Easy',
    questionTemplate: '"They are ready to go to school." Is the pronoun singular or plural?',
    correctAnswerFormula: 'Plural',
    wrongAnswers: ['Singular', 'Neither', 'Both'],
    methodSteps: ['They refers to more than one person.', 'So it is plural.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },
  // January 2022 - Adjectives (comparative/superlative) from MS
  {
    id: 'eng-jan22-adj-fast',
    topic: 'Adjectives',
    category: 'Grammar - Adjectives',
    difficulty: 'Easy',
    questionTemplate: 'Tom is _____ than Dave. (fast)',
    correctAnswerFormula: 'faster',
    wrongAnswers: ['fast', 'fastest', 'more fast'],
    methodSteps: ['We compare two people: Tom and Dave.', 'Use comparative form: faster.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'eng-jan22-adj-noisiest',
    topic: 'Adjectives',
    category: 'Grammar - Adjectives',
    difficulty: 'Medium',
    questionTemplate: 'Barry is the _____ in the class. (noisy)',
    correctAnswerFormula: 'noisiest',
    wrongAnswers: ['noisy', 'noisier', 'most noisy'],
    methodSteps: ['We compare Barry with the whole class.', 'Use superlative: noisiest.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'eng-jan22-adj-coldest',
    topic: 'Adjectives',
    category: 'Grammar - Adjectives',
    difficulty: 'Medium',
    questionTemplate: 'The Arctic is the _____ place on Earth. (cold)',
    correctAnswerFormula: 'coldest',
    wrongAnswers: ['cold', 'colder', 'most cold'],
    methodSteps: ['We compare all places on Earth.', 'Superlative: coldest.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'eng-jan22-adj-smaller',
    topic: 'Adjectives',
    category: 'Grammar - Adjectives',
    difficulty: 'Easy',
    questionTemplate: 'A lime is _____ than an orange. (small)',
    correctAnswerFormula: 'smaller',
    wrongAnswers: ['small', 'smallest', 'more small'],
    methodSteps: ['We compare two fruits.', 'Comparative: smaller.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  // January 2022 - Simple Past Tense from MS
  {
    id: 'eng-jan22-past-threw',
    topic: 'Tenses',
    category: 'Grammar - Tenses',
    difficulty: 'Easy',
    questionTemplate: 'Fanny _____ (throw) the ball over the fence.',
    correctAnswerFormula: 'threw',
    wrongAnswers: ['throw', 'thrown', 'threwed'],
    methodSteps: ['Past tense of throw is threw.', 'It is an irregular verb.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'eng-jan22-past-wrote',
    topic: 'Tenses',
    category: 'Grammar - Tenses',
    difficulty: 'Easy',
    questionTemplate: 'Students _____ (write) their names on top of the page.',
    correctAnswerFormula: 'wrote',
    wrongAnswers: ['write', 'written', 'writed'],
    methodSteps: ['Past tense of write is wrote.', 'Irregular verb.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'eng-jan22-past-went',
    topic: 'Tenses',
    category: 'Grammar - Tenses',
    difficulty: 'Easy',
    questionTemplate: 'Last night, we _____ (go) for a movie.',
    correctAnswerFormula: 'went',
    wrongAnswers: ['go', 'gone', 'goed'],
    methodSteps: ['Past tense of go is went.', 'Irregular verb.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'eng-jan22-past-slept',
    topic: 'Tenses',
    category: 'Grammar - Tenses',
    difficulty: 'Easy',
    questionTemplate: 'My father _____ (sleep) for 8 hours at a stretch.',
    correctAnswerFormula: 'slept',
    wrongAnswers: ['sleep', 'slepped', 'sleeped'],
    methodSteps: ['Past tense of sleep is slept.', 'Irregular verb.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  // January 2022 - can/could from MS
  {
    id: 'eng-jan22-modal-couldnt',
    topic: 'Modals',
    category: 'Grammar - Modals',
    difficulty: 'Easy',
    questionTemplate: "I _____ go to the party last night because I was sick.",
    correctAnswerFormula: "couldn't",
    wrongAnswers: ["can't", 'could', 'can'],
    methodSteps: ['Past ability: use could/couldn\'t.', 'Negative past: couldn\'t.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'eng-jan22-modal-cant',
    topic: 'Modals',
    category: 'Grammar - Modals',
    difficulty: 'Easy',
    questionTemplate: "Excuse me, I _____ hear you now as the music is too loud.",
    correctAnswerFormula: "can't",
    wrongAnswers: ["couldn't", 'could', 'can'],
    methodSteps: ['Present: use can/can\'t.', 'Negative present ability: can\'t.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'eng-jan22-modal-could',
    topic: 'Modals',
    category: 'Grammar - Modals',
    difficulty: 'Easy',
    questionTemplate: 'He _____ sing nicely when he was in grade 4.',
    correctAnswerFormula: 'could',
    wrongAnswers: ['can', "can't", "couldn't"],
    methodSteps: ['Past ability: could.', 'When he was in grade 4 = past.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  // January 2022 - Opposites from MS (Match: Up-Down, Slow-Fast, etc.)
  {
    id: 'eng-jan22-opp-up',
    topic: 'Opposites',
    category: 'Vocabulary - Opposites',
    difficulty: 'Easy',
    questionTemplate: 'What is the opposite of "Up"?',
    correctAnswerFormula: 'Down',
    wrongAnswers: ['High', 'Above', 'Tall'],
    methodSteps: ['Up and down are opposite directions.', 'Down is the opposite of up.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },
  {
    id: 'eng-jan22-opp-slow',
    topic: 'Opposites',
    category: 'Vocabulary - Opposites',
    difficulty: 'Easy',
    questionTemplate: 'What is the opposite of "Slow"?',
    correctAnswerFormula: 'Fast',
    wrongAnswers: ['Quick', 'Quickly', 'Speed'],
    methodSteps: ['Slow and fast are opposite in speed.', 'Fast is the opposite of slow.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },
  {
    id: 'eng-jan22-opp-beautiful',
    topic: 'Opposites',
    category: 'Vocabulary - Opposites',
    difficulty: 'Easy',
    questionTemplate: 'What is the opposite of "Beautiful"?',
    correctAnswerFormula: 'Ugly',
    wrongAnswers: ['Bad', 'Plain', 'Worst'],
    methodSteps: ['Beautiful means very nice to look at.', 'Ugly means not nice to look at.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },
  {
    id: 'eng-jan22-opp-brave',
    topic: 'Opposites',
    category: 'Vocabulary - Opposites',
    difficulty: 'Easy',
    questionTemplate: 'What is the opposite of "Brave"?',
    correctAnswerFormula: 'Coward',
    wrongAnswers: ['Scared', 'Afraid', 'Fear'],
    methodSteps: ['Brave means not afraid.', 'Coward is a person who is not brave.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },
  {
    id: 'eng-jan22-opp-narrow',
    topic: 'Opposites',
    category: 'Vocabulary - Opposites',
    difficulty: 'Easy',
    questionTemplate: 'What is the opposite of "Narrow"?',
    correctAnswerFormula: 'Wide',
    wrongAnswers: ['Broad', 'Big', 'Large'],
    methodSteps: ['Narrow means not wide.', 'Wide is the opposite.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },
  {
    id: 'eng-jan22-opp-thin',
    topic: 'Opposites',
    category: 'Vocabulary - Opposites',
    difficulty: 'Easy',
    questionTemplate: 'What is the opposite of "Thin"?',
    correctAnswerFormula: 'Thick',
    wrongAnswers: ['Fat', 'Wide', 'Big'],
    methodSteps: ['Thin and thick describe width.', 'Thick is the opposite of thin.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },
  {
    id: 'eng-jan22-opp-wise',
    topic: 'Opposites',
    category: 'Vocabulary - Opposites',
    difficulty: 'Easy',
    questionTemplate: 'What is the opposite of "Wise"?',
    correctAnswerFormula: 'Foolish',
    wrongAnswers: ['Silly', 'Stupid', 'Dull'],
    methodSteps: ['Wise means smart and sensible.', 'Foolish means not wise.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },
  {
    id: 'eng-jan22-opp-old',
    topic: 'Opposites',
    category: 'Vocabulary - Opposites',
    difficulty: 'Easy',
    questionTemplate: 'What is the opposite of "Old"?',
    correctAnswerFormula: 'Young',
    wrongAnswers: ['New', 'Fresh', 'Small'],
    methodSteps: ['Old (for people) means not young.', 'Young is the opposite.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },
  {
    id: 'eng-jan22-opp-tall',
    topic: 'Opposites',
    category: 'Vocabulary - Opposites',
    difficulty: 'Easy',
    questionTemplate: 'What is the opposite of "Tall"?',
    correctAnswerFormula: 'Short',
    wrongAnswers: ['Small', 'Low', 'Little'],
    methodSteps: ['Tall and short describe height.', 'Short is the opposite of tall.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },
  {
    id: 'eng-jan22-opp-end',
    topic: 'Opposites',
    category: 'Vocabulary - Opposites',
    difficulty: 'Easy',
    questionTemplate: 'What is the opposite of "End"?',
    correctAnswerFormula: 'Begin',
    wrongAnswers: ['Start', 'First', 'Opening'],
    methodSteps: ['End means the last part.', 'Begin means to start.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },
  // October 2022 - Wh-questions from MS
  {
    id: 'eng-oct22-wh-who',
    topic: 'Wh-questions',
    category: 'Wh-questions',
    difficulty: 'Easy',
    questionTemplate: "_____ is she? She is my sister.",
    correctAnswerFormula: 'Who',
    wrongAnswers: ['Where', 'What', 'When'],
    methodSteps: ['We ask about a person with Who.', 'She is a person.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },
  {
    id: 'eng-oct22-wh-where',
    topic: 'Wh-questions',
    category: 'Wh-questions',
    difficulty: 'Easy',
    questionTemplate: "_____ are they? They are in the kitchen.",
    correctAnswerFormula: 'Where',
    wrongAnswers: ['Who', 'What', 'When'],
    methodSteps: ['We ask about place with Where.', 'In the kitchen is a place.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },
  {
    id: 'eng-oct22-wh-what',
    topic: 'Wh-questions',
    category: 'Wh-questions',
    difficulty: 'Easy',
    questionTemplate: "_____ is it? It is a cake.",
    correctAnswerFormula: 'What',
    wrongAnswers: ['Who', 'Where', 'When'],
    methodSteps: ['We ask about a thing with What.', 'A cake is a thing.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },
  {
    id: 'eng-oct22-wh-when',
    topic: 'Wh-questions',
    category: 'Wh-questions',
    difficulty: 'Easy',
    questionTemplate: "_____ is your Math class? It is on Monday.",
    correctAnswerFormula: 'When',
    wrongAnswers: ['Who', 'Where', 'What'],
    methodSteps: ['We ask about time with When.', 'On Monday is a time.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },
  {
    id: 'eng-oct22-wh-why',
    topic: 'Wh-questions',
    category: 'Wh-questions',
    difficulty: 'Easy',
    questionTemplate: "_____ are you sad? I am sad because I fell down.",
    correctAnswerFormula: 'Why',
    wrongAnswers: ['Who', 'Where', 'When'],
    methodSteps: ['We ask for reason with Why.', 'Because gives a reason.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },
  // October 2022 - Pronouns from MS
  {
    id: 'eng-oct22-pronoun-tony',
    topic: 'Pronouns',
    category: 'Grammar - Pronouns',
    difficulty: 'Easy',
    questionTemplate: '(Tony) _____ is happy.',
    correctAnswerFormula: 'He',
    wrongAnswers: ['She', 'It', 'They'],
    methodSteps: ['Tony is a boy\'s name.', 'We use He for a boy.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },
  {
    id: 'eng-oct22-pronoun-lisa',
    topic: 'Pronouns',
    category: 'Grammar - Pronouns',
    difficulty: 'Easy',
    questionTemplate: '(Lisa) _____ is angry.',
    correctAnswerFormula: 'She',
    wrongAnswers: ['He', 'It', 'They'],
    methodSteps: ['Lisa is a girl\'s name.', 'We use She for a girl.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },
  {
    id: 'eng-oct22-pronoun-bike',
    topic: 'Pronouns',
    category: 'Grammar - Pronouns',
    difficulty: 'Easy',
    questionTemplate: '(A bike) _____ is red.',
    correctAnswerFormula: 'It',
    wrongAnswers: ['He', 'She', 'They'],
    methodSteps: ['A bike is a thing, not a person.', 'We use It for things.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },
  {
    id: 'eng-oct22-pronoun-books',
    topic: 'Pronouns',
    category: 'Grammar - Pronouns',
    difficulty: 'Easy',
    questionTemplate: '(Two books) _____ are in the box.',
    correctAnswerFormula: 'They',
    wrongAnswers: ['He', 'She', 'It'],
    methodSteps: ['Two books = more than one.', 'We use They for plural.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },
  {
    id: 'eng-oct22-pronoun-we',
    topic: 'Pronouns',
    category: 'Grammar - Pronouns',
    difficulty: 'Easy',
    questionTemplate: '(Tom and I) _____ are good friends.',
    correctAnswerFormula: 'We',
    wrongAnswers: ['They', 'He', 'I'],
    methodSteps: ['Tom and I = we (including me).', 'We is the correct pronoun.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },
  // October 2022 - Prepositions from MS
  {
    id: 'eng-oct22-prep-under',
    topic: 'Prepositions',
    category: 'Prepositions',
    difficulty: 'Easy',
    questionTemplate: 'The cat is _____ the box. (below, inside from above)',
    correctAnswerFormula: 'under',
    wrongAnswers: ['on', 'in', 'behind'],
    methodSteps: ['Under means below something.', 'The cat is below the box.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'eng-oct22-prep-between',
    topic: 'Prepositions',
    category: 'Prepositions',
    difficulty: 'Easy',
    questionTemplate: 'The bird is _____ the boxes. (in the middle of two)',
    correctAnswerFormula: 'between',
    wrongAnswers: ['under', 'in', 'on'],
    methodSteps: ['Between means in the middle of two things.', 'The bird is in the middle of two boxes.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'eng-oct22-prep-in',
    topic: 'Prepositions',
    category: 'Prepositions',
    difficulty: 'Easy',
    questionTemplate: 'The cat is _____ the box. (inside)',
    correctAnswerFormula: 'in',
    wrongAnswers: ['on', 'under', 'behind'],
    methodSteps: ['In means inside.', 'The cat is inside the box.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'eng-oct22-prep-on',
    topic: 'Prepositions',
    category: 'Prepositions',
    difficulty: 'Easy',
    questionTemplate: 'The bird is _____ the box. (on top of)',
    correctAnswerFormula: 'on',
    wrongAnswers: ['in', 'under', 'between'],
    methodSteps: ['On means on top of something.', 'The bird is on top of the box.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'eng-oct22-prep-in-front',
    topic: 'Prepositions',
    category: 'Prepositions',
    difficulty: 'Easy',
    questionTemplate: 'The cat is _____ the box. (in front of)',
    correctAnswerFormula: 'in front of',
    wrongAnswers: ['behind', 'under', 'on'],
    methodSteps: ['In front of means before something.', 'The cat is before the box.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'eng-oct22-prep-behind',
    topic: 'Prepositions',
    category: 'Prepositions',
    difficulty: 'Easy',
    questionTemplate: 'The cat is _____ the box. (at the back of)',
    correctAnswerFormula: 'behind',
    wrongAnswers: ['in front of', 'under', 'in'],
    methodSteps: ['Behind means at the back.', 'The cat is at the back of the box.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  // Comprehension - The Paper Boats (Oct 2022 MS)
  {
    id: 'eng-oct22-comp-tim-play',
    topic: 'Comprehension',
    category: 'Comprehension',
    difficulty: 'Easy',
    questionTemplate: 'Where does Tim like to play? (From "The Paper Boats")',
    correctAnswerFormula: 'In the rain.',
    wrongAnswers: ['In the house.', 'At school.', 'In the garden.'],
    methodSteps: ['Tim likes to play in the rain.', 'He puts on raincoat and boots and goes outside.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'eng-oct22-comp-tina',
    topic: 'Comprehension',
    category: 'Comprehension',
    difficulty: 'Easy',
    questionTemplate: 'Who is Tina? (From "The Paper Boats")',
    correctAnswerFormula: "Tim's younger sister.",
    wrongAnswers: ['Tim\'s friend.', 'Tim\'s mother.', 'Tim\'s teacher.'],
    methodSteps: ['Tina is Tim\'s younger sister.', 'She is ten years old.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'eng-oct22-comp-title',
    topic: 'Comprehension',
    category: 'Comprehension',
    difficulty: 'Easy',
    questionTemplate: "What is the title of the story about Tim and Tina and puddles?",
    correctAnswerFormula: 'The Paper Boats',
    wrongAnswers: ['The Rain', 'Tim and Tina', 'Paper in Puddles'],
    methodSteps: ['The title of the story is The Paper Boats.', 'They play with paper boats in the puddles.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  // Jan 2022 Comprehension - The Cat and the Cookies (from MS)
  {
    id: 'eng-jan22-comp-spices',
    topic: 'Comprehension',
    category: 'Comprehension',
    difficulty: 'Easy',
    questionTemplate: 'What did Cynthia and Ginny use as spices? (From "The Cat and the Cookies")',
    correctAnswerFormula: 'Cinnamon and ginger',
    wrongAnswers: ['Salt and pepper', 'Sugar and flour', 'Vanilla and nutmeg'],
    methodSteps: ['They decided to make cinnamon cookies and gingerbread.', 'They used spices including cinnamon and ginger.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'eng-jan22-comp-cool',
    topic: 'Comprehension',
    category: 'Comprehension',
    difficulty: 'Easy',
    questionTemplate: 'Where were the cookies and gingerbread placed to cool?',
    correctAnswerFormula: 'On the window ledge',
    wrongAnswers: ['In the fridge', 'On the table', 'In the garage'],
    methodSteps: ['Cynthia placed them on the window ledge to cool.', 'Window ledge is the correct answer.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'eng-jan22-comp-garage',
    topic: 'Comprehension',
    category: 'Comprehension',
    difficulty: 'Easy',
    questionTemplate: 'Why did they go to the garage?',
    correctAnswerFormula: "To fix Ginny's bicycle",
    wrongAnswers: ['To get the cookies', 'To find Cinderella', 'To play'],
    methodSteps: ['They decided to go to the garage to fix Ginny\'s bicycle.', 'Later they would have the cookies.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'eng-jan22-comp-cinderella-face',
    topic: 'Comprehension',
    category: 'Comprehension',
    difficulty: 'Easy',
    questionTemplate: 'What did Cinderella have on her face?',
    correctAnswerFormula: 'Traces of gumdrops',
    wrongAnswers: ['Flour', 'Chocolate', 'Nothing'],
    methodSteps: ['Cinderella had traces of gumdrops all over her face.', 'That is how Ginny guessed what had happened.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
];

export function getEnglishTemplates(): QuestionTemplate[] {
  return englishTemplates;
}
