import { QuestionTemplate } from '@/types/question-template';

/**
 * Education in Human Values Question Templates - Grade 3
 * Extracted from July 2024 Grade 3 Education in Human Values Second Semester Examination
 */

export const HUMAN_VALUES_CATEGORIES = [
  'Values of Love',
  'Respect',
  'Truth and Perseverance',
  'Contentment',
  'Kindness and Compassion',
  'Peace',
  'Patience',
  'Truth',
  'Environmental Care',
  'Kindness to Animals',
  'Helping the Poor and Needy',
  'Anger Management',
  'Respect for Teachers',
  'Understanding Values',
  'Friendship',
] as const;

export const humanValuesTemplates: QuestionTemplate[] = [
  // ========== Values of Love ==========
  {
    id: 'ehv_2024_jul_01a',
    topic: 'Love',
    category: 'Values of Love',
    difficulty: 'Easy',
    questionTemplate: 'Which of the following is a value of love?',
    correctAnswerFormula: 'Forgiving',
    wrongAnswers: ['Hurting', 'Intolerance', 'Jealousy'],
    methodSteps: ['Forgiving is a value of love because it shows compassion and the ability to let go of negative feelings.', 'Values of love include positive actions that bring people together and create harmony.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'ehv_2024_jul_01b',
    topic: 'Love',
    category: 'Values of Love',
    difficulty: 'Easy',
    questionTemplate: 'Which of the following represents a value of love?',
    correctAnswerFormula: 'Giving',
    wrongAnswers: ['Hurting', 'Jealousy', 'Being selfish'],
    methodSteps: ['Giving is an important value of love that involves sharing what we have with others without expecting anything in return.', 'It demonstrates generosity and care for others\' wellbeing.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'ehv_2024_jul_01c',
    topic: 'Love',
    category: 'Values of Love',
    difficulty: 'Easy',
    questionTemplate: 'Which quality shows a value of love?',
    correctAnswerFormula: 'Helping',
    wrongAnswers: ['Ignoring', 'Fighting', 'Being mean'],
    methodSteps: ['Helping others is a fundamental value of love.', 'When we help someone, we show that we care about their needs and are willing to support them.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'ehv_2024_jul_01d',
    topic: 'Love',
    category: 'Values of Love',
    difficulty: 'Easy',
    questionTemplate: 'Which of these is a value of love?',
    correctAnswerFormula: 'Kindness',
    wrongAnswers: ['Intolerance', 'Rudeness', 'Cruelty'],
    methodSteps: ['Kindness is a core value of love that involves being gentle, considerate, and friendly towards others.', 'It creates positive feelings and helps build strong, loving relationships.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'ehv_2024_jul_01e',
    topic: 'Love',
    category: 'Values of Love',
    difficulty: 'Easy',
    questionTemplate: 'Which quality represents a value of love?',
    correctAnswerFormula: 'Caring',
    wrongAnswers: ['Neglecting', 'Ignoring', 'Being unconcerned'],
    methodSteps: ['Caring shows that we are concerned about the wellbeing and happiness of others.', 'It is an essential value of love that involves paying attention to others\' needs and feelings.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'ehv_2024_jul_01f',
    topic: 'Love',
    category: 'Values of Love',
    difficulty: 'Easy',
    questionTemplate: 'Which of the following is a value of love?',
    correctAnswerFormula: 'Loving',
    wrongAnswers: ['Hating', 'Jealousy', 'Hurting'],
    methodSteps: ['Loving is the purest expression of affection and care for others.', 'It encompasses all positive feelings and actions that create bonds of trust, respect, and mutual support.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },

  // ========== Fill in the Blanks - Various Values ==========
  {
    id: 'ehv_2024_jul_02a',
    topic: 'Respect',
    category: 'Respect',
    difficulty: 'Easy',
    questionTemplate: 'Complete the sentence: We must _______ our elders.',
    correctAnswerFormula: 'respect',
    wrongAnswers: ['ignore', 'disobey', 'avoid'],
    methodSteps: ['We must respect our elders because they have more life experience and wisdom.', 'Showing respect to elders is an important value in building harmonious relationships.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'ehv_2024_jul_02b',
    topic: 'Perseverance',
    category: 'Truth and Perseverance',
    difficulty: 'Medium',
    questionTemplate: 'The road to success is never _______.',
    correctAnswerFormula: 'smooth',
    wrongAnswers: ['possible', 'worth it', 'important'],
    methodSteps: ['The road to success is never smooth, meaning there will always be challenges and obstacles.', 'This teaches us to be patient, persistent, and determined when working toward our goals.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'ehv_2024_jul_02c',
    topic: 'Contentment',
    category: 'Contentment',
    difficulty: 'Medium',
    questionTemplate: 'You should be _______ with what you have.',
    correctAnswerFormula: 'happy',
    wrongAnswers: ['sad', 'angry', 'dissatisfied'],
    methodSteps: ['Being happy with what we have is called contentment.', 'It means appreciating and being grateful for our possessions and circumstances rather than always wanting more.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'ehv_2024_jul_02d',
    topic: 'Kindness',
    category: 'Kindness and Compassion',
    difficulty: 'Hard',
    questionTemplate: 'Kindness is a language that the _______ can see.',
    correctAnswerFormula: 'blind',
    wrongAnswers: ['deaf', 'rich', 'young'],
    methodSteps: ['This beautiful saying means that kindness can be felt and understood even by those who cannot physically see.', 'It emphasizes that kindness transcends physical abilities and is expressed through actions and feelings.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 30,
  },
  {
    id: 'ehv_2024_jul_02e',
    topic: 'Peace',
    category: 'Peace',
    difficulty: 'Medium',
    questionTemplate: '_______ begins with a smile.',
    correctAnswerFormula: 'Peace',
    wrongAnswers: ['War', 'Anger', 'Sadness'],
    methodSteps: ['Peace begins with a smile because a smile is a simple yet powerful gesture that shows friendliness and goodwill.', 'It can break barriers, ease tensions, and create positive connections between people.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },

  // ========== True or False ==========
  {
    id: 'ehv_2024_jul_03a',
    topic: 'Patience',
    category: 'Patience',
    difficulty: 'Easy',
    questionTemplate: 'True or False: We should not be patient during hard times.',
    correctAnswerFormula: 'False',
    wrongAnswers: ['True', 'Sometimes true', 'Only on weekends'],
    methodSteps: ['This statement is FALSE. We should definitely be patient during hard times.', 'Patience helps us stay calm, think clearly, and find solutions to our problems.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'ehv_2024_jul_03b',
    topic: 'Truth',
    category: 'Truth',
    difficulty: 'Easy',
    questionTemplate: 'True or False: We should always learn to speak the truth.',
    correctAnswerFormula: 'True',
    wrongAnswers: ['False', 'Only sometimes', 'Never'],
    methodSteps: ['This statement is TRUE. Speaking the truth is a fundamental human value.', 'Honesty builds trust, strengthens relationships, and helps us maintain our integrity.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'ehv_2024_jul_03c',
    topic: 'Truth',
    category: 'Truth',
    difficulty: 'Medium',
    questionTemplate: 'True or False: Truth is the only thing that does not change.',
    correctAnswerFormula: 'True',
    wrongAnswers: ['False', 'Only in some cases', 'It depends'],
    methodSteps: ['This statement is TRUE. Truth is constant and unchanging.', 'While opinions, feelings, and circumstances may change, the truth remains the same.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'ehv_2024_jul_03d',
    topic: 'Environment',
    category: 'Environmental Care',
    difficulty: 'Easy',
    questionTemplate: 'True or False: We must look after our environment.',
    correctAnswerFormula: 'True',
    wrongAnswers: ['False', 'Not necessary', 'Only adults should'],
    methodSteps: ['This statement is TRUE. Looking after our environment is everyone\'s responsibility.', 'We depend on nature for air, water, food, and shelter.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'ehv_2024_jul_03e',
    topic: 'Animals',
    category: 'Kindness to Animals',
    difficulty: 'Easy',
    questionTemplate: 'True or False: We should be rude to animals.',
    correctAnswerFormula: 'False',
    wrongAnswers: ['True', 'Only to wild animals', 'Sometimes'],
    methodSteps: ['This statement is FALSE. We should never be rude to animals.', 'Animals deserve kindness and respect just like humans.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },

  // ========== Situational Questions ==========
  {
    id: 'ehv_2024_jul_04a',
    topic: 'Environment',
    category: 'Environmental Care',
    difficulty: 'Medium',
    questionTemplate: 'What is one effective way to stop pollution?',
    correctAnswerFormula: 'Throw trash into the trash bins',
    wrongAnswers: ['Litter anywhere', 'Burn all plastic', 'Pour waste into rivers'],
    methodSteps: ['Throwing trash into proper bins prevents pollution by keeping our surroundings clean.', 'This simple action helps protect our environment and keeps our communities healthy.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'ehv_2024_jul_04b',
    topic: 'Environment',
    category: 'Environmental Care',
    difficulty: 'Medium',
    questionTemplate: 'How can we help reduce pollution?',
    correctAnswerFormula: 'Plant more trees',
    wrongAnswers: ['Cut down forests', 'Use more plastic bags', 'Waste water'],
    methodSteps: ['Planting more trees helps reduce pollution because trees absorb harmful carbon dioxide and produce oxygen.', 'They also prevent soil erosion and provide habitats for animals.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'ehv_2024_jul_04c',
    topic: 'Helping Others',
    category: 'Helping the Poor and Needy',
    difficulty: 'Easy',
    questionTemplate: 'How can we help poor and needy people?',
    correctAnswerFormula: 'Share food with them',
    wrongAnswers: ['Ignore them', 'Make fun of them', 'Run away from them'],
    methodSteps: ['Sharing food with poor and needy people is a direct way to help them meet their basic needs.', 'This act of kindness shows compassion and generosity.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'ehv_2024_jul_04d',
    topic: 'Helping Others',
    category: 'Helping the Poor and Needy',
    difficulty: 'Easy',
    questionTemplate: 'What should we show to poor and needy people?',
    correctAnswerFormula: 'Kindness',
    wrongAnswers: ['Disrespect', 'Hatred', 'Mockery'],
    methodSteps: ['Showing kindness to poor and needy people treats them with dignity and respect.', 'Everyone deserves to be treated kindly regardless of their circumstances.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'ehv_2024_jul_04e',
    topic: 'Animals',
    category: 'Kindness to Animals',
    difficulty: 'Easy',
    questionTemplate: 'How can we show love and kindness to animals?',
    correctAnswerFormula: 'Give them food',
    wrongAnswers: ['Hurt them', 'Chase them away', 'Throw stones at them'],
    methodSteps: ['Giving animals food shows care and compassion.', 'Animals need food to survive, and by feeding them we demonstrate kindness.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'ehv_2024_jul_04f',
    topic: 'Animals',
    category: 'Kindness to Animals',
    difficulty: 'Medium',
    questionTemplate: 'What is a way to show kindness to animals?',
    correctAnswerFormula: 'Treat the sick animals',
    wrongAnswers: ['Abandon sick animals', 'Ignore injured animals', 'Harm animals'],
    methodSteps: ['Treating sick animals shows compassion and responsibility.', 'When animals are injured or ill, they need help just like humans do.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'ehv_2024_jul_04g',
    topic: 'Anger',
    category: 'Anger Management',
    difficulty: 'Medium',
    questionTemplate: 'What is a good way to calm yourself when you are very angry?',
    correctAnswerFormula: 'Count from 1 to 10',
    wrongAnswers: ['Shout at others', 'Break things', 'Hurt someone'],
    methodSteps: ['Counting from 1 to 10 when angry helps calm your mind by giving you time to pause and think.', 'This technique slows down your reaction and helps control your emotions.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'ehv_2024_jul_04h',
    topic: 'Anger',
    category: 'Anger Management',
    difficulty: 'Medium',
    questionTemplate: 'How can you calm down when feeling very angry?',
    correctAnswerFormula: 'Meditate to calm down',
    wrongAnswers: ['Fight with others', 'Stay angry all day', 'Refuse to talk to anyone'],
    methodSteps: ['Meditation helps calm anger by focusing your mind and relaxing your body.', 'Taking deep breaths and finding inner peace allows you to manage your emotions better.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'ehv_2024_jul_04i',
    topic: 'Teachers',
    category: 'Respect for Teachers',
    difficulty: 'Easy',
    questionTemplate: 'How can you show respect towards your teachers?',
    correctAnswerFormula: 'Listen to the teacher when she teaches',
    wrongAnswers: ['Talk while teacher is teaching', 'Ignore the teacher', 'Disrupt the class'],
    methodSteps: ['Listening to the teacher when they teach shows respect and helps you learn.', 'It demonstrates that you value their time, knowledge, and effort.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'ehv_2024_jul_04j',
    topic: 'Teachers',
    category: 'Respect for Teachers',
    difficulty: 'Easy',
    questionTemplate: 'What is a way to show respect to your teachers?',
    correctAnswerFormula: 'Follow the instructions the teacher gives',
    wrongAnswers: ['Disobey teacher\'s instructions', 'Argue with the teacher', 'Do the opposite of what teacher says'],
    methodSteps: ['Following your teacher\'s instructions shows respect and responsibility.', 'Teachers give instructions to help you learn and stay safe.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },

  // ========== Matching Values ==========
  {
    id: 'ehv_2024_jul_05a',
    topic: 'Generosity',
    category: 'Understanding Values',
    difficulty: 'Medium',
    questionTemplate: 'What value means \'being kind and generous\'?',
    correctAnswerFormula: 'Generosity',
    wrongAnswers: ['Honesty', 'Loyalty', 'Caring'],
    methodSteps: ['Generosity is the quality of being kind and generous.', 'It involves giving freely without expecting anything in return.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'ehv_2024_jul_05b',
    topic: 'Honesty',
    category: 'Understanding Values',
    difficulty: 'Easy',
    questionTemplate: 'Which value means \'speaking and acting truthfully\'?',
    correctAnswerFormula: 'Honesty',
    wrongAnswers: ['Generosity', 'Loyalty', 'Optimistic'],
    methodSteps: ['Honesty means speaking and acting truthfully.', 'An honest person tells the truth, keeps promises, and acts with integrity.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'ehv_2024_jul_05c',
    topic: 'Caring',
    category: 'Understanding Values',
    difficulty: 'Medium',
    questionTemplate: 'What value describes \'showing kindness and concern towards others\'?',
    correctAnswerFormula: 'Caring',
    wrongAnswers: ['Honesty', 'Loyalty', 'Generosity'],
    methodSteps: ['Caring means showing kindness and concern towards others.', 'A caring person thinks about others\' feelings and needs.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'ehv_2024_jul_05d',
    topic: 'Optimism',
    category: 'Understanding Values',
    difficulty: 'Medium',
    questionTemplate: 'Which value means \'hoping and believing in the best\'?',
    correctAnswerFormula: 'Optimistic',
    wrongAnswers: ['Caring', 'Loyalty', 'Honesty'],
    methodSteps: ['Being optimistic means hoping and believing in the best outcomes.', 'Optimistic people maintain a positive attitude and see possibilities rather than problems.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'ehv_2024_jul_05e',
    topic: 'Loyalty',
    category: 'Understanding Values',
    difficulty: 'Medium',
    questionTemplate: 'What value means \'giving firm and constant support to a person or to an institute\'?',
    correctAnswerFormula: 'Loyalty',
    wrongAnswers: ['Generosity', 'Caring', 'Optimistic'],
    methodSteps: ['Loyalty means giving firm and constant support to a person or institution.', 'A loyal person stands by others through good and difficult times.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },

  // ========== Poem Comprehension - Let's Be Friends ==========
  {
    id: 'ehv_2024_jul_07a',
    topic: 'Friendship',
    category: 'Friendship',
    difficulty: 'Medium',
    questionTemplate: 'According to the poem \'Let\'s Be Friends\', why is the kid lucky?',
    correctAnswerFormula: 'To have a friend like him',
    wrongAnswers: ['To have lots of toys', 'To have a big house', 'To get good grades'],
    methodSteps: ['The kid feels lucky to have a good friend.', 'The poem emphasizes that true friendship is valuable and enriching.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'ehv_2024_jul_07b',
    topic: 'Friendship',
    category: 'Friendship',
    difficulty: 'Easy',
    questionTemplate: 'In the poem \'Let\'s Be Friends\', what is one activity friends will do together?',
    correctAnswerFormula: 'Run around in the backyard',
    wrongAnswers: ['Watch TV alone', 'Study separately', 'Stay indoors all day'],
    methodSteps: ['The poem mentions friends running around in the backyard together.', 'This shows that friendship involves shared activities and spending active, fun time together.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'ehv_2024_jul_07c',
    topic: 'Friendship',
    category: 'Friendship',
    difficulty: 'Easy',
    questionTemplate: 'According to the poem, what will the friends do at school?',
    correctAnswerFormula: 'Walk to school together',
    wrongAnswers: ['Go to school separately', 'Skip school', 'Fight at school'],
    methodSteps: ['The poem says friends will walk to school together.', 'Walking together shows companionship and makes ordinary activities more enjoyable.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'ehv_2024_jul_07d',
    topic: 'Friendship',
    category: 'Friendship',
    difficulty: 'Easy',
    questionTemplate: 'What will the friends do at lunch according to the poem?',
    correctAnswerFormula: 'Share their lunches',
    wrongAnswers: ['Eat alone', 'Throw away food', 'Fight over food'],
    methodSteps: ['The poem mentions friends will share their lunches.', 'Sharing is an important way friends show they care about each other.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'ehv_2024_jul_07e',
    topic: 'Friendship',
    category: 'Friendship',
    difficulty: 'Medium',
    questionTemplate: 'What quality can be learned from the poem \'Let\'s Be Friends\'?',
    correctAnswerFormula: 'Sharing with others',
    wrongAnswers: ['Being selfish', 'Staying alone', 'Keeping everything to yourself'],
    methodSteps: ['The poem teaches the value of sharing with others.', 'The friends share lunches and activities, showing that friendship thrives on generosity.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'ehv_2024_jul_07f',
    topic: 'Friendship',
    category: 'Friendship',
    difficulty: 'Medium',
    questionTemplate: 'What is another quality shown in the poem \'Let\'s Be Friends\'?',
    correctAnswerFormula: 'Playing with others',
    wrongAnswers: ['Ignoring others', 'Fighting with friends', 'Being mean'],
    methodSteps: ['The poem emphasizes playing with others as an important part of friendship.', 'Playing together brings joy and helps build strong relationships.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
];

export function getHumanValuesTemplates(): QuestionTemplate[] {
  return humanValuesTemplates;
}
