import { QuestionTemplate } from '@/types/question-template';

/**
 * Mathematics Preview Question Templates - Grade 3
 * Based on textbook learning objectives
 * ~280 questions organized by skill area
 * FOR REVIEW BEFORE ADDING TO MAIN MATHEMATICS SECTION
 */

export const MATH_PREVIEW_CATEGORIES = [
  'Comparing Numbers',
  'Place Value',
  'Number Lines',
  'Rounding Numbers',
  'Ordering Numbers',
  'Multiply/Divide by 10',
  'Counting Patterns',
  'Addition Partitioning',
  'Addition Methods',
  'Money Subtraction',
  'Subtraction Crossing 100',
  'Times Tables Links',
  '8 Times Table',
  'Multiply/Divide by 4',
  'Multiply/Divide by 8',
  'Doubling and Halving',
  'Advanced Doubling',
  'Grid Method Multiplication',
  'Fractions of Amounts',
  'Fractions and Wholes',
  'Comparing Fractions',
  'Unit Fractions',
  'Non-Unit Fractions',
  'Fractions on Number Line',
  'Right Angles',
  'Shape Recognition',
  '2D Shape Properties',
  '3D Shapes',
  'Perimeter',
  'Angles and Turns',
  'Time - Quarter Hours',
  'Time - 5 Minutes',
  'Time - 1 Minute',
  'Time - Seconds',
  'Time Calculations',
  'Days and Weeks',
  'Calendar',
  'Money - Making Amounts',
  'Money - Addition',
  'Length Conversions',
  'Capacity Conversions',
  'Estimating Capacity',
  'Division with Remainders',
] as const;

export const mathPreviewTemplates: QuestionTemplate[] = [
  
  // ========== COMPARING NUMBERS ==========
  {
    id: 'preview_comp_01',
    topic: 'Comparing 3-digit numbers',
    category: 'Comparing Numbers',
    difficulty: 'Easy',
    questionTemplate: 'Which is greater: 345 or 354?',
    correctAnswerFormula: '354',
    wrongAnswers: ['345', '543', '435'],
    methodSteps: ['Compare the digits from left to right.', 'Both have 3 hundreds.', '345 has 4 tens, 354 has 5 tens.', '5 tens is more than 4 tens, so 354 is greater.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'preview_comp_02',
    topic: 'Ordering numbers',
    category: 'Comparing Numbers',
    difficulty: 'Easy',
    questionTemplate: 'Put these in order from smallest to largest: 256, 265, 562',
    correctAnswerFormula: '256, 265, 562',
    wrongAnswers: ['265, 256, 562', '562, 265, 256', '256, 562, 265'],
    methodSteps: ['Compare hundreds first: all have 2 or 5 hundreds.', '256 and 265 have 2 hundreds, 562 has 5 hundreds.', 'Compare 256 and 265: 256 has 5 tens, 265 has 6 tens.', 'Order: 256, 265, 562'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'preview_comp_03',
    topic: 'Greater than or less than',
    category: 'Comparing Numbers',
    difficulty: 'Medium',
    questionTemplate: 'Fill in: 478 ___ 487',
    correctAnswerFormula: '<',
    wrongAnswers: ['>', '=', '≠'],
    methodSteps: ['Compare hundreds: both have 4 hundreds.', 'Compare tens: 478 has 7 tens, 487 has 8 tens.', '7 tens < 8 tens', 'So 478 < 487'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'preview_comp_04',
    topic: 'Number in range',
    category: 'Comparing Numbers',
    difficulty: 'Medium',
    questionTemplate: 'Which number is between 300 and 350?',
    correctAnswerFormula: '325',
    wrongAnswers: ['295', '360', '285'],
    methodSteps: ['We need a number greater than 300 and less than 350.', '295 is less than 300 - too small.', '360 is greater than 350 - too big.', '325 is between 300 and 350 ✓'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'preview_comp_05',
    topic: 'Ordering multiple numbers',
    category: 'Comparing Numbers',
    difficulty: 'Hard',
    questionTemplate: 'Order these from smallest to largest: 709, 790, 907, 970, 799',
    correctAnswerFormula: '709, 790, 799, 907, 970',
    wrongAnswers: ['709, 799, 790, 907, 970', '970, 907, 799, 790, 709', '709, 790, 907, 799, 970'],
    methodSteps: ['All have 7 or 9 hundreds.', '709 and 790, 799 have 7 hundreds.', '907 and 970 have 9 hundreds.', 'In the 700s: 709, 790, 799', 'In the 900s: 907, 970', 'Final order: 709, 790, 799, 907, 970'],
    questionType: 'mcq',
    estimatedTimeSeconds: 35,
  },
  {
    id: 'preview_comp_06',
    topic: 'Place value comparison',
    category: 'Comparing Numbers',
    difficulty: 'Hard',
    questionTemplate: 'True or False: 6 hundreds and 5 tens is less than 605',
    correctAnswerFormula: 'False',
    wrongAnswers: ['True'],
    methodSteps: ['6 hundreds and 5 tens = 600 + 50 = 650', '605 means 6 hundreds, 0 tens, and 5 ones.', 'Compare: 650 and 605', '650 is greater than 605, not less than.', 'So the statement is FALSE.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 30,
  },

  // ========== PLACE VALUE ==========
  {
    id: 'preview_pv_01',
    topic: 'Building numbers',
    category: 'Place Value',
    difficulty: 'Easy',
    questionTemplate: 'I have 3 hundreds, 4 tens, and 5 ones. What number is this?',
    correctAnswerFormula: '345',
    wrongAnswers: ['354', '543', '435'],
    methodSteps: ['3 hundreds = 300', '4 tens = 40', '5 ones = 5', 'Add them: 300 + 40 + 5 = 345'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'preview_pv_02',
    topic: 'Place value positions',
    category: 'Place Value',
    difficulty: 'Medium',
    questionTemplate: 'A number has 7 in the tens place and 2 in the hundreds place. The ones digit is 9. What is the number?',
    correctAnswerFormula: '279',
    wrongAnswers: ['297', '729', '792'],
    methodSteps: ['Hundreds place: 2 → 200', 'Tens place: 7 → 70', 'Ones place: 9 → 9', 'The number is 279'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'preview_pv_03',
    topic: 'Adding tens',
    category: 'Place Value',
    difficulty: 'Easy',
    questionTemplate: 'What is 10 more than 456?',
    correctAnswerFormula: '466',
    wrongAnswers: ['556', '457', '446'],
    methodSteps: ['456 + 10 means add 1 ten to the tens place.', '456 has 5 tens, add 1 more = 6 tens', 'The number becomes 466'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'preview_pv_04',
    topic: 'Subtracting tens',
    category: 'Place Value',
    difficulty: 'Medium',
    questionTemplate: 'I subtract 2 tens from 531. What number do I get?',
    correctAnswerFormula: '511',
    wrongAnswers: ['529', '551', '331'],
    methodSteps: ['531 has 3 tens in the tens place.', 'Subtract 2 tens: 3 tens - 2 tens = 1 ten', 'The number becomes 511'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'preview_pv_05',
    topic: 'Complex place value',
    category: 'Place Value',
    difficulty: 'Hard',
    questionTemplate: 'The hundreds digit is double the tens digit. The tens digit is 3. The ones digit is 0. What is the number?',
    correctAnswerFormula: '630',
    wrongAnswers: ['360', '603', '306'],
    methodSteps: ['Tens digit is 3', 'Hundreds digit is double: 3 × 2 = 6', 'Ones digit is 0', 'The number is 630'],
    questionType: 'mcq',
    estimatedTimeSeconds: 30,
  },
  {
    id: 'preview_pv_06',
    topic: 'Partitioning',
    category: 'Place Value',
    difficulty: 'Easy',
    questionTemplate: '364 = 300 + ___ + 4',
    correctAnswerFormula: '60',
    wrongAnswers: ['6', '600', '36'],
    methodSteps: ['364 = 300 + ? + 4', 'The tens digit is 6, which means 60 (6 tens)', '364 = 300 + 60 + 4'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'preview_pv_07',
    topic: 'Full partitioning',
    category: 'Place Value',
    difficulty: 'Easy',
    questionTemplate: 'Partition 527 into hundreds, tens, and ones',
    correctAnswerFormula: '500 + 20 + 7',
    wrongAnswers: ['5 + 2 + 7', '50 + 2 + 7', '500 + 2 + 7'],
    methodSteps: ['Hundreds: 5 hundreds = 500', 'Tens: 2 tens = 20', 'Ones: 7 ones = 7', 'Partition: 500 + 20 + 7'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'preview_pv_08',
    topic: 'Recombining',
    category: 'Place Value',
    difficulty: 'Medium',
    questionTemplate: '400 + 70 + 5 = ?',
    correctAnswerFormula: '475',
    wrongAnswers: ['4075', '457', '745'],
    methodSteps: ['400 = 4 hundreds', '70 = 7 tens', '5 = 5 ones', 'Combine: 475'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'preview_pv_09',
    topic: 'Digit value',
    category: 'Place Value',
    difficulty: 'Medium',
    questionTemplate: 'In 682, what is the value of the 8?',
    correctAnswerFormula: '80',
    wrongAnswers: ['8', '800', '82'],
    methodSteps: ['The 8 is in the tens place.', '8 in the tens place = 8 tens = 80', 'The value of 8 is 80'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'preview_pv_10',
    topic: 'Building from description',
    category: 'Place Value',
    difficulty: 'Hard',
    questionTemplate: 'What number is 5 hundreds, 3 ones, and 9 tens?',
    correctAnswerFormula: '593',
    wrongAnswers: ['539', '935', '395'],
    methodSteps: ['5 hundreds = 500', '9 tens = 90', '3 ones = 3', 'Combine in order: 500 + 90 + 3 = 593'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },

  // ========== MULTIPLY/DIVIDE BY 10 ==========
  {
    id: 'preview_m10_01',
    topic: 'Multiply by 10',
    category: 'Multiply/Divide by 10',
    difficulty: 'Easy',
    questionTemplate: '23 × 10 = ?',
    correctAnswerFormula: '230',
    wrongAnswers: ['203', '2300', '23'],
    methodSteps: ['When you multiply by 10, add a zero to the end.', '23 × 10 = 230'],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },
  {
    id: 'preview_m10_02',
    topic: 'Divide by 10',
    category: 'Multiply/Divide by 10',
    difficulty: 'Easy',
    questionTemplate: '180 ÷ 10 = ?',
    correctAnswerFormula: '18',
    wrongAnswers: ['1800', '180', '1.8'],
    methodSteps: ['When you divide by 10, remove a zero from the end.', '180 ÷ 10 = 18'],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },
  {
    id: 'preview_m10_03',
    topic: 'Word problem multiply',
    category: 'Multiply/Divide by 10',
    difficulty: 'Medium',
    questionTemplate: 'I have 10 bags with 15 marbles in each bag. How many marbles in total?',
    correctAnswerFormula: '150',
    wrongAnswers: ['25', '105', '1510'],
    methodSteps: ['10 bags × 15 marbles per bag', '15 × 10 = 150', 'Total: 150 marbles'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'preview_m10_04',
    topic: 'Larger division',
    category: 'Multiply/Divide by 10',
    difficulty: 'Medium',
    questionTemplate: '640 ÷ 10 = ?',
    correctAnswerFormula: '64',
    wrongAnswers: ['6400', '604', '6.4'],
    methodSteps: ['Divide by 10: remove one zero.', '640 ÷ 10 = 64'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'preview_m10_05',
    topic: 'Word problem divide',
    category: 'Multiply/Divide by 10',
    difficulty: 'Hard',
    questionTemplate: 'A rope is 370 cm long. I cut it into 10 equal pieces. How long is each piece?',
    correctAnswerFormula: '37 cm',
    wrongAnswers: ['3.7 cm', '3700 cm', '360 cm'],
    methodSteps: ['Total length: 370 cm', 'Cut into 10 pieces: 370 ÷ 10', '370 ÷ 10 = 37', 'Each piece is 37 cm'],
    questionType: 'mcq',
    estimatedTimeSeconds: 30,
  },
  {
    id: 'preview_m10_06',
    topic: 'Pattern recognition',
    category: 'Multiply/Divide by 10',
    difficulty: 'Hard',
    questionTemplate: 'Follow the pattern: 12 → 120 → 1200, so 8 → 80 → ?',
    correctAnswerFormula: '800',
    wrongAnswers: ['8000', '88', '808'],
    methodSteps: ['The pattern multiplies by 10 each time.', '8 × 10 = 80', '80 × 10 = 800'],
    questionType: 'mcq',
    estimatedTimeSeconds: 30,
  },

  // ========== COUNTING PATTERNS ==========
  {
    id: 'preview_cp_01',
    topic: 'Counting in 10s',
    category: 'Counting Patterns',
    difficulty: 'Easy',
    questionTemplate: 'Continue the pattern: 45, 55, 65, ___, ___',
    correctAnswerFormula: '75, 85',
    wrongAnswers: ['70, 80', '76, 86', '74, 84'],
    methodSteps: ['The pattern adds 10 each time.', '65 + 10 = 75', '75 + 10 = 85'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'preview_cp_02',
    topic: 'Counting back in 10s',
    category: 'Counting Patterns',
    difficulty: 'Easy',
    questionTemplate: 'Count back: 238, 228, 218, ___',
    correctAnswerFormula: '208',
    wrongAnswers: ['198', '218', '228'],
    methodSteps: ['The pattern subtracts 10 each time.', '218 - 10 = 208'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'preview_cp_03',
    topic: 'Counting in 50s',
    category: 'Counting Patterns',
    difficulty: 'Medium',
    questionTemplate: 'Fill in: 150, 200, 250, ___, ___',
    correctAnswerFormula: '300, 350',
    wrongAnswers: ['280, 310', '260, 270', '275, 325'],
    methodSteps: ['The pattern adds 50 each time.', '250 + 50 = 300', '300 + 50 = 350'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'preview_cp_04',
    topic: 'Counting back in 50s',
    category: 'Counting Patterns',
    difficulty: 'Medium',
    questionTemplate: 'Start at 425. Count back 3 steps of 50. Where are you?',
    correctAnswerFormula: '275',
    wrongAnswers: ['325', '475', '225'],
    methodSteps: ['Start: 425', 'Step 1: 425 - 50 = 375', 'Step 2: 375 - 50 = 325', 'Step 3: 325 - 50 = 275'],
    questionType: 'mcq',
    estimatedTimeSeconds: 30,
  },
  {
    id: 'preview_cp_05',
    topic: 'Counting in 100s',
    category: 'Counting Patterns',
    difficulty: 'Easy',
    questionTemplate: 'Continue: 320, 420, 520, ___',
    correctAnswerFormula: '620',
    wrongAnswers: ['530', '720', '820'],
    methodSteps: ['The pattern adds 100 each time.', '520 + 100 = 620'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'preview_cp_06',
    topic: 'Multi-step counting',
    category: 'Counting Patterns',
    difficulty: 'Hard',
    questionTemplate: 'I start at 157 and count in 100s four times. What number do I reach?',
    correctAnswerFormula: '557',
    wrongAnswers: ['457', '657', '257'],
    methodSteps: ['Start: 157', 'Count 1: 157 + 100 = 257', 'Count 2: 257 + 100 = 357', 'Count 3: 357 + 100 = 457', 'Count 4: 457 + 100 = 557'],
    questionType: 'mcq',
    estimatedTimeSeconds: 35,
  },

  // ========== ADDITION PARTITIONING ==========
  {
    id: 'preview_ap_01',
    topic: 'Splitting numbers',
    category: 'Addition Partitioning',
    difficulty: 'Easy',
    questionTemplate: 'Split 47 into tens and ones: 47 = ___ + 7',
    correctAnswerFormula: '40',
    wrongAnswers: ['4', '70', '37'],
    methodSteps: ['47 has 4 tens and 7 ones', '4 tens = 40', 'So 47 = 40 + 7'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'preview_ap_02',
    topic: 'Addition using partitioning',
    category: 'Addition Partitioning',
    difficulty: 'Medium',
    questionTemplate: 'Solve 34 + 25 using partitioning. What is the answer?',
    correctAnswerFormula: '59',
    wrongAnswers: ['54', '69', '49'],
    methodSteps: ['Split: 34 = 30 + 4, and 25 = 20 + 5', 'Add tens: 30 + 20 = 50', 'Add ones: 4 + 5 = 9', 'Combine: 50 + 9 = 59'],
    questionType: 'mcq',
    estimatedTimeSeconds: 30,
  },
  {
    id: 'preview_ap_03',
    topic: 'Partitioning first step',
    category: 'Addition Partitioning',
    difficulty: 'Easy',
    questionTemplate: 'To add 56 + 38 using partitioning, first add the tens. What is 50 + 30?',
    correctAnswerFormula: '80',
    wrongAnswers: ['8', '38', '88'],
    methodSteps: ['56 has 5 tens (50), 38 has 3 tens (30)', 'Add the tens: 50 + 30 = 80', 'Next you would add the ones: 6 + 8 = 14', 'Then combine: 80 + 14 = 94'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'preview_ap_04',
    topic: 'Full partitioning problem',
    category: 'Addition Partitioning',
    difficulty: 'Hard',
    questionTemplate: 'Use partitioning to solve 145 + 237. What is the answer?',
    correctAnswerFormula: '382',
    wrongAnswers: ['372', '392', '482'],
    methodSteps: ['Split: 145 = 100 + 40 + 5, and 237 = 200 + 30 + 7', 'Add hundreds: 100 + 200 = 300', 'Add tens: 40 + 30 = 70', 'Add ones: 5 + 7 = 12', 'Combine: 300 + 70 + 12 = 382'],
    questionType: 'mcq',
    estimatedTimeSeconds: 40,
  },

  // ========== TIMES TABLES ==========
  {
    id: 'preview_tt_01',
    topic: 'Basic recall',
    category: 'Times Tables Links',
    difficulty: 'Easy',
    questionTemplate: '7 × 5 = ?',
    correctAnswerFormula: '35',
    wrongAnswers: ['30', '40', '45'],
    methodSteps: ['Count in 5s seven times: 5, 10, 15, 20, 25, 30, 35', '7 × 5 = 35'],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },
  {
    id: 'preview_tt_02',
    topic: 'Link between 2 and 4',
    category: 'Times Tables Links',
    difficulty: 'Medium',
    questionTemplate: '4 × 6 = 24, so 2 × 6 = ? (half of 24)',
    correctAnswerFormula: '12',
    wrongAnswers: ['48', '6', '18'],
    methodSteps: ['4 × 6 = 24', '2 × 6 is half of 4 × 6', 'Half of 24 = 12', 'So 2 × 6 = 12'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'preview_tt_03',
    topic: 'Link between 5 and 10',
    category: 'Times Tables Links',
    difficulty: 'Medium',
    questionTemplate: '5 × 8 = 40, so 10 × 8 = ? (double of 40)',
    correctAnswerFormula: '80',
    wrongAnswers: ['48', '50', '88'],
    methodSteps: ['5 × 8 = 40', '10 × 8 is double of 5 × 8', 'Double 40 = 80', 'So 10 × 8 = 80'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'preview_tt_04',
    topic: 'Using known facts',
    category: 'Times Tables Links',
    difficulty: 'Hard',
    questionTemplate: 'I know 4 × 7 = 28. Use this to find 8 × 7 (double it)',
    correctAnswerFormula: '56',
    wrongAnswers: ['35', '42', '48'],
    methodSteps: ['4 × 7 = 28', '8 × 7 is double of 4 × 7', 'Double 28 = 56', 'So 8 × 7 = 56'],
    questionType: 'mcq',
    estimatedTimeSeconds: 30,
  },
  {
    id: 'preview_8tt_01',
    topic: '8 times table',
    category: '8 Times Table',
    difficulty: 'Easy',
    questionTemplate: '8 × 3 = ?',
    correctAnswerFormula: '24',
    wrongAnswers: ['18', '28', '32'],
    methodSteps: ['Count in 8s three times: 8, 16, 24', '8 × 3 = 24'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'preview_8tt_02',
    topic: '8 times table',
    category: '8 Times Table',
    difficulty: 'Medium',
    questionTemplate: '8 × 7 = ?',
    correctAnswerFormula: '56',
    wrongAnswers: ['48', '64', '54'],
    methodSteps: ['8 × 7 can be found by doubling 4 × 7', '4 × 7 = 28', 'Double 28 = 56'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'preview_8tt_03',
    topic: 'Division with 8',
    category: '8 Times Table',
    difficulty: 'Medium',
    questionTemplate: '88 ÷ 8 = ?',
    correctAnswerFormula: '11',
    wrongAnswers: ['10', '12', '9'],
    methodSteps: ['Think: 8 × ? = 88', '8 × 10 = 80', '8 × 11 = 88', 'So 88 ÷ 8 = 11'],
    questionType: 'mcq',
    estimatedTimeSeconds: 30,
  },

  // ========== MULTIPLY/DIVIDE BY 4 ==========
  {
    id: 'preview_m4_01',
    topic: 'Doubling twice',
    category: 'Multiply/Divide by 4',
    difficulty: 'Medium',
    questionTemplate: '4 × 15: Double 15 = 30, double again = ?',
    correctAnswerFormula: '60',
    wrongAnswers: ['45', '75', '50'],
    methodSteps: ['To multiply by 4, double twice', 'Double 15 = 30', 'Double 30 = 60', '4 × 15 = 60'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'preview_m4_02',
    topic: 'Halving twice',
    category: 'Multiply/Divide by 4',
    difficulty: 'Medium',
    questionTemplate: '64 ÷ 4: Half of 64 = 32, half again = ?',
    correctAnswerFormula: '16',
    wrongAnswers: ['8', '24', '18'],
    methodSteps: ['To divide by 4, halve twice', 'Half of 64 = 32', 'Half of 32 = 16', '64 ÷ 4 = 16'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'preview_m4_03',
    topic: 'Applied multiplication',
    category: 'Multiply/Divide by 4',
    difficulty: 'Hard',
    questionTemplate: '88 ÷ 4 using halving twice = ?',
    correctAnswerFormula: '22',
    wrongAnswers: ['44', '11', '24'],
    methodSteps: ['Half of 88 = 44', 'Half of 44 = 22', '88 ÷ 4 = 22'],
    questionType: 'mcq',
    estimatedTimeSeconds: 30,
  },

  // ========== MULTIPLY/DIVIDE BY 8 ==========
  {
    id: 'preview_m8_01',
    topic: 'Doubling three times',
    category: 'Multiply/Divide by 8',
    difficulty: 'Medium',
    questionTemplate: '8 × 5: Double 5 = 10, double = 20, double = ?',
    correctAnswerFormula: '40',
    wrongAnswers: ['30', '50', '35'],
    methodSteps: ['To multiply by 8, double three times', 'Double 5 = 10', 'Double 10 = 20', 'Double 20 = 40'],
    questionType: 'mcq',
    estimatedTimeSeconds: 30,
  },
  {
    id: 'preview_m8_02',
    topic: 'Halving three times',
    category: 'Multiply/Divide by 8',
    difficulty: 'Medium',
    questionTemplate: '96 ÷ 8: Half = 48, half = 24, half = ?',
    correctAnswerFormula: '12',
    wrongAnswers: ['16', '10', '14'],
    methodSteps: ['To divide by 8, halve three times', 'Half of 96 = 48', 'Half of 48 = 24', 'Half of 24 = 12'],
    questionType: 'mcq',
    estimatedTimeSeconds: 30,
  },

  // ========== DOUBLING AND HALVING ==========
  {
    id: 'preview_dh_01',
    topic: 'Doubling',
    category: 'Doubling and Halving',
    difficulty: 'Easy',
    questionTemplate: 'Double 35',
    correctAnswerFormula: '70',
    wrongAnswers: ['60', '75', '65'],
    methodSteps: ['Double 30 = 60', 'Double 5 = 10', 'Add: 60 + 10 = 70'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'preview_dh_02',
    topic: 'Halving',
    category: 'Doubling and Halving',
    difficulty: 'Easy',
    questionTemplate: 'Half of 64',
    correctAnswerFormula: '32',
    wrongAnswers: ['30', '34', '28'],
    methodSteps: ['Half of 60 = 30', 'Half of 4 = 2', 'Add: 30 + 2 = 32'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'preview_dh_03',
    topic: 'Reverse doubling',
    category: 'Doubling and Halving',
    difficulty: 'Medium',
    questionTemplate: 'I double a number and get 74. What was the number?',
    correctAnswerFormula: '37',
    wrongAnswers: ['148', '34', '40'],
    methodSteps: ['If double = 74, then original = half of 74', 'Half of 74 = 37', 'Check: 37 × 2 = 74 ✓'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },

  // ========== FRACTIONS OF AMOUNTS ==========
  {
    id: 'preview_fa_01',
    topic: 'Half of amount',
    category: 'Fractions of Amounts',
    difficulty: 'Easy',
    questionTemplate: 'Find 1/2 of 20',
    correctAnswerFormula: '10',
    wrongAnswers: ['5', '15', '40'],
    methodSteps: ['1/2 means divide by 2', '20 ÷ 2 = 10', '1/2 of 20 = 10'],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },
  {
    id: 'preview_fa_02',
    topic: 'Quarter of amount',
    category: 'Fractions of Amounts',
    difficulty: 'Easy',
    questionTemplate: 'What is 1/4 of 12?',
    correctAnswerFormula: '3',
    wrongAnswers: ['4', '6', '2'],
    methodSteps: ['1/4 means divide by 4', '12 ÷ 4 = 3', '1/4 of 12 = 3'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'preview_fa_03',
    topic: 'Third of amount',
    category: 'Fractions of Amounts',
    difficulty: 'Medium',
    questionTemplate: 'Find 1/3 of 24 sweets',
    correctAnswerFormula: '8',
    wrongAnswers: ['6', '12', '9'],
    methodSteps: ['1/3 means divide by 3', '24 ÷ 3 = 8', '1/3 of 24 = 8 sweets'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'preview_fa_04',
    topic: 'Multiple parts',
    category: 'Fractions of Amounts',
    difficulty: 'Hard',
    questionTemplate: 'Find 3/4 of 20 (find 1/4 first, then multiply by 3)',
    correctAnswerFormula: '15',
    wrongAnswers: ['12', '16', '18'],
    methodSteps: ['First find 1/4: 20 ÷ 4 = 5', 'Then multiply by 3: 5 × 3 = 15', '3/4 of 20 = 15'],
    questionType: 'mcq',
    estimatedTimeSeconds: 35,
  },

  // ========== COMPARING FRACTIONS ==========
  {
    id: 'preview_cf_01',
    topic: 'Comparing unit fractions',
    category: 'Comparing Fractions',
    difficulty: 'Easy',
    questionTemplate: 'Which is bigger: 1/2 or 1/4?',
    correctAnswerFormula: '1/2',
    wrongAnswers: ['1/4', 'They are equal', 'Cannot compare'],
    methodSteps: ['1/2 means one piece out of 2 equal pieces (big pieces)', '1/4 means one piece out of 4 equal pieces (smaller pieces)', 'Bigger piece = 1/2'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'preview_cf_02',
    topic: 'Ordering fractions',
    category: 'Comparing Fractions',
    difficulty: 'Medium',
    questionTemplate: 'Put in order smallest to largest: 1/3, 1/2, 1/5',
    correctAnswerFormula: '1/5, 1/3, 1/2',
    wrongAnswers: ['1/2, 1/3, 1/5', '1/3, 1/5, 1/2', '1/5, 1/2, 1/3'],
    methodSteps: ['More pieces = smaller each piece', '1/5 is smallest (5 pieces)', '1/3 is medium (3 pieces)', '1/2 is biggest (2 pieces)'],
    questionType: 'mcq',
    estimatedTimeSeconds: 30,
  },
  {
    id: 'preview_cf_03',
    topic: 'Equivalent fractions',
    category: 'Comparing Fractions',
    difficulty: 'Medium',
    questionTemplate: '1/2 = ?/4',
    correctAnswerFormula: '2/4',
    wrongAnswers: ['1/4', '3/4', '4/4'],
    methodSteps: ['1/2 means 1 out of 2', 'If we split each half into 2 pieces, we get 4 pieces total', '1/2 = 2/4 (2 out of 4)'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },

  // ========== TIME ==========
  {
    id: 'preview_t_01',
    topic: 'Reading time - 5 minutes',
    category: 'Time - 5 Minutes',
    difficulty: 'Easy',
    questionTemplate: 'The clock shows the big hand on 3 and small hand on 3. What time is it?',
    correctAnswerFormula: '3:15',
    wrongAnswers: ['3:30', '3:03', '15:03'],
    methodSteps: ['Small hand (hour hand) on 3 = 3 o\'clock hour', 'Big hand (minute hand) on 3 = 15 minutes', 'Time is 3:15 (quarter past 3)'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'preview_t_02',
    topic: 'Seconds in a minute',
    category: 'Time - Seconds',
    difficulty: 'Easy',
    questionTemplate: 'How many seconds in 1 minute?',
    correctAnswerFormula: '60',
    wrongAnswers: ['100', '30', '50'],
    methodSteps: ['There are 60 seconds in 1 minute'],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },
  {
    id: 'preview_t_03',
    topic: 'Adding minutes',
    category: 'Time Calculations',
    difficulty: 'Medium',
    questionTemplate: 'It is 3:10. What time will it be in 5 minutes?',
    correctAnswerFormula: '3:15',
    wrongAnswers: ['3:05', '3:50', '8:10'],
    methodSteps: ['Start time: 3:10', 'Add 5 minutes: 10 + 5 = 15', 'New time: 3:15'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'preview_t_04',
    topic: 'Time earlier',
    category: 'Time Calculations',
    difficulty: 'Medium',
    questionTemplate: 'It is 5:20. What was the time 10 minutes ago?',
    correctAnswerFormula: '5:10',
    wrongAnswers: ['5:30', '4:20', '5:00'],
    methodSteps: ['Current time: 5:20', 'Subtract 10 minutes: 20 - 10 = 10', 'Time was: 5:10'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },

  // ========== PERIMETER ==========
  {
    id: 'preview_per_01',
    topic: 'Rectangle perimeter',
    category: 'Perimeter',
    difficulty: 'Easy',
    questionTemplate: 'A rectangle is 5cm long and 3cm wide. What is the perimeter?',
    correctAnswerFormula: '16 cm',
    wrongAnswers: ['15 cm', '8 cm', '18 cm'],
    methodSteps: ['Perimeter = add all sides', 'Rectangle has 2 long sides (5cm each) and 2 short sides (3cm each)', '5 + 5 + 3 + 3 = 16 cm'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'preview_per_02',
    topic: 'Square perimeter',
    category: 'Perimeter',
    difficulty: 'Medium',
    questionTemplate: 'A square has perimeter 24cm. How long is each side?',
    correctAnswerFormula: '6 cm',
    wrongAnswers: ['4 cm', '8 cm', '12 cm'],
    methodSteps: ['A square has 4 equal sides', 'Perimeter = 24 cm', 'Each side = 24 ÷ 4 = 6 cm'],
    questionType: 'mcq',
    estimatedTimeSeconds: 30,
  },

  // ========== 2D SHAPES ==========
  {
    id: 'preview_2d_01',
    topic: 'Counting sides',
    category: '2D Shape Properties',
    difficulty: 'Easy',
    questionTemplate: 'How many sides does a triangle have?',
    correctAnswerFormula: '3',
    wrongAnswers: ['4', '5', '6'],
    methodSteps: ['A triangle has 3 sides and 3 corners'],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },
  {
    id: 'preview_2d_02',
    topic: 'Recognizing shapes',
    category: 'Shape Recognition',
    difficulty: 'Easy',
    questionTemplate: 'How many sides does a hexagon have?',
    correctAnswerFormula: '6',
    wrongAnswers: ['5', '7', '8'],
    methodSteps: ['A hexagon has 6 sides', 'Hex means 6'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'preview_2d_03',
    topic: 'Right angles',
    category: 'Right Angles',
    difficulty: 'Easy',
    questionTemplate: 'How many right angles in a square?',
    correctAnswerFormula: '4',
    wrongAnswers: ['2', '3', '1'],
    methodSteps: ['A square has 4 corners', 'Each corner is a right angle (90°)', 'Total: 4 right angles'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'preview_2d_04',
    topic: 'Identifying angles',
    category: 'Right Angles',
    difficulty: 'Easy',
    questionTemplate: 'Which corner of a book makes a right angle?',
    correctAnswerFormula: 'Any corner',
    wrongAnswers: ['Only the top corner', 'Only the bottom corner', 'No corners'],
    methodSteps: ['All corners of a book are right angles', 'A right angle looks like the corner of a square or rectangle', 'It makes an L shape'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'preview_2d_05',
    topic: 'Finding right angles',
    category: 'Right Angles',
    difficulty: 'Easy',
    questionTemplate: 'True or False: The corner of a door frame is a right angle.',
    correctAnswerFormula: 'True',
    wrongAnswers: ['False'],
    methodSteps: ['Door frames have corners that make right angles', 'Right angles are found in many rectangular objects around us', 'They look like the letter L'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },

  // ========== ROUNDING ==========
  {
    id: 'preview_rd_01',
    topic: 'Rounding to nearest 10',
    category: 'Rounding Numbers',
    difficulty: 'Easy',
    questionTemplate: 'Round 47 to the nearest 10',
    correctAnswerFormula: '50',
    wrongAnswers: ['40', '45', '47'],
    methodSteps: ['47 is between 40 and 50', '47 is closer to 50', 'Round to 50'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'preview_rd_02',
    topic: 'Rounding to nearest 100',
    category: 'Rounding Numbers',
    difficulty: 'Medium',
    questionTemplate: 'Round 345 to the nearest 100',
    correctAnswerFormula: '300',
    wrongAnswers: ['400', '350', '340'],
    methodSteps: ['345 is between 300 and 400', '345 is closer to 300 (only 45 away)', 'Round to 300'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'preview_rd_03',
    topic: 'Rounding halfway',
    category: 'Rounding Numbers',
    difficulty: 'Hard',
    questionTemplate: 'Round 450 to the nearest 100',
    correctAnswerFormula: '500',
    wrongAnswers: ['400', '450', '550'],
    methodSteps: ['450 is exactly halfway between 400 and 500', 'When exactly halfway, round UP', 'Round to 500'],
    questionType: 'mcq',
    estimatedTimeSeconds: 30,
  },

  // ========== ORDERING ==========
  {
    id: 'preview_ord_01',
    topic: 'Simple ordering',
    category: 'Ordering Numbers',
    difficulty: 'Easy',
    questionTemplate: 'Order from smallest to largest: 345, 354, 453',
    correctAnswerFormula: '345, 354, 453',
    wrongAnswers: ['354, 345, 453', '453, 354, 345', '345, 453, 354'],
    methodSteps: ['Compare hundreds: all have 3 or 4', '345 and 354 have 3 hundreds, 453 has 4 hundreds', 'In the 300s: 345 < 354', 'Order: 345, 354, 453'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },

  // ========== MONEY SUBTRACTION ==========
  {
    id: 'preview_ms_01',
    topic: 'Change from £5',
    category: 'Money Subtraction',
    difficulty: 'Easy',
    questionTemplate: 'I spend £3. I paid with £5. How much change?',
    correctAnswerFormula: '£2',
    wrongAnswers: ['£3', '£1', '£8'],
    methodSteps: ['Paid: £5', 'Spent: £3', 'Change: £5 - £3 = £2'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'preview_ms_02',
    topic: 'Change from £10',
    category: 'Money Subtraction',
    difficulty: 'Medium',
    questionTemplate: 'Item costs £7.25. Pay with £10. What change?',
    correctAnswerFormula: '£2.75',
    wrongAnswers: ['£3.75', '£2.25', '£3.25'],
    methodSteps: ['Count up from £7.25 to £10', 'From £7.25 to £8 = 75p', 'From £8 to £10 = £2', 'Total change: £2 + 75p = £2.75'],
    questionType: 'mcq',
    estimatedTimeSeconds: 30,
  },

  // ========== SUBTRACTION CROSSING 100 ==========
  {
    id: 'preview_sc_01',
    topic: 'Counting up method',
    category: 'Subtraction Crossing 100',
    difficulty: 'Hard',
    questionTemplate: '502 - 298: Count up from 298 to 300, then to 502',
    correctAnswerFormula: '204',
    wrongAnswers: ['294', '214', '194'],
    methodSteps: ['Count from 298 to 300 = 2', 'Count from 300 to 502 = 202', 'Total: 2 + 202 = 204'],
    questionType: 'mcq',
    estimatedTimeSeconds: 35,
  },

  // ========== HALVING TO 40 ==========
  {
    id: 'preview_halv_01',
    topic: 'Halving to 40',
    category: 'Doubling and Halving',
    difficulty: 'Easy',
    questionTemplate: 'Half of 20 = ?',
    correctAnswerFormula: '10',
    wrongAnswers: ['5', '15', '40'],
    methodSteps: ['Half means divide by 2', '20 ÷ 2 = 10'],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },
  {
    id: 'preview_halv_02',
    topic: 'Halving to 40',
    category: 'Doubling and Halving',
    difficulty: 'Easy',
    questionTemplate: 'Half of 30 = ?',
    correctAnswerFormula: '15',
    wrongAnswers: ['10', '20', '60'],
    methodSteps: ['Half means divide by 2', '30 ÷ 2 = 15'],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },
  {
    id: 'preview_halv_03',
    topic: 'Halving even numbers',
    category: 'Doubling and Halving',
    difficulty: 'Medium',
    questionTemplate: 'Half of 26 = ?',
    correctAnswerFormula: '13',
    wrongAnswers: ['12', '14', '52'],
    methodSteps: ['Half of 20 = 10', 'Half of 6 = 3', '10 + 3 = 13'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'preview_halv_04',
    topic: 'Halving larger numbers',
    category: 'Doubling and Halving',
    difficulty: 'Medium',
    questionTemplate: 'Half of 38 = ?',
    correctAnswerFormula: '19',
    wrongAnswers: ['17', '18', '76'],
    methodSteps: ['Half of 30 = 15', 'Half of 8 = 4', '15 + 4 = 19'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'preview_halv_05',
    topic: 'Reverse halving',
    category: 'Doubling and Halving',
    difficulty: 'Hard',
    questionTemplate: 'I halve a number and get 18. What was the number?',
    correctAnswerFormula: '36',
    wrongAnswers: ['9', '38', '19'],
    methodSteps: ['If half = 18, then double it to find the original', '18 × 2 = 36', 'Check: 36 ÷ 2 = 18 ✓'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },

  // ========== ADVANCED DOUBLING ==========
  {
    id: 'preview_adv_dbl_01',
    topic: 'Doubling to 30',
    category: 'Advanced Doubling',
    difficulty: 'Easy',
    questionTemplate: 'Double 15 = ?',
    correctAnswerFormula: '30',
    wrongAnswers: ['25', '20', '35'],
    methodSteps: ['Double 10 = 20', 'Double 5 = 10', '20 + 10 = 30'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'preview_adv_dbl_02',
    topic: 'Doubling to 30',
    category: 'Advanced Doubling',
    difficulty: 'Medium',
    questionTemplate: 'Double 28 = ?',
    correctAnswerFormula: '56',
    wrongAnswers: ['48', '54', '58'],
    methodSteps: ['Double 20 = 40', 'Double 8 = 16', '40 + 16 = 56'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'preview_adv_dbl_03',
    topic: 'Reverse doubling',
    category: 'Advanced Doubling',
    difficulty: 'Medium',
    questionTemplate: 'I doubled a number and got 24. What was the number?',
    correctAnswerFormula: '12',
    wrongAnswers: ['48', '6', '14'],
    methodSteps: ['If double = 24, halve it to find original', '24 ÷ 2 = 12', 'Check: 12 × 2 = 24 ✓'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'preview_adv_dbl_04',
    topic: 'Doubling beyond 50',
    category: 'Advanced Doubling',
    difficulty: 'Hard',
    questionTemplate: 'Double 45 = ?',
    correctAnswerFormula: '90',
    wrongAnswers: ['80', '85', '95'],
    methodSteps: ['Double 40 = 80', 'Double 5 = 10', '80 + 10 = 90'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'preview_adv_dbl_05',
    topic: 'Doubling large numbers',
    category: 'Advanced Doubling',
    difficulty: 'Hard',
    questionTemplate: 'Double 52 = ?',
    correctAnswerFormula: '104',
    wrongAnswers: ['100', '102', '106'],
    methodSteps: ['Double 50 = 100', 'Double 2 = 4', '100 + 4 = 104'],
    questionType: 'mcq',
    estimatedTimeSeconds: 30,
  },

  // ========== DAYS AND WEEKS ==========
  {
    id: 'preview_cal_01',
    topic: 'Days in a week',
    category: 'Days and Weeks',
    difficulty: 'Easy',
    questionTemplate: 'How many days are in 1 week?',
    correctAnswerFormula: '7',
    wrongAnswers: ['5', '6', '10'],
    methodSteps: ['A week has 7 days', 'Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday'],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },
  {
    id: 'preview_cal_02',
    topic: 'Weeks in a month',
    category: 'Calendar',
    difficulty: 'Easy',
    questionTemplate: 'About how many weeks are in a month?',
    correctAnswerFormula: '4',
    wrongAnswers: ['2', '3', '5'],
    methodSteps: ['Most months have about 4 weeks', '4 weeks × 7 days = 28 days', 'Most months have 30 or 31 days'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'preview_cal_03',
    topic: 'Date calculation',
    category: 'Calendar',
    difficulty: 'Medium',
    questionTemplate: 'If today is the 7th, what date will it be in 1 week?',
    correctAnswerFormula: '14th',
    wrongAnswers: ['13th', '8th', '15th'],
    methodSteps: ['1 week = 7 days', 'Add 7 to current date: 7 + 7 = 14', 'It will be the 14th'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'preview_cal_04',
    topic: 'Days in weeks',
    category: 'Days and Weeks',
    difficulty: 'Medium',
    questionTemplate: 'If there are 7 days in a week, how many days in 2 weeks?',
    correctAnswerFormula: '14',
    wrongAnswers: ['12', '10', '21'],
    methodSteps: ['2 weeks × 7 days per week', '2 × 7 = 14 days'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'preview_cal_05',
    topic: 'Weeks in a year',
    category: 'Calendar',
    difficulty: 'Medium',
    questionTemplate: 'About how many weeks are in a year?',
    correctAnswerFormula: '52',
    wrongAnswers: ['50', '48', '60'],
    methodSteps: ['A year has 365 days', '365 ÷ 7 ≈ 52 weeks', 'There are 52 weeks in a year'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'preview_cal_06',
    topic: 'Days in a year',
    category: 'Calendar',
    difficulty: 'Hard',
    questionTemplate: 'About how many days are in a year?',
    correctAnswerFormula: '365',
    wrongAnswers: ['360', '300', '400'],
    methodSteps: ['Most years have 365 days', '(Leap years have 366 days)', 'A year is 365 days'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'preview_cal_07',
    topic: 'Day after',
    category: 'Days and Weeks',
    difficulty: 'Easy',
    questionTemplate: 'What day comes after Wednesday?',
    correctAnswerFormula: 'Thursday',
    wrongAnswers: ['Tuesday', 'Friday', 'Monday'],
    methodSteps: ['Days of the week in order:', 'Monday, Tuesday, Wednesday, Thursday...', 'After Wednesday comes Thursday'],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },

  // ========== TIME - QUARTER HOURS ==========
  {
    id: 'preview_tq_01',
    topic: 'Quarter past',
    category: 'Time - Quarter Hours',
    difficulty: 'Easy',
    questionTemplate: 'The clock shows quarter past 3. What time is this?',
    correctAnswerFormula: '3:15',
    wrongAnswers: ['3:30', '3:45', '4:15'],
    methodSteps: ['Quarter past = 15 minutes after the hour', 'Quarter past 3 = 3:15'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'preview_tq_02',
    topic: 'Quarter to',
    category: 'Time - Quarter Hours',
    difficulty: 'Medium',
    questionTemplate: 'Quarter to 9 means what time?',
    correctAnswerFormula: '8:45',
    wrongAnswers: ['9:15', '9:45', '8:15'],
    methodSteps: ['Quarter to = 15 minutes before the next hour', 'Quarter to 9 = 45 minutes past 8', '8:45'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'preview_tq_03',
    topic: 'Half past',
    category: 'Time - Quarter Hours',
    difficulty: 'Easy',
    questionTemplate: 'Half past 6 means what time?',
    correctAnswerFormula: '6:30',
    wrongAnswers: ['6:15', '6:45', '7:00'],
    methodSteps: ['Half past = 30 minutes after the hour', 'Half past 6 = 6:30'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'preview_tq_04',
    topic: 'Time calculation',
    category: 'Time - Quarter Hours',
    difficulty: 'Hard',
    questionTemplate: 'It is 3:45. What time will it be in 30 minutes?',
    correctAnswerFormula: '4:15',
    wrongAnswers: ['4:45', '4:00', '3:15'],
    methodSteps: ['Start: 3:45', 'Add 15 minutes → 4:00', 'Add 15 more minutes → 4:15'],
    questionType: 'mcq',
    estimatedTimeSeconds: 30,
  },

  // ========== 3D SHAPES ==========
  {
    id: 'preview_3d_01',
    topic: 'Sphere',
    category: '3D Shapes',
    difficulty: 'Easy',
    questionTemplate: 'A ball is which 3D shape?',
    correctAnswerFormula: 'Sphere',
    wrongAnswers: ['Cube', 'Cylinder', 'Cone'],
    methodSteps: ['A sphere is perfectly round like a ball', 'It can roll in any direction'],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },
  {
    id: 'preview_3d_02',
    topic: 'Cube',
    category: '3D Shapes',
    difficulty: 'Easy',
    questionTemplate: 'A dice is which 3D shape?',
    correctAnswerFormula: 'Cube',
    wrongAnswers: ['Sphere', 'Cylinder', 'Pyramid'],
    methodSteps: ['A cube has 6 square faces', 'All faces are the same size', 'A dice is a cube'],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },
  {
    id: 'preview_3d_03',
    topic: 'Cylinder',
    category: '3D Shapes',
    difficulty: 'Easy',
    questionTemplate: 'A can (like a soup can) is which 3D shape?',
    correctAnswerFormula: 'Cylinder',
    wrongAnswers: ['Sphere', 'Cube', 'Cone'],
    methodSteps: ['A cylinder has 2 circular ends', 'It has a curved side', 'A can is a cylinder'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'preview_3d_04',
    topic: 'Cube faces',
    category: '3D Shapes',
    difficulty: 'Medium',
    questionTemplate: 'How many faces does a cube have?',
    correctAnswerFormula: '6',
    wrongAnswers: ['4', '8', '12'],
    methodSteps: ['A cube has faces on:', 'Top, bottom, front, back, left side, right side', 'Total: 6 faces'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'preview_3d_05',
    topic: 'Cone',
    category: '3D Shapes',
    difficulty: 'Medium',
    questionTemplate: 'A cone has a ___ base',
    correctAnswerFormula: 'circular',
    wrongAnswers: ['square', 'triangular', 'rectangular'],
    methodSteps: ['A cone has a circular base', 'It comes to a point at the top', 'Like an ice cream cone'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'preview_3d_06',
    topic: 'Shape properties',
    category: '3D Shapes',
    difficulty: 'Hard',
    questionTemplate: 'Which 3D shape can roll in any direction?',
    correctAnswerFormula: 'Sphere',
    wrongAnswers: ['Cube', 'Pyramid', 'Cone'],
    methodSteps: ['A sphere is perfectly round', 'It has no flat faces', 'It can roll in any direction'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },

  // ========== UNIT FRACTIONS ==========
  {
    id: 'preview_uf_01',
    topic: 'Unit fraction of amount',
    category: 'Unit Fractions',
    difficulty: 'Easy',
    questionTemplate: '1/5 of 20 = ?',
    correctAnswerFormula: '4',
    wrongAnswers: ['5', '10', '2'],
    methodSteps: ['1/5 means divide by 5', '20 ÷ 5 = 4', '1/5 of 20 = 4'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'preview_uf_02',
    topic: 'Unit fraction',
    category: 'Unit Fractions',
    difficulty: 'Medium',
    questionTemplate: '1/3 of 24 = ?',
    correctAnswerFormula: '8',
    wrongAnswers: ['6', '12', '3'],
    methodSteps: ['1/3 means divide by 3', '24 ÷ 3 = 8', '1/3 of 24 = 8'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'preview_uf_03',
    topic: 'Finding unit fractions',
    category: 'Unit Fractions',
    difficulty: 'Medium',
    questionTemplate: '1/4 of 28 = ?',
    correctAnswerFormula: '7',
    wrongAnswers: ['4', '14', '8'],
    methodSteps: ['1/4 means divide by 4', '28 ÷ 4 = 7', '1/4 of 28 = 7'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },

  // ========== NON-UNIT FRACTIONS ==========
  {
    id: 'preview_nuf_01',
    topic: 'Non-unit fractions',
    category: 'Non-Unit Fractions',
    difficulty: 'Hard',
    questionTemplate: 'Find 2/3 of 12 (find 1/3 first, then double it)',
    correctAnswerFormula: '8',
    wrongAnswers: ['6', '4', '9'],
    methodSteps: ['First find 1/3: 12 ÷ 3 = 4', 'Then multiply by 2: 4 × 2 = 8', '2/3 of 12 = 8'],
    questionType: 'mcq',
    estimatedTimeSeconds: 35,
  },
  {
    id: 'preview_nuf_02',
    topic: 'Three quarters',
    category: 'Non-Unit Fractions',
    difficulty: 'Hard',
    questionTemplate: '3/4 of 16 = ?',
    correctAnswerFormula: '12',
    wrongAnswers: ['8', '4', '16'],
    methodSteps: ['First find 1/4: 16 ÷ 4 = 4', 'Then multiply by 3: 4 × 3 = 12', '3/4 of 16 = 12'],
    questionType: 'mcq',
    estimatedTimeSeconds: 35,
  },
  {
    id: 'preview_nuf_03',
    topic: 'Two fifths',
    category: 'Non-Unit Fractions',
    difficulty: 'Hard',
    questionTemplate: 'Find 2/5 of 15',
    correctAnswerFormula: '6',
    wrongAnswers: ['3', '5', '10'],
    methodSteps: ['First find 1/5: 15 ÷ 5 = 3', 'Then multiply by 2: 3 × 2 = 6', '2/5 of 15 = 6'],
    questionType: 'mcq',
    estimatedTimeSeconds: 35,
  },

  // ========== MONEY - MAKING AMOUNTS ==========
  {
    id: 'preview_money_01',
    topic: 'Pounds to pence',
    category: 'Money - Making Amounts',
    difficulty: 'Easy',
    questionTemplate: '£1 = ___ pence',
    correctAnswerFormula: '100',
    wrongAnswers: ['10', '50', '1000'],
    methodSteps: ['1 pound = 100 pence'],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },
  {
    id: 'preview_money_02',
    topic: 'Adding coins',
    category: 'Money - Making Amounts',
    difficulty: 'Easy',
    questionTemplate: '50p + 50p = £___',
    correctAnswerFormula: '1',
    wrongAnswers: ['100', '0.50', '2'],
    methodSteps: ['50p + 50p = 100p', '100p = £1'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'preview_money_03',
    topic: 'Pounds and pence',
    category: 'Money - Making Amounts',
    difficulty: 'Medium',
    questionTemplate: '£2.50 = £2 and ___ pence',
    correctAnswerFormula: '50',
    wrongAnswers: ['5', '250', '2.5'],
    methodSteps: ['£2.50 means 2 pounds and 50 pence', 'The .50 part is 50 pence'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'preview_money_04',
    topic: 'Converting pence',
    category: 'Money - Making Amounts',
    difficulty: 'Medium',
    questionTemplate: '75p + 30p = ?',
    correctAnswerFormula: '105p or £1.05',
    wrongAnswers: ['£1.75', '85p', '£0.75'],
    methodSteps: ['75p + 30p = 105p', '105p = £1 and 5p = £1.05'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },

  // ========== MONEY - ADDITION ==========
  {
    id: 'preview_madd_01',
    topic: 'Adding pounds',
    category: 'Money - Addition',
    difficulty: 'Easy',
    questionTemplate: '£2 + £3 = ?',
    correctAnswerFormula: '£5',
    wrongAnswers: ['£6', '£4', '£23'],
    methodSteps: ['Add the pounds: 2 + 3 = 5', '£2 + £3 = £5'],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },
  {
    id: 'preview_madd_02',
    topic: 'Adding pence',
    category: 'Money - Addition',
    difficulty: 'Easy',
    questionTemplate: '50p + 30p = ?',
    correctAnswerFormula: '80p',
    wrongAnswers: ['£8', '20p', '70p'],
    methodSteps: ['Add the pence: 50 + 30 = 80', '50p + 30p = 80p'],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },
  {
    id: 'preview_madd_03',
    topic: 'Adding pounds and pence',
    category: 'Money - Addition',
    difficulty: 'Medium',
    questionTemplate: '£1.50 + £2.30 = ?',
    correctAnswerFormula: '£3.80',
    wrongAnswers: ['£3.70', '£4.80', '£3.30'],
    methodSteps: ['Add pounds: £1 + £2 = £3', 'Add pence: 50p + 30p = 80p', 'Total: £3.80'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'preview_madd_04',
    topic: 'Money addition',
    category: 'Money - Addition',
    difficulty: 'Hard',
    questionTemplate: '£3.45 + £2.85 = ?',
    correctAnswerFormula: '£6.30',
    wrongAnswers: ['£6.20', '£5.30', '£6.10'],
    methodSteps: ['Add pounds: £3 + £2 = £5', 'Add pence: 45p + 85p = 130p = £1.30', 'Total: £5 + £1.30 = £6.30'],
    questionType: 'mcq',
    estimatedTimeSeconds: 35,
  },

  // ========== LENGTH CONVERSIONS ==========
  {
    id: 'preview_len_01',
    topic: 'Meters to centimeters',
    category: 'Length Conversions',
    difficulty: 'Easy',
    questionTemplate: '1 meter = ?',
    correctAnswerFormula: '100 cm',
    wrongAnswers: ['10 cm', '1000 cm', '50 cm'],
    methodSteps: ['1 meter = 100 centimeters'],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },
  {
    id: 'preview_len_02',
    topic: 'Centimeters to millimeters',
    category: 'Length Conversions',
    difficulty: 'Easy',
    questionTemplate: '1 centimeter = ?',
    correctAnswerFormula: '10 mm',
    wrongAnswers: ['100 mm', '5 mm', '20 mm'],
    methodSteps: ['1 centimeter = 10 millimeters'],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },
  {
    id: 'preview_len_03',
    topic: 'Converting meters',
    category: 'Length Conversions',
    difficulty: 'Medium',
    questionTemplate: '2 meters = ?',
    correctAnswerFormula: '200 cm',
    wrongAnswers: ['20 cm', '2000 cm', '100 cm'],
    methodSteps: ['1 meter = 100 cm', '2 meters = 2 × 100 = 200 cm'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'preview_len_04',
    topic: 'Centimeters to meters',
    category: 'Length Conversions',
    difficulty: 'Medium',
    questionTemplate: '50 centimeters = ?',
    correctAnswerFormula: '0.5 m or 1/2 m',
    wrongAnswers: ['5 m', '0.05 m', '500 m'],
    methodSteps: ['100 cm = 1 meter', '50 cm = half a meter = 0.5 m'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'preview_len_05',
    topic: 'Mixed units',
    category: 'Length Conversions',
    difficulty: 'Hard',
    questionTemplate: '3 meters 40 centimeters = ?',
    correctAnswerFormula: '340 cm',
    wrongAnswers: ['304 cm', '3040 cm', '34 cm'],
    methodSteps: ['3 meters = 300 cm', 'Add 40 cm', '300 + 40 = 340 cm'],
    questionType: 'mcq',
    estimatedTimeSeconds: 30,
  },
  {
    id: 'preview_len_06',
    topic: 'Mixed fraction meters',
    category: 'Length Conversions',
    difficulty: 'Hard',
    questionTemplate: '1 1/2 meters = ?',
    correctAnswerFormula: '150 cm',
    wrongAnswers: ['112 cm', '152 cm', '1.5 cm'],
    methodSteps: ['1 meter = 100 cm', '1/2 meter = 50 cm', '100 + 50 = 150 cm'],
    questionType: 'mcq',
    estimatedTimeSeconds: 30,
  },
  {
    id: 'preview_len_07',
    topic: 'Quarter meter',
    category: 'Length Conversions',
    difficulty: 'Hard',
    questionTemplate: '1 1/4 meters = ?',
    correctAnswerFormula: '125 cm',
    wrongAnswers: ['114 cm', '124 cm', '140 cm'],
    methodSteps: ['1 meter = 100 cm', '1/4 meter = 25 cm', '100 + 25 = 125 cm'],
    questionType: 'mcq',
    estimatedTimeSeconds: 35,
  },
  {
    id: 'preview_len_08',
    topic: 'Three quarter meter',
    category: 'Length Conversions',
    difficulty: 'Hard',
    questionTemplate: '1 3/4 meters = ?',
    correctAnswerFormula: '175 cm',
    wrongAnswers: ['134 cm', '173 cm', '174 cm'],
    methodSteps: ['1 meter = 100 cm', '3/4 meter = 75 cm', '100 + 75 = 175 cm'],
    questionType: 'mcq',
    estimatedTimeSeconds: 35,
  },
  {
    id: 'preview_len_09',
    topic: 'Two and half meters',
    category: 'Length Conversions',
    difficulty: 'Hard',
    questionTemplate: '2 1/2 meters = ?',
    correctAnswerFormula: '250 cm',
    wrongAnswers: ['212 cm', '252 cm', '225 cm'],
    methodSteps: ['2 meters = 200 cm', '1/2 meter = 50 cm', '200 + 50 = 250 cm'],
    questionType: 'mcq',
    estimatedTimeSeconds: 30,
  },

  // ========== CAPACITY CONVERSIONS ==========
  {
    id: 'preview_cap_01',
    topic: 'Liters to milliliters',
    category: 'Capacity Conversions',
    difficulty: 'Easy',
    questionTemplate: '1 liter = ?',
    correctAnswerFormula: '1000 ml',
    wrongAnswers: ['100 ml', '10 ml', '500 ml'],
    methodSteps: ['1 liter = 1000 milliliters'],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },
  {
    id: 'preview_cap_02',
    topic: 'Half liter',
    category: 'Capacity Conversions',
    difficulty: 'Easy',
    questionTemplate: '500 ml is ___ of a liter',
    correctAnswerFormula: 'half',
    wrongAnswers: ['quarter', 'third', 'double'],
    methodSteps: ['1 liter = 1000 ml', 'Half of 1000 ml = 500 ml', '500 ml = half a liter'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'preview_cap_03',
    topic: 'Converting liters',
    category: 'Capacity Conversions',
    difficulty: 'Medium',
    questionTemplate: '2 liters = ?',
    correctAnswerFormula: '2000 ml',
    wrongAnswers: ['200 ml', '20000 ml', '1000 ml'],
    methodSteps: ['1 liter = 1000 ml', '2 liters = 2 × 1000 = 2000 ml'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'preview_cap_04',
    topic: 'Adding capacity',
    category: 'Capacity Conversions',
    difficulty: 'Medium',
    questionTemplate: '750 ml + 250 ml = ? (answer in liters)',
    correctAnswerFormula: '1 liter',
    wrongAnswers: ['0.5 liters', '2 liters', '1.5 liters'],
    methodSteps: ['750 ml + 250 ml = 1000 ml', '1000 ml = 1 liter'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'preview_cap_05',
    topic: 'Mixed units capacity',
    category: 'Capacity Conversions',
    difficulty: 'Hard',
    questionTemplate: '2 liters 300 ml = ?',
    correctAnswerFormula: '2300 ml',
    wrongAnswers: ['2030 ml', '23000 ml', '230 ml'],
    methodSteps: ['2 liters = 2000 ml', 'Add 300 ml', '2000 + 300 = 2300 ml'],
    questionType: 'mcq',
    estimatedTimeSeconds: 30,
  },
  {
    id: 'preview_cap_06',
    topic: 'Mixed fraction liters',
    category: 'Capacity Conversions',
    difficulty: 'Hard',
    questionTemplate: '1 1/2 liters = ?',
    correctAnswerFormula: '1500 ml',
    wrongAnswers: ['1050 ml', '112 ml', '1.5 ml'],
    methodSteps: ['1 liter = 1000 ml', '1/2 liter = 500 ml', '1000 + 500 = 1500 ml'],
    questionType: 'mcq',
    estimatedTimeSeconds: 30,
  },
  {
    id: 'preview_cap_07',
    topic: 'Quarter liter',
    category: 'Capacity Conversions',
    difficulty: 'Hard',
    questionTemplate: '1 1/4 liters = ?',
    correctAnswerFormula: '1250 ml',
    wrongAnswers: ['1025 ml', '1240 ml', '1125 ml'],
    methodSteps: ['1 liter = 1000 ml', '1/4 liter = 250 ml', '1000 + 250 = 1250 ml'],
    questionType: 'mcq',
    estimatedTimeSeconds: 35,
  },
  {
    id: 'preview_cap_08',
    topic: 'Three quarter liter',
    category: 'Capacity Conversions',
    difficulty: 'Hard',
    questionTemplate: '1 3/4 liters = ?',
    correctAnswerFormula: '1750 ml',
    wrongAnswers: ['1340 ml', '1730 ml', '1075 ml'],
    methodSteps: ['1 liter = 1000 ml', '3/4 liter = 750 ml', '1000 + 750 = 1750 ml'],
    questionType: 'mcq',
    estimatedTimeSeconds: 35,
  },
  {
    id: 'preview_cap_09',
    topic: 'Two and half liters',
    category: 'Capacity Conversions',
    difficulty: 'Hard',
    questionTemplate: '2 1/2 liters = ?',
    correctAnswerFormula: '2500 ml',
    wrongAnswers: ['2050 ml', '2250 ml', '2150 ml'],
    methodSteps: ['2 liters = 2000 ml', '1/2 liter = 500 ml', '2000 + 500 = 2500 ml'],
    questionType: 'mcq',
    estimatedTimeSeconds: 30,
  },
  {
    id: 'preview_cap_10',
    topic: 'Two and quarter liters',
    category: 'Capacity Conversions',
    difficulty: 'Hard',
    questionTemplate: '2 1/4 liters = ?',
    correctAnswerFormula: '2250 ml',
    wrongAnswers: ['2025 ml', '2240 ml', '2125 ml'],
    methodSteps: ['2 liters = 2000 ml', '1/4 liter = 250 ml', '2000 + 250 = 2250 ml'],
    questionType: 'mcq',
    estimatedTimeSeconds: 35,
  },

  // ========== ESTIMATING CAPACITY ==========
  {
    id: 'preview_est_01',
    topic: 'Comparing capacities',
    category: 'Estimating Capacity',
    difficulty: 'Easy',
    questionTemplate: 'Which holds more: a cup or a bucket?',
    correctAnswerFormula: 'bucket',
    wrongAnswers: ['cup', 'same amount', 'cannot tell'],
    methodSteps: ['A bucket is much larger than a cup', 'A bucket can hold many cups of water', 'Bucket holds more'],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },
  {
    id: 'preview_est_02',
    topic: 'Estimating volume',
    category: 'Estimating Capacity',
    difficulty: 'Medium',
    questionTemplate: 'A water bottle holds about ___',
    correctAnswerFormula: '500ml or 1 liter',
    wrongAnswers: ['5 liters', '100ml', '10 liters'],
    methodSteps: ['A typical water bottle holds 500ml to 1 liter', 'This is a reasonable amount to drink'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'preview_est_03',
    topic: 'Large capacities',
    category: 'Estimating Capacity',
    difficulty: 'Medium',
    questionTemplate: 'A bathtub holds about ___',
    correctAnswerFormula: '100-200 liters',
    wrongAnswers: ['10 liters', '1000 liters', '1 liter'],
    methodSteps: ['A bathtub is very large', 'It holds many buckets of water', 'About 100-200 liters'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },

  // ========== DIVISION WITH REMAINDERS ==========
  {
    id: 'preview_div_01',
    topic: 'Division with remainder',
    category: 'Division with Remainders',
    difficulty: 'Easy',
    questionTemplate: '13 ÷ 3 = ___ remainder ___',
    correctAnswerFormula: '4 remainder 1',
    wrongAnswers: ['4 remainder 2', '5 remainder 1', '3 remainder 4'],
    methodSteps: ['3 × 4 = 12', '13 - 12 = 1 left over', '13 ÷ 3 = 4 remainder 1'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'preview_div_02',
    topic: 'Division by 5',
    category: 'Division with Remainders',
    difficulty: 'Easy',
    questionTemplate: '17 ÷ 5 = ___ remainder ___',
    correctAnswerFormula: '3 remainder 2',
    wrongAnswers: ['3 remainder 1', '4 remainder 2', '2 remainder 7'],
    methodSteps: ['5 × 3 = 15', '17 - 15 = 2 left over', '17 ÷ 5 = 3 remainder 2'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'preview_div_03',
    topic: 'Division by 4',
    category: 'Division with Remainders',
    difficulty: 'Medium',
    questionTemplate: '26 ÷ 4 = ___ remainder ___',
    correctAnswerFormula: '6 remainder 2',
    wrongAnswers: ['6 remainder 0', '7 remainder 2', '6 remainder 4'],
    methodSteps: ['4 × 6 = 24', '26 - 24 = 2 left over', '26 ÷ 4 = 6 remainder 2'],
    questionType: 'mcq',
    estimatedTimeSeconds: 30,
  },
  {
    id: 'preview_div_04',
    topic: 'Division by 10',
    category: 'Division with Remainders',
    difficulty: 'Medium',
    questionTemplate: '23 ÷ 10 = ___ remainder ___',
    correctAnswerFormula: '2 remainder 3',
    wrongAnswers: ['3 remainder 2', '2 remainder 0', '1 remainder 13'],
    methodSteps: ['10 × 2 = 20', '23 - 20 = 3 left over', '23 ÷ 10 = 2 remainder 3'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'preview_div_05',
    topic: 'Larger division',
    category: 'Division with Remainders',
    difficulty: 'Hard',
    questionTemplate: '47 ÷ 5 = ___ remainder ___',
    correctAnswerFormula: '9 remainder 2',
    wrongAnswers: ['9 remainder 0', '10 remainder 2', '8 remainder 7'],
    methodSteps: ['5 × 9 = 45', '47 - 45 = 2 left over', '47 ÷ 5 = 9 remainder 2'],
    questionType: 'mcq',
    estimatedTimeSeconds: 35,
  },
  {
    id: 'preview_div_06',
    topic: 'Reverse division',
    category: 'Division with Remainders',
    difficulty: 'Hard',
    questionTemplate: 'I divide a number by 4 and get 7 remainder 2. What was the number?',
    correctAnswerFormula: '30',
    wrongAnswers: ['28', '29', '32'],
    methodSteps: ['If answer is 7, multiply: 4 × 7 = 28', 'Add the remainder: 28 + 2 = 30', 'The number was 30'],
    questionType: 'mcq',
    estimatedTimeSeconds: 35,
  },

];

export function getMathPreviewTemplates(): QuestionTemplate[] {
  return mathPreviewTemplates;
}
