import { QuestionTemplate } from '@/types/question-template';
import { scienceExamTemplates } from './science-templates-exam-based';

/**
 * COMPREHENSIVE Science Question Templates
 * 85+ questions extracted from Grade 3 Exam Papers (2020-2025)
 * All answers verified against official marking schemes
 */

export const comprehensiveScienceTemplates: QuestionTemplate[] = [
  // Import all existing verified questions first
  ...scienceExamTemplates,
  
  // ========== NUTRITION & DIET (NEW) ==========
  {
    id: 'nutrition-protein-function',
    topic: 'Nutrition',
    category: 'Nutrition and Health',
    difficulty: 'Easy',
    questionTemplate: 'Proteins are:',
    correctAnswerFormula: 'Body building food',
    wrongAnswers: ['Energy giving food', 'Protective food', 'Water'],
    methodSteps: [
      'Proteins help build and repair body tissues.',
      'They are needed for growth.',
      'Examples: meat, fish, eggs, beans.',
    ],
  },
  {
    id: 'nutrition-carbohydrate-function',
    topic: 'Nutrition',
    category: 'Nutrition and Health',
    difficulty: 'Easy',
    questionTemplate: 'Carbohydrates are:',
    correctAnswerFormula: 'Energy giving food',
    wrongAnswers: ['Body building food', 'Protective food', 'Minerals'],
    methodSteps: [
      'Carbohydrates give us energy.',
      'They help us run, play, and think.',
      'Examples: rice, bread, pasta, potatoes.',
    ],
  },
  {
    id: 'nutrition-balanced-diet',
    topic: 'Nutrition',
    category: 'Nutrition and Health',
    difficulty: 'Medium',
    questionTemplate: 'What is a balanced diet?',
    correctAnswerFormula: 'A meal that contains all the nutrients in the correct amount',
    wrongAnswers: [
      'Eating only vegetables',
      'Eating only meat',
      'Eating lots of sugar',
    ],
    methodSteps: [
      'A balanced diet includes all food groups.',
      'It has carbohydrates, proteins, fats, vitamins, and minerals.',
      'This keeps your body healthy and strong.',
    ],
  },
  {
    id: 'nutrition-less-fat-sugar',
    topic: 'Nutrition',
    category: 'Nutrition and Health',
    difficulty: 'Easy',
    questionTemplate: 'We should eat less:',
    correctAnswerFormula: 'Fat and sugar',
    wrongAnswers: [
      'Vitamins and minerals',
      'Proteins and carbohydrates',
      'Fruits and vegetables',
    ],
    methodSteps: [
      'Too much fat and sugar is unhealthy.',
      'They can cause tooth decay and obesity.',
      'Eat them in small amounts only.',
    ],
  },
  {
    id: 'nutrition-milk-complete',
    topic: 'Nutrition',
    category: 'Nutrition and Health',
    difficulty: 'Easy',
    questionTemplate: 'Is milk a complete food?',
    correctAnswerFormula: 'True',
    wrongAnswers: ['False'],
    methodSteps: [
      'Milk contains proteins, fats, carbohydrates, vitamins, and minerals.',
      'It has most nutrients needed for growth.',
      'That\'s why it\'s called a complete food.',
    ],
  },
  {
    id: 'nutrition-bread-food-group',
    topic: 'Nutrition',
    category: 'Nutrition and Health',
    difficulty: 'Easy',
    questionTemplate: 'Bread belongs to which food group?',
    correctAnswerFormula: 'Carbohydrates',
    wrongAnswers: ['Proteins', 'Vitamins', 'Fats'],
    methodSteps: [
      'Bread is made from wheat.',
      'Wheat contains lots of carbohydrates.',
      'Carbohydrates give us energy.',
    ],
  },
  {
    id: 'nutrition-chicken-food-group',
    topic: 'Nutrition',
    category: 'Nutrition and Health',
    difficulty: 'Easy',
    questionTemplate: 'Chicken belongs to which food group?',
    correctAnswerFormula: 'Proteins',
    wrongAnswers: ['Carbohydrates', 'Vitamins', 'Minerals'],
    methodSteps: [
      'Chicken is meat.',
      'Meat is rich in protein.',
      'Proteins help you grow and build muscles.',
    ],
  },
  {
    id: 'nutrition-exercise-benefit',
    topic: 'Nutrition',
    category: 'Nutrition and Health',
    difficulty: 'Medium',
    questionTemplate: 'Exercise is good for our:',
    correctAnswerFormula: 'Bones, muscles and heart',
    wrongAnswers: [
      'Only bones',
      'Only muscles',
      'Hair and nails',
    ],
    methodSteps: [
      'Exercise strengthens bones.',
      'It builds muscles and keeps them strong.',
      'It also keeps your heart healthy.',
    ],
  },
  {
    id: 'nutrition-dehydration',
    topic: 'Nutrition',
    category: 'Nutrition and Health',
    difficulty: 'Medium',
    questionTemplate: 'Lack of water will make you:',
    correctAnswerFormula: 'Dehydrated',
    wrongAnswers: ['Energetic', 'Stronger', 'Taller'],
    methodSteps: [
      'Your body needs water to function.',
      'Without enough water, you become dehydrated.',
      'Drink plenty of water every day.',
    ],
  },

  // ========== PLANTS (NEW) ==========
  {
    id: 'plants-roots-function',
    topic: 'Plants',
    category: 'Plants',
    difficulty: 'Easy',
    questionTemplate: 'Which part of the plant absorbs water and nutrients from the soil?',
    correctAnswerFormula: 'Roots',
    wrongAnswers: ['Leaves', 'Stem', 'Flowers'],
    methodSteps: [
      'Roots grow underground.',
      'They absorb water and nutrients from soil.',
      'They also hold the plant firmly in place.',
    ],
  },
  {
    id: 'plants-flower-function',
    topic: 'Plants',
    category: 'Plants',
    difficulty: 'Easy',
    questionTemplate: 'Which part of the plant makes seeds?',
    correctAnswerFormula: 'Flower',
    wrongAnswers: ['Roots', 'Stem', 'Leaves'],
    methodSteps: [
      'Flowers produce seeds.',
      'Seeds help the plant reproduce.',
      'New plants grow from seeds.',
    ],
  },
  {
    id: 'plants-leaves-function',
    topic: 'Plants',
    category: 'Plants',
    difficulty: 'Medium',
    questionTemplate: 'Which part of the plant makes most of the food?',
    correctAnswerFormula: 'Leaves',
    wrongAnswers: ['Roots', 'Stem', 'Flowers'],
    methodSteps: [
      'Leaves make food using sunlight.',
      'This process is called photosynthesis.',
      'They use water, air, and sunlight to make food.',
    ],
  },
  {
    id: 'plants-stem-function',
    topic: 'Plants',
    category: 'Plants',
    difficulty: 'Medium',
    questionTemplate: 'What does the stem do?',
    correctAnswerFormula: 'Holds up leaves and flowers',
    wrongAnswers: [
      'Absorbs water from soil',
      'Makes seeds',
      'Stores all the food',
    ],
    methodSteps: [
      'The stem supports the plant.',
      'It holds leaves and flowers up towards sunlight.',
      'It also transports water and nutrients.',
    ],
  },
  {
    id: 'plants-need-light',
    topic: 'Plants',
    category: 'Plants',
    difficulty: 'Easy',
    questionTemplate: 'All plants need _____ to grow and keep their stems and leaves healthy.',
    correctAnswerFormula: 'Light',
    wrongAnswers: ['Darkness', 'Salt', 'Plastic'],
    methodSteps: [
      'Plants need light to make food.',
      'Without light, plants cannot survive.',
      'They use sunlight for photosynthesis.',
    ],
  },
  {
    id: 'plants-no-water',
    topic: 'Plants',
    category: 'Plants',
    difficulty: 'Easy',
    questionTemplate: 'If a plant is not given water, it will:',
    correctAnswerFormula: 'Wilt',
    wrongAnswers: ['Grow', 'Flower', 'Become taller'],
    methodSteps: [
      'Plants need water to survive.',
      'Without water, they dry out and wilt.',
      'Wilting means drooping and dying.',
    ],
  },
  {
    id: 'plants-photosynthesis-needs',
    topic: 'Plants',
    category: 'Plants',
    difficulty: 'Hard',
    questionTemplate: 'What three things do plants need to make food?',
    correctAnswerFormula: 'Water, sunlight, and air (carbon dioxide)',
    wrongAnswers: [
      'Water, soil, and darkness',
      'Only water',
      'Fertilizer, salt, and heat',
    ],
    methodSteps: [
      'Plants make food through photosynthesis.',
      'They need: water (from roots), sunlight (energy), and air (carbon dioxide).',
      'They produce oxygen as a byproduct.',
    ],
  },
  {
    id: 'plants-best-temperature',
    topic: 'Plants',
    category: 'Plants',
    difficulty: 'Medium',
    questionTemplate: 'What is the best temperature for plants to grow?',
    correctAnswerFormula: 'Warm temperature',
    wrongAnswers: ['Very cold', 'Freezing', 'Extremely hot'],
    methodSteps: [
      'Most plants grow best in warm conditions.',
      'Too cold or too hot can harm plants.',
      'Warm temperature helps plant processes work well.',
    ],
  },
  {
    id: 'plants-rainforest-grow-well',
    topic: 'Plants',
    category: 'Plants',
    difficulty: 'Medium',
    questionTemplate: 'Why do plants in the rainforest grow well?',
    correctAnswerFormula: 'They get plenty of water, warmth, and sunlight',
    wrongAnswers: [
      'Because it\'s very cold',
      'Because there\'s no rain',
      'Because it\'s dark',
    ],
    methodSteps: [
      'Rainforests have lots of rain (water).',
      'They are warm all year.',
      'Trees get plenty of sunlight at the top.',
    ],
  },

  // ========== FORCES & MAGNETS (NEW) ==========
  {
    id: 'forces-definition',
    topic: 'Forces',
    category: 'Forces and Motion',
    difficulty: 'Easy',
    questionTemplate: 'Push and pull are examples of:',
    correctAnswerFormula: 'A force',
    wrongAnswers: ['Energy', 'Light', 'Sound'],
    methodSteps: [
      'A force is a push or a pull.',
      'Forces can make things move, stop, or change direction.',
      'Examples: pushing a door, pulling a rope.',
    ],
  },
  {
    id: 'forces-change-direction',
    topic: 'Forces',
    category: 'Forces and Motion',
    difficulty: 'Easy',
    questionTemplate: 'Football players use force to change the _____ of the ball.',
    correctAnswerFormula: 'Direction',
    wrongAnswers: ['Color', 'Size', 'Weight'],
    methodSteps: [
      'When you kick a ball, you apply force.',
      'This force changes where the ball goes.',
      'Direction means which way something moves.',
    ],
  },
  {
    id: 'forces-start-moving',
    topic: 'Forces',
    category: 'Forces and Motion',
    difficulty: 'Medium',
    questionTemplate: 'Forces can _____ things and stop things from moving.',
    correctAnswerFormula: 'Start',
    wrongAnswers: ['Melt', 'Freeze', 'Hide'],
    methodSteps: [
      'Forces make stationary objects move.',
      'Forces can also stop moving objects.',
      'Without force, things stay as they are.',
    ],
  },
  {
    id: 'forces-change-speed',
    topic: 'Forces',
    category: 'Forces and Motion',
    difficulty: 'Medium',
    questionTemplate: 'We can use force to make things move:',
    correctAnswerFormula: 'Faster',
    wrongAnswers: ['Lighter', 'Heavier', 'Smaller'],
    methodSteps: [
      'More force makes things speed up.',
      'Less force makes things slow down.',
      'The size of the force affects speed.',
    ],
  },
  {
    id: 'forces-change-shape',
    topic: 'Forces',
    category: 'Forces and Motion',
    difficulty: 'Medium',
    questionTemplate: 'Potters and carpenters use force to change the _____ of materials.',
    correctAnswerFormula: 'Shape',
    wrongAnswers: ['Color', 'Temperature', 'Smell'],
    methodSteps: [
      'Forces can change the shape of objects.',
      'Potters mold clay into different shapes.',
      'Carpenters bend and cut wood.',
    ],
  },
  {
    id: 'magnets-attract-repel-NS',
    topic: 'Forces',
    category: 'Forces and Motion',
    difficulty: 'Medium',
    questionTemplate: 'What happens when the N pole of one magnet faces the S pole of another?',
    correctAnswerFormula: 'They attract',
    wrongAnswers: ['They repel', 'Nothing happens', 'They break'],
    methodSteps: [
      'Opposite poles attract each other.',
      'N (North) and S (South) are opposite poles.',
      'When N faces S, they pull together.',
    ],
  },
  {
    id: 'magnets-repel-NN',
    topic: 'Forces',
    category: 'Forces and Motion',
    difficulty: 'Medium',
    questionTemplate: 'What happens when the N pole of one magnet faces the N pole of another?',
    correctAnswerFormula: 'They repel',
    wrongAnswers: ['They attract', 'Nothing happens', 'They stick'],
    methodSteps: [
      'Same poles repel each other.',
      'N (North) and N (North) are the same.',
      'They push away from each other.',
    ],
  },
  {
    id: 'magnets-repel-SS',
    topic: 'Forces',
    category: 'Forces and Motion',
    difficulty: 'Medium',
    questionTemplate: 'What happens when the S pole of one magnet faces the S pole of another?',
    correctAnswerFormula: 'They repel',
    wrongAnswers: ['They attract', 'Nothing happens', 'They combine'],
    methodSteps: [
      'Same poles repel each other.',
      'S (South) and S (South) are the same.',
      'They push away from each other.',
    ],
  },
  {
    id: 'magnets-unit-force',
    topic: 'Forces',
    category: 'Forces and Motion',
    difficulty: 'Hard',
    questionTemplate: 'What is the unit of measurement of force?',
    correctAnswerFormula: 'Newton (N)',
    wrongAnswers: ['Meter (m)', 'Kilogram (kg)', 'Second (s)'],
    methodSteps: [
      'Force is measured in Newtons.',
      'The symbol is N.',
      'Named after scientist Isaac Newton.',
    ],
  },

  // ========== MATERIALS (NEW) ==========
  {
    id: 'materials-iron-nail-magnetic',
    topic: 'Materials',
    category: 'Materials',
    difficulty: 'Easy',
    questionTemplate: 'Is an iron nail magnetic or non-magnetic?',
    correctAnswerFormula: 'Magnetic',
    wrongAnswers: ['Non-magnetic', 'Both', 'Neither'],
    methodSteps: [
      'Iron is a magnetic material.',
      'Magnets attract iron objects.',
      'An iron nail will stick to a magnet.',
    ],
  },
  {
    id: 'materials-plastic-bottle-magnetic',
    topic: 'Materials',
    category: 'Materials',
    difficulty: 'Easy',
    questionTemplate: 'Is a plastic bottle magnetic or non-magnetic?',
    correctAnswerFormula: 'Non-magnetic',
    wrongAnswers: ['Magnetic', 'Sometimes magnetic', 'Depends on color'],
    methodSteps: [
      'Plastic is not a magnetic material.',
      'Magnets do not attract plastic.',
      'A plastic bottle will not stick to a magnet.',
    ],
  },
  {
    id: 'materials-flexible-strong',
    topic: 'Materials',
    category: 'Materials',
    difficulty: 'Medium',
    questionTemplate: 'Which material can be both flexible and strong?',
    correctAnswerFormula: 'Copper wire',
    wrongAnswers: ['Brick', 'Glass', 'Paper'],
    methodSteps: [
      'Flexible means it can bend without breaking.',
      'Strong means it doesn\'t break easily.',
      'Copper wire can bend and is also strong.',
    ],
  },

  // ========== HUMAN BODY - Additional (NEW) ==========
  {
    id: 'human-fingerprints-unique',
    topic: 'Human Body',
    category: 'Human Body',
    difficulty: 'Medium',
    questionTemplate: 'Do all humans have similar fingerprints?',
    correctAnswerFormula: 'False',
    wrongAnswers: ['True'],
    methodSteps: [
      'Every person has unique fingerprints.',
      'No two people have the same fingerprints.',
      'Even identical twins have different fingerprints.',
    ],
  },
  {
    id: 'human-eyes-see-distance',
    topic: 'Human Body',
    category: 'Human Body',
    difficulty: 'Easy',
    questionTemplate: 'Can our eyes see things closer and further away?',
    correctAnswerFormula: 'True',
    wrongAnswers: ['False'],
    methodSteps: [
      'Our eyes can focus on objects at different distances.',
      'We can see things right in front of us.',
      'We can also see things far away.',
    ],
  },

  // ========== ANIMALS - Additional (NEW) ==========
  {
    id: 'animals-bears-sense-smell',
    topic: 'Animals',
    category: 'Animals',
    difficulty: 'Medium',
    questionTemplate: 'Bears have a very good sense of:',
    correctAnswerFormula: 'Smell',
    wrongAnswers: ['Sight', 'Taste', 'Hearing'],
    methodSteps: [
      'Bears have one of the best senses of smell.',
      'They can smell food from miles away.',
      'This helps them find food and detect danger.',
    ],
  },
  {
    id: 'animals-mammals-reproduce',
    topic: 'Animals',
    category: 'Animals',
    difficulty: 'Medium',
    questionTemplate: 'Do mammals lay eggs to have their young ones?',
    correctAnswerFormula: 'False',
    wrongAnswers: ['True'],
    methodSteps: [
      'Most mammals give birth to live young.',
      'They do not lay eggs.',
      'Exception: platypus and echidna are egg-laying mammals.',
    ],
  },

  // ========== FOOD CHAINS - Additional (NEW) ==========
  {
    id: 'food-chain-grass-snake',
    topic: 'Food Chains',
    category: 'Food Chains',
    difficulty: 'Hard',
    questionTemplate: 'In the food chain: grass → grasshopper → frog → snake, which is the producer?',
    correctAnswerFormula: 'Grass',
    wrongAnswers: ['Grasshopper', 'Frog', 'Snake'],
    methodSteps: [
      'Producers make their own food.',
      'Grass is a plant - it makes food using sunlight.',
      'All other organisms in the chain are consumers.',
    ],
  },
  {
    id: 'food-chain-grass-snake-predator',
    topic: 'Food Chains',
    category: 'Food Chains',
    difficulty: 'Medium',
    questionTemplate: 'In the food chain: grass → grasshopper → frog → snake, which are predators?',
    correctAnswerFormula: 'Frog and snake',
    wrongAnswers: [
      'Grass and grasshopper',
      'Only snake',
      'Only grasshopper',
    ],
    methodSteps: [
      'Predators hunt and eat other animals.',
      'The frog hunts grasshoppers.',
      'The snake hunts frogs.',
    ],
  },
  {
    id: 'food-chain-grass-snake-prey',
    topic: 'Food Chains',
    category: 'Food Chains',
    difficulty: 'Medium',
    questionTemplate: 'In the food chain: grass → grasshopper → frog → snake, which are prey?',
    correctAnswerFormula: 'Grasshopper and frog',
    wrongAnswers: [
      'Grass and snake',
      'Only frog',
      'Only snake',
    ],
    methodSteps: [
      'Prey are animals that are hunted.',
      'The grasshopper is eaten by the frog.',
      'The frog is eaten by the snake.',
    ],
  },
  {
    id: 'food-chain-grass-snake-carnivore',
    topic: 'Food Chains',
    category: 'Food Chains',
    difficulty: 'Medium',
    questionTemplate: 'In the food chain: grass → grasshopper → frog → snake, which are carnivores?',
    correctAnswerFormula: 'Frog and snake',
    wrongAnswers: [
      'Grass and grasshopper',
      'Only grasshopper',
      'All of them',
    ],
    methodSteps: [
      'Carnivores eat only meat (other animals).',
      'Frogs eat insects like grasshoppers.',
      'Snakes eat animals like frogs.',
    ],
  },

  // ========== ADDITIONAL MATERIALS QUESTIONS ==========
  {
    id: 'materials-glass-properties',
    topic: 'Materials',
    category: 'Materials',
    difficulty: 'Easy',
    questionTemplate: 'Which material is transparent and smooth?',
    correctAnswerFormula: 'Glass',
    wrongAnswers: ['Wood', 'Metal', 'Fabric'],
    methodSteps: [
      'Transparent means you can see through it.',
      'Glass is transparent and has a smooth surface.',
      'This makes it perfect for windows and lenses.',
    ],
  },
  {
    id: 'materials-metal-properties',
    topic: 'Materials',
    category: 'Materials',
    difficulty: 'Easy',
    questionTemplate: 'Which material is sharp and does not burn?',
    correctAnswerFormula: 'Metal',
    wrongAnswers: ['Paper', 'Wood', 'Plastic'],
    methodSteps: [
      'Metals like steel can be made very sharp.',
      'Metals do not burn easily.',
      'This makes them good for knives and tools.',
    ],
  },
  {
    id: 'materials-rubber-properties',
    topic: 'Materials',
    category: 'Materials',
    difficulty: 'Medium',
    questionTemplate: 'Which material is stretchable and waterproof?',
    correctAnswerFormula: 'Rubber',
    wrongAnswers: ['Cotton', 'Paper', 'Wood'],
    methodSteps: [
      'Rubber can stretch and return to its shape.',
      'It is also waterproof.',
      'This makes it good for tires and raincoats.',
    ],
  },
  {
    id: 'materials-plastic-properties',
    topic: 'Materials',
    category: 'Materials',
    difficulty: 'Easy',
    questionTemplate: 'Which material is waterproof and colorful?',
    correctAnswerFormula: 'Plastic',
    wrongAnswers: ['Paper', 'Fabric', 'Wood'],
    methodSteps: [
      'Plastic does not absorb water.',
      'It can be made in many colors.',
      'This makes it good for toys and containers.',
    ],
  },
  {
    id: 'materials-wood-strong',
    topic: 'Materials',
    category: 'Materials',
    difficulty: 'Easy',
    questionTemplate: 'Which material is strong and rigid?',
    correctAnswerFormula: 'Wood',
    wrongAnswers: ['Paper', 'Fabric', 'Sponge'],
    methodSteps: [
      'Wood is hard and does not bend easily.',
      'Rigid means it keeps its shape.',
      'This makes wood good for furniture and buildings.',
    ],
  },
  {
    id: 'materials-fabric-absorbent',
    topic: 'Materials',
    category: 'Materials',
    difficulty: 'Easy',
    questionTemplate: 'Which material is soft and absorbent?',
    correctAnswerFormula: 'Fabric (cotton)',
    wrongAnswers: ['Metal', 'Glass', 'Plastic'],
    methodSteps: [
      'Fabric like cotton is soft to touch.',
      'Absorbent means it can soak up water.',
      'This makes fabric good for towels and clothes.',
    ],
  },
  {
    id: 'materials-glass-windows',
    topic: 'Materials',
    category: 'Materials',
    difficulty: 'Easy',
    questionTemplate: 'Is glass a good material to make windows?',
    correctAnswerFormula: 'True',
    wrongAnswers: ['False'],
    methodSteps: [
      'Glass is transparent - you can see through it.',
      'It lets light in.',
      'This makes it perfect for windows.',
    ],
  },
  {
    id: 'materials-steel-bridges',
    topic: 'Materials',
    category: 'Materials',
    difficulty: 'Medium',
    questionTemplate: 'Is steel a good material to make strong bridges?',
    correctAnswerFormula: 'True',
    wrongAnswers: ['False'],
    methodSteps: [
      'Steel is very strong.',
      'It can support heavy weights.',
      'This makes it excellent for bridges and buildings.',
    ],
  },
  {
    id: 'materials-paper-towel-absorbent',
    topic: 'Materials',
    category: 'Materials',
    difficulty: 'Easy',
    questionTemplate: 'Does paper towel absorb water?',
    correctAnswerFormula: 'True',
    wrongAnswers: ['False'],
    methodSteps: [
      'Paper towel is designed to soak up water.',
      'It is made from absorbent materials.',
      'This is why we use it to clean up spills.',
    ],
  },
  {
    id: 'materials-plastic-absorbent',
    topic: 'Materials',
    category: 'Materials',
    difficulty: 'Easy',
    questionTemplate: 'Is plastic an absorbent material?',
    correctAnswerFormula: 'False',
    wrongAnswers: ['True'],
    methodSteps: [
      'Plastic is waterproof.',
      'It does not soak up water.',
      'This is why plastic bags keep things dry.',
    ],
  },
  {
    id: 'materials-unlike-poles',
    topic: 'Materials',
    category: 'Materials',
    difficulty: 'Medium',
    questionTemplate: 'Unlike poles of two bar magnets _____ each other.',
    correctAnswerFormula: 'Attract',
    wrongAnswers: ['Repel', 'Ignore', 'Break'],
    methodSteps: [
      'Unlike poles are opposite poles (N and S).',
      'Opposite poles attract (pull together).',
      'Like poles repel (push apart).',
    ],
  },
  {
    id: 'materials-forcemeter-measures',
    topic: 'Materials',
    category: 'Materials',
    difficulty: 'Medium',
    questionTemplate: 'What does a forcemeter measure?',
    correctAnswerFormula: 'The size of pulls',
    wrongAnswers: ['Temperature', 'Weight', 'Time'],
    methodSteps: [
      'A forcemeter measures force.',
      'Force is measured in Newtons (N).',
      'It shows how strong a push or pull is.',
    ],
  },
  {
    id: 'materials-metal-pans',
    topic: 'Materials',
    category: 'Materials',
    difficulty: 'Easy',
    questionTemplate: 'Which material is good for making pans?',
    correctAnswerFormula: 'Metal',
    wrongAnswers: ['Plastic', 'Paper', 'Fabric'],
    methodSteps: [
      'Metal can withstand high heat.',
      'It conducts heat well for cooking.',
      'Plastic would melt at high temperatures.',
    ],
  },
  {
    id: 'materials-waterproof-smooth',
    topic: 'Materials',
    category: 'Materials',
    difficulty: 'Medium',
    questionTemplate: 'Plastic and glass are both:',
    correctAnswerFormula: 'Waterproof',
    wrongAnswers: ['Absorbent', 'Magnetic', 'Soft'],
    methodSteps: [
      'Both plastic and glass do not absorb water.',
      'Water stays on their surface.',
      'This property is called waterproof.',
    ],
  },
  {
    id: 'materials-glass-surface',
    topic: 'Materials',
    category: 'Materials',
    difficulty: 'Easy',
    questionTemplate: 'Glass has a _____ surface.',
    correctAnswerFormula: 'Smooth',
    wrongAnswers: ['Rough', 'Bumpy', 'Sharp'],
    methodSteps: [
      'Glass feels smooth to touch.',
      'Smooth surfaces have less friction.',
      'This is why glass is slippery.',
    ],
  },

  // ========== ADDITIONAL NUTRITION QUESTIONS ==========
  {
    id: 'nutrition-vitamins-minerals-function',
    topic: 'Nutrition',
    category: 'Nutrition and Health',
    difficulty: 'Easy',
    questionTemplate: 'What food group keeps your body healthy?',
    correctAnswerFormula: 'Vitamins and minerals',
    wrongAnswers: ['Fat and sugar', 'Carbohydrates only', 'Proteins only'],
    methodSteps: [
      'Vitamins and minerals protect your body.',
      'They help you fight diseases.',
      'Found in fruits and vegetables.',
    ],
  },
  {
    id: 'nutrition-bones-teeth',
    topic: 'Nutrition',
    category: 'Nutrition and Health',
    difficulty: 'Medium',
    questionTemplate: 'Which food group keeps your bones and teeth strong?',
    correctAnswerFormula: 'Proteins (and calcium)',
    wrongAnswers: ['Fat and sugar', 'Carbohydrates only', 'Vitamins only'],
    methodSteps: [
      'Proteins help build strong bones.',
      'Calcium (found in milk) also strengthens bones and teeth.',
      'Eat dairy products and protein-rich foods.',
    ],
  },
  {
    id: 'nutrition-fruit-juice-sugar',
    topic: 'Nutrition',
    category: 'Nutrition and Health',
    difficulty: 'Medium',
    questionTemplate: 'Fruit juice has _____ sugar in it.',
    correctAnswerFormula: 'Natural',
    wrongAnswers: ['Added', 'No', 'Artificial'],
    methodSteps: [
      'Fruits naturally contain sugar.',
      'This sugar is called fructose.',
      'Natural sugar is healthier than added sugar.',
    ],
  },
  {
    id: 'nutrition-eating-too-much',
    topic: 'Nutrition',
    category: 'Nutrition and Health',
    difficulty: 'Easy',
    questionTemplate: 'Eating too much food makes you:',
    correctAnswerFormula: 'Overweight',
    wrongAnswers: ['Thin', 'Taller', 'Smarter'],
    methodSteps: [
      'Too much food means extra calories.',
      'Extra calories are stored as fat.',
      'This leads to being overweight.',
    ],
  },
  {
    id: 'nutrition-ruler-measure-height',
    topic: 'Nutrition',
    category: 'Nutrition and Health',
    difficulty: 'Easy',
    questionTemplate: 'What do we use to measure the height of plants?',
    correctAnswerFormula: 'Ruler',
    wrongAnswers: ['Thermometer', 'Clock', 'Scale'],
    methodSteps: [
      'A ruler measures length or height.',
      'It shows measurements in cm or m.',
      'A thermometer measures temperature, not height.',
    ],
  },
  {
    id: 'nutrition-too-much-sugar',
    topic: 'Nutrition',
    category: 'Nutrition and Health',
    difficulty: 'Easy',
    questionTemplate: 'Eating too much sugar harms our:',
    correctAnswerFormula: 'Teeth',
    wrongAnswers: ['Hair', 'Nails', 'Skin'],
    methodSteps: [
      'Sugar sticks to teeth.',
      'Bacteria eat sugar and produce acid.',
      'Acid damages teeth causing cavities.',
    ],
  },
  {
    id: 'nutrition-butter-added-salt',
    topic: 'Nutrition',
    category: 'Nutrition and Health',
    difficulty: 'Medium',
    questionTemplate: 'Which food has added salt in it?',
    correctAnswerFormula: 'Butter',
    wrongAnswers: ['Rice', 'Fruits', 'Plain water'],
    methodSteps: [
      'Butter is processed food.',
      'Salt is added to butter for flavor and preservation.',
      'Plain foods like rice have no added salt.',
    ],
  },
  {
    id: 'nutrition-fat-salt-harmful',
    topic: 'Nutrition',
    category: 'Nutrition and Health',
    difficulty: 'Medium',
    questionTemplate: 'Too much fat and salt are bad for our:',
    correctAnswerFormula: 'Heart and circulatory system',
    wrongAnswers: ['Bones', 'Hair', 'Eyes'],
    methodSteps: [
      'Too much fat clogs blood vessels.',
      'Too much salt raises blood pressure.',
      'Both harm the heart and circulation.',
    ],
  },
  {
    id: 'nutrition-unhealthy-diet',
    topic: 'Nutrition',
    category: 'Nutrition and Health',
    difficulty: 'Easy',
    questionTemplate: 'Sugary food, drinks and fatty food make the diet:',
    correctAnswerFormula: 'Unhealthy',
    wrongAnswers: ['Healthy', 'Balanced', 'Perfect'],
    methodSteps: [
      'Too much sugar and fat is bad for you.',
      'They provide little nutrition.',
      'A healthy diet has less sugar and fat.',
    ],
  },

  // ========== ADDITIONAL PLANTS QUESTIONS ==========
  {
    id: 'plants-four-parts',
    topic: 'Plants',
    category: 'Plants',
    difficulty: 'Easy',
    questionTemplate: 'Most plants have _____ main parts.',
    correctAnswerFormula: 'Four',
    wrongAnswers: ['Three', 'Five', 'Six'],
    methodSteps: [
      'The four main parts are: roots, stem, leaves, and flowers.',
      'Not all plants have all parts.',
      'But most flowering plants have these four.',
    ],
  },
  {
    id: 'plants-stem-transports',
    topic: 'Plants',
    category: 'Plants',
    difficulty: 'Easy',
    questionTemplate: 'Which part transports water around the plant?',
    correctAnswerFormula: 'Stem',
    wrongAnswers: ['Roots', 'Leaves', 'Flowers'],
    methodSteps: [
      'The stem carries water from roots to leaves.',
      'It also carries food made in leaves to other parts.',
      'The stem acts like a pipeline.',
    ],
  },
  {
    id: 'plants-rainforest-growth',
    topic: 'Plants',
    category: 'Plants',
    difficulty: 'Medium',
    questionTemplate: 'In which environment is there warmth and plenty of water for plants to grow?',
    correctAnswerFormula: 'Rainforest',
    wrongAnswers: ['Desert', 'Arctic', 'Mountains'],
    methodSteps: [
      'Rainforests are warm and receive lots of rain.',
      'These are ideal conditions for plant growth.',
      'Many plants thrive in rainforests.',
    ],
  },
  {
    id: 'plants-sunlight-make-food',
    topic: 'Plants',
    category: 'Plants',
    difficulty: 'Medium',
    questionTemplate: 'Plants make food in the green parts using:',
    correctAnswerFormula: 'Sunlight, water, and carbon dioxide',
    wrongAnswers: [
      'Only sunlight',
      'Only water',
      'Darkness and soil',
    ],
    methodSteps: [
      'Plants make food through photosynthesis.',
      'They need: sunlight (energy), water (from roots), air (CO2).',
      'This produces sugar (food) and oxygen.',
    ],
  },
  {
    id: 'plants-move-sunlight',
    topic: 'Plants',
    category: 'Plants',
    difficulty: 'Medium',
    questionTemplate: 'Plants move towards:',
    correctAnswerFormula: 'Sunlight',
    wrongAnswers: ['Darkness', 'Water only', 'Cold'],
    methodSteps: [
      'Plants need sunlight to make food.',
      'They grow towards the light source.',
      'This movement is called phototropism.',
    ],
  },
  {
    id: 'plants-too-hot-cold',
    topic: 'Plants',
    category: 'Plants',
    difficulty: 'Medium',
    questionTemplate: 'What happens to a plant if it gets too hot or too cold?',
    correctAnswerFormula: 'It will die',
    wrongAnswers: ['It will grow faster', 'Nothing happens', 'It will flower more'],
    methodSteps: [
      'Extreme temperatures harm plants.',
      'Too hot: the plant dries out.',
      'Too cold: the plant freezes and dies.',
    ],
  },
  {
    id: 'plants-no-light-yellow',
    topic: 'Plants',
    category: 'Plants',
    difficulty: 'Hard',
    questionTemplate: 'Why do leaves turn yellow when a plant is kept in darkness?',
    correctAnswerFormula: 'There is no sunlight to make food',
    wrongAnswers: [
      'The plant has too much water',
      'The plant is too cold',
      'The plant is growing',
    ],
    methodSteps: [
      'Plants need light to make food (photosynthesis).',
      'Without light, they cannot produce chlorophyll (green pigment).',
      'Leaves turn yellow and the plant becomes weak.',
    ],
  },
  {
    id: 'plants-potato-energy',
    topic: 'Plants',
    category: 'Plants',
    difficulty: 'Easy',
    questionTemplate: 'Is potato an energy giving food?',
    correctAnswerFormula: 'True',
    wrongAnswers: ['False'],
    methodSteps: [
      'Potatoes are rich in carbohydrates.',
      'Carbohydrates provide energy.',
      'That\'s why potatoes are energy-giving food.',
    ],
  },

  // ========== ADDITIONAL FORCES QUESTIONS ==========
  {
    id: 'forces-friction-definition',
    topic: 'Forces',
    category: 'Forces and Motion',
    difficulty: 'Medium',
    questionTemplate: 'What is the force that acts when two surfaces rub together?',
    correctAnswerFormula: 'Friction',
    wrongAnswers: ['Magnetism', 'Gravity', 'Electricity'],
    methodSteps: [
      'Friction is a force that opposes motion.',
      'It occurs when surfaces slide against each other.',
      'Rough surfaces create more friction.',
    ],
  },
  {
    id: 'forces-magnets-poles',
    topic: 'Forces',
    category: 'Forces and Motion',
    difficulty: 'Easy',
    questionTemplate: 'Magnets have _____ poles.',
    correctAnswerFormula: 'Two',
    wrongAnswers: ['One', 'Three', 'Four'],
    methodSteps: [
      'Every magnet has two poles.',
      'The poles are called North (N) and South (S).',
      'Magnetic force is strongest at the poles.',
    ],
  },
  {
    id: 'forces-newton-unit',
    topic: 'Forces',
    category: 'Forces and Motion',
    difficulty: 'Medium',
    questionTemplate: 'Newton is the unit of measurement of:',
    correctAnswerFormula: 'Force',
    wrongAnswers: ['Weight', 'Temperature', 'Distance'],
    methodSteps: [
      'Force is measured in Newtons.',
      'The symbol is N.',
      'Named after scientist Isaac Newton.',
    ],
  },
  {
    id: 'forces-is-push-pull',
    topic: 'Forces',
    category: 'Forces and Motion',
    difficulty: 'Easy',
    questionTemplate: 'Force is:',
    correctAnswerFormula: 'A push or a pull',
    wrongAnswers: ['Only a push', 'Only a pull', 'Heat'],
    methodSteps: [
      'A force can be a push (moving away).',
      'A force can be a pull (bringing closer).',
      'Both are types of forces.',
    ],
  },
  {
    id: 'forces-what-can-do',
    topic: 'Forces',
    category: 'Forces and Motion',
    difficulty: 'Medium',
    questionTemplate: 'What can forces do?',
    correctAnswerFormula: 'Start, stop, and change direction of moving objects',
    wrongAnswers: [
      'Only start movement',
      'Only stop movement',
      'Make things disappear',
    ],
    methodSteps: [
      'Forces can start things moving.',
      'Forces can stop moving things.',
      'Forces can change direction, speed, and shape.',
    ],
  },
  {
    id: 'forces-friction-rough',
    topic: 'Forces',
    category: 'Forces and Motion',
    difficulty: 'Hard',
    questionTemplate: 'Why does grass create more friction than glass?',
    correctAnswerFormula: 'Grass has a rough surface',
    wrongAnswers: [
      'Grass is green',
      'Grass is soft',
      'Grass is wet',
    ],
    methodSteps: [
      'Friction depends on surface texture.',
      'Rough surfaces (like grass) create more friction.',
      'Smooth surfaces (like glass) create less friction.',
    ],
  },
  {
    id: 'forces-pull-actions',
    topic: 'Forces',
    category: 'Forces and Motion',
    difficulty: 'Easy',
    questionTemplate: 'Drawing a bucket of water from a well is an example of:',
    correctAnswerFormula: 'Pull',
    wrongAnswers: ['Push', 'Twist', 'Squeeze'],
    methodSteps: [
      'You pull the rope to lift the bucket.',
      'Pull means bringing something towards you.',
      'This is an upward pulling force.',
    ],
  },
  {
    id: 'forces-push-actions',
    topic: 'Forces',
    category: 'Forces and Motion',
    difficulty: 'Easy',
    questionTemplate: 'Kicking a ball is an example of:',
    correctAnswerFormula: 'Push',
    wrongAnswers: ['Pull', 'Twist', 'Bend'],
    methodSteps: [
      'You push the ball away with your foot.',
      'Push means moving something away from you.',
      'This makes the ball move forward.',
    ],
  },

  // ========== ADDITIONAL ANIMALS QUESTIONS ==========
  {
    id: 'animals-fish-movement',
    topic: 'Animals',
    category: 'Animals',
    difficulty: 'Easy',
    questionTemplate: 'How do fish move?',
    correctAnswerFormula: 'Swim',
    wrongAnswers: ['Fly', 'Walk', 'Slither'],
    methodSteps: [
      'Fish live in water.',
      'They have fins to help them swim.',
      'They move through water by swimming.',
    ],
  },
  {
    id: 'animals-snake-movement',
    topic: 'Animals',
    category: 'Animals',
    difficulty: 'Easy',
    questionTemplate: 'How do snakes move?',
    correctAnswerFormula: 'Slither',
    wrongAnswers: ['Walk', 'Fly', 'Jump'],
    methodSteps: [
      'Snakes have no legs.',
      'They slide along the ground.',
      'This movement is called slithering.',
    ],
  },
  {
    id: 'animals-frog-movement',
    topic: 'Animals',
    category: 'Animals',
    difficulty: 'Easy',
    questionTemplate: 'How do frogs move on land?',
    correctAnswerFormula: 'Jump',
    wrongAnswers: ['Fly', 'Slither', 'Roll'],
    methodSteps: [
      'Frogs have strong back legs.',
      'They use their legs to jump.',
      'They can also swim in water.',
    ],
  },
  {
    id: 'animals-scales',
    topic: 'Animals',
    category: 'Animals',
    difficulty: 'Easy',
    questionTemplate: 'Which animals have scales on their body?',
    correctAnswerFormula: 'Fish and snakes',
    wrongAnswers: [
      'Birds and mammals',
      'Only insects',
      'Frogs and toads',
    ],
    methodSteps: [
      'Scales are hard, overlapping plates.',
      'Fish have scales to protect their body.',
      'Reptiles like snakes also have scales.',
    ],
  },
  {
    id: 'animals-egg-laying',
    topic: 'Animals',
    category: 'Animals',
    difficulty: 'Medium',
    questionTemplate: 'Which animals lay eggs to reproduce?',
    correctAnswerFormula: 'Birds, fish, and butterflies',
    wrongAnswers: [
      'Cows and elephants',
      'Lions and tigers',
      'Rabbits and rats',
    ],
    methodSteps: [
      'Birds lay eggs in nests.',
      'Fish lay eggs in water.',
      'Insects like butterflies also lay eggs.',
    ],
  },
  {
    id: 'animals-give-birth',
    topic: 'Animals',
    category: 'Animals',
    difficulty: 'Medium',
    questionTemplate: 'Which animals give birth to their young ones?',
    correctAnswerFormula: 'Cows, zebras, and lions',
    wrongAnswers: [
      'Birds and butterflies',
      'Fish and snakes',
      'Frogs and snails',
    ],
    methodSteps: [
      'Mammals give birth to live young.',
      'Examples: cows, zebras, lions, elephants.',
      'Their babies drink milk from their mothers.',
    ],
  },

  // ========== ADDITIONAL HUMAN BODY QUESTIONS ==========
  {
    id: 'human-skin-feel',
    topic: 'Human Body',
    category: 'Human Body',
    difficulty: 'Easy',
    questionTemplate: 'Which part of our body can feel hot and cold?',
    correctAnswerFormula: 'Skin',
    wrongAnswers: ['Nose', 'Eyes', 'Ears'],
    methodSteps: [
      'Skin has nerve endings.',
      'These nerves detect temperature.',
      'Skin senses touch, pain, hot, and cold.',
    ],
  },
  {
    id: 'human-tongue-tastes',
    topic: 'Human Body',
    category: 'Human Body',
    difficulty: 'Easy',
    questionTemplate: 'The tongue can sense which tastes?',
    correctAnswerFormula: 'Sweet, bitter, sour, and salt',
    wrongAnswers: [
      'Only sweet',
      'Only sour',
      'Hot and cold',
    ],
    methodSteps: [
      'The tongue has taste buds.',
      'Taste buds detect: sweet, sour, salty, bitter, and umami.',
      'Different parts of the tongue sense different tastes.',
    ],
  },
  {
    id: 'human-owl-eyesight',
    topic: 'Human Body',
    category: 'Human Body',
    difficulty: 'Medium',
    questionTemplate: 'Which animal has very good eyesight?',
    correctAnswerFormula: 'Owl',
    wrongAnswers: ['Mole', 'Bat', 'Earthworm'],
    methodSteps: [
      'Owls are birds of prey.',
      'They hunt at night and need excellent vision.',
      'Moles live underground and have poor eyesight.',
    ],
  },
  {
    id: 'human-common-eye-colors',
    topic: 'Human Body',
    category: 'Human Body',
    difficulty: 'Easy',
    questionTemplate: 'Common eye colors in human beings include:',
    correctAnswerFormula: 'Blue, hazel, and brown',
    wrongAnswers: [
      'Red, yellow, and green',
      'Only black',
      'Purple and orange',
    ],
    methodSteps: [
      'Most humans have brown, blue, or hazel eyes.',
      'Eye color is inherited from parents.',
      'Green and gray are also common.',
    ],
  },
  {
    id: 'human-all-similar-bodies',
    topic: 'Human Body',
    category: 'Human Body',
    difficulty: 'Medium',
    questionTemplate: 'Do all humans have similar bodies (same body parts)?',
    correctAnswerFormula: 'True',
    wrongAnswers: ['False'],
    methodSteps: [
      'All humans have the same body parts.',
      'We all have: head, arms, legs, eyes, nose, etc.',
      'But we differ in height, color, and features.',
    ],
  },
  {
    id: 'human-same-height',
    topic: 'Human Body',
    category: 'Human Body',
    difficulty: 'Easy',
    questionTemplate: 'Are all humans of the same height?',
    correctAnswerFormula: 'False',
    wrongAnswers: ['True'],
    methodSteps: [
      'Humans have different heights.',
      'Height depends on genetics and nutrition.',
      'Some people are tall, some are short.',
    ],
  },
  {
    id: 'human-same-skin-color',
    topic: 'Human Body',
    category: 'Human Body',
    difficulty: 'Easy',
    questionTemplate: 'Do we all have similar skin color and hair color?',
    correctAnswerFormula: 'False',
    wrongAnswers: ['True'],
    methodSteps: [
      'Humans have different skin colors.',
      'Hair color also varies (black, brown, blonde, red).',
      'These differences make us unique.',
    ],
  },

  // ========== ADDITIONAL LIFE PROCESSES ==========
  {
    id: 'life-cat-kittens',
    topic: 'Living Things',
    category: 'Living Things',
    difficulty: 'Easy',
    questionTemplate: 'A cat giving birth to kittens is an example of:',
    correctAnswerFormula: 'Reproduction',
    wrongAnswers: ['Growth', 'Nutrition', 'Movement'],
    methodSteps: [
      'Reproduction is producing offspring.',
      'Cats give birth to baby cats (kittens).',
      'This continues the species.',
    ],
  },
  {
    id: 'life-butterfly-nectar',
    topic: 'Living Things',
    category: 'Living Things',
    difficulty: 'Medium',
    questionTemplate: 'A butterfly drinking nectar is an example of:',
    correctAnswerFormula: 'Nutrition',
    wrongAnswers: ['Respiration', 'Reproduction', 'Growth'],
    methodSteps: [
      'Nutrition is getting food.',
      'Butterflies drink nectar from flowers.',
      'This gives them energy to live.',
    ],
  },
  {
    id: 'life-lion-running',
    topic: 'Living Things',
    category: 'Living Things',
    difficulty: 'Easy',
    questionTemplate: 'A lion running to catch its prey is an example of:',
    correctAnswerFormula: 'Movement',
    wrongAnswers: ['Nutrition', 'Growth', 'Respiration'],
    methodSteps: [
      'Movement is changing position.',
      'The lion runs using its legs.',
      'Movement helps animals find food and escape danger.',
    ],
  },
  {
    id: 'life-plant-taller',
    topic: 'Living Things',
    category: 'Living Things',
    difficulty: 'Easy',
    questionTemplate: 'A plant growing taller is an example of:',
    correctAnswerFormula: 'Growth',
    wrongAnswers: ['Movement', 'Nutrition', 'Reproduction'],
    methodSteps: [
      'Growth is getting bigger.',
      'Plants grow taller as they develop.',
      'All living things grow.',
    ],
  },
  {
    id: 'life-living-seven-processes',
    topic: 'Living Things',
    category: 'Living Things',
    difficulty: 'Hard',
    questionTemplate: 'Do all living things have seven life processes?',
    correctAnswerFormula: 'True',
    wrongAnswers: ['False'],
    methodSteps: [
      'The 7 life processes are: Movement, Respiration, Sensitivity, Growth, Reproduction, Excretion, Nutrition.',
      'Remember: MRS GREN.',
      'All living things do all 7 processes.',
    ],
  },
  {
    id: 'life-humans-five-senses',
    topic: 'Living Things',
    category: 'Living Things',
    difficulty: 'Easy',
    questionTemplate: 'Do humans have five senses?',
    correctAnswerFormula: 'True',
    wrongAnswers: ['False'],
    methodSteps: [
      'Humans have 5 senses.',
      'They are: sight, hearing, smell, taste, and touch.',
      'Senses help us understand our environment.',
    ],
  },

  // ========== ADDITIONAL ROCKS QUESTIONS ==========
  {
    id: 'rocks-chicken-bodybuilding',
    topic: 'Nutrition',
    category: 'Nutrition and Health',
    difficulty: 'Easy',
    questionTemplate: 'Which food is a body-building food?',
    correctAnswerFormula: 'Chicken',
    wrongAnswers: ['Potato', 'Rice', 'Bread'],
    methodSteps: [
      'Body-building foods are rich in protein.',
      'Chicken has lots of protein.',
      'Protein helps you grow and build muscles.',
    ],
  },

  // ========== SPECIAL TOPICS ==========
  {
    id: 'senses-ear-function',
    topic: 'Human Body',
    category: 'Human Body',
    difficulty: 'Easy',
    questionTemplate: 'Which sensory organ helps us hear loud and quiet sounds?',
    correctAnswerFormula: 'Ears',
    wrongAnswers: ['Eyes', 'Nose', 'Tongue'],
    methodSteps: [
      'Ears are the organs for hearing.',
      'They detect sound waves.',
      'We can hear both loud and quiet sounds.',
    ],
  },
  {
    id: 'senses-nose-function',
    topic: 'Human Body',
    category: 'Human Body',
    difficulty: 'Easy',
    questionTemplate: 'Which sensory organ helps us smell food?',
    correctAnswerFormula: 'Nose',
    wrongAnswers: ['Tongue', 'Eyes', 'Skin'],
    methodSteps: [
      'The nose is the organ for smell.',
      'It detects odors in the air.',
      'Smell helps us enjoy food and detect danger.',
    ],
  },
  {
    id: 'animals-shark-sense',
    topic: 'Animals',
    category: 'Animals',
    difficulty: 'Medium',
    questionTemplate: 'Sharks have a very good sense of:',
    correctAnswerFormula: 'Smell',
    wrongAnswers: ['Sight', 'Hearing', 'Taste'],
    methodSteps: [
      'Sharks can smell blood from miles away.',
      'Their sense of smell helps them hunt.',
      'This is their most important sense.',
    ],
  },
  {
    id: 'plants-coconut-seed-dispersal',
    topic: 'Plants',
    category: 'Plants',
    difficulty: 'Medium',
    questionTemplate: 'How does a coconut seed move to new places?',
    correctAnswerFormula: 'Floating on water',
    wrongAnswers: ['Wind', 'Birds carry it', 'Animals eat it'],
    methodSteps: [
      'Coconuts can float in water.',
      'They fall into rivers or oceans.',
      'Water carries them to new shores where they grow.',
    ],
  },

  // ========== ADDITIONAL ANIMALS QUESTIONS (to reach 10) ==========
  {
    id: 'animals-bat-movement',
    topic: 'Animals',
    category: 'Animals',
    difficulty: 'Easy',
    questionTemplate: 'How do bats move from place to place?',
    correctAnswerFormula: 'Fly',
    wrongAnswers: ['Walk', 'Swim', 'Crawl'],
    methodSteps: [
      'Bats are mammals that can fly.',
      'They have wings made of skin.',
      'They are the only mammals that can truly fly.',
    ],
  },

  // ========== ADDITIONAL LIVING THINGS QUESTIONS (to reach 10) ==========
  {
    id: 'life-plants-need-sunlight',
    topic: 'Living Things',
    category: 'Living Things',
    difficulty: 'Easy',
    questionTemplate: 'Do plants need sunlight to survive?',
    correctAnswerFormula: 'True',
    wrongAnswers: ['False'],
    methodSteps: [
      'Plants need sunlight to make food.',
      'They use sunlight for photosynthesis.',
      'Without sunlight, plants cannot grow properly.',
    ],
  },
  {
    id: 'life-animals-need-water',
    topic: 'Living Things',
    category: 'Living Things',
    difficulty: 'Easy',
    questionTemplate: 'Do all living things need water?',
    correctAnswerFormula: 'True',
    wrongAnswers: ['False'],
    methodSteps: [
      'Water is essential for all life.',
      'Living things need water to survive.',
      'Without water, living things will die.',
    ],
  },
  {
    id: 'life-non-living-cannot-grow',
    topic: 'Living Things',
    category: 'Living Things',
    difficulty: 'Medium',
    questionTemplate: 'Can non-living things grow?',
    correctAnswerFormula: 'False',
    wrongAnswers: ['True'],
    methodSteps: [
      'Only living things can grow.',
      'Non-living things like rocks do not grow.',
      'Growth is one of the characteristics of life.',
    ],
  },
  {
    id: 'life-plants-breathe',
    topic: 'Living Things',
    category: 'Living Things',
    difficulty: 'Medium',
    questionTemplate: 'Do plants breathe (respire)?',
    correctAnswerFormula: 'True',
    wrongAnswers: ['False'],
    methodSteps: [
      'All living things respire (breathe).',
      'Plants take in oxygen and release carbon dioxide.',
      'Plants breathe through tiny holes in their leaves.',
    ],
  },

  // ========== ADDITIONAL FOOD CHAINS QUESTIONS (to reach 10) ==========
  {
    id: 'food-chain-start',
    topic: 'Food Chains',
    category: 'Food Chains',
    difficulty: 'Easy',
    questionTemplate: 'What do all food chains start with?',
    correctAnswerFormula: 'Plants (producers)',
    wrongAnswers: ['Animals', 'Humans', 'Fungi'],
    methodSteps: [
      'Food chains always begin with plants.',
      'Plants are called producers because they make their own food.',
      'They use sunlight to create food through photosynthesis.',
    ],
  },
  {
    id: 'food-chain-herbivore',
    topic: 'Food Chains',
    category: 'Food Chains',
    difficulty: 'Easy',
    questionTemplate: 'What do we call animals that only eat plants?',
    correctAnswerFormula: 'Herbivores',
    wrongAnswers: ['Carnivores', 'Omnivores', 'Producers'],
    methodSteps: [
      'Animals that eat only plants are herbivores.',
      'Examples: cows, rabbits, deer, elephants.',
      'They get energy from eating plants.',
    ],
  },
  {
    id: 'food-chain-carnivore',
    topic: 'Food Chains',
    category: 'Food Chains',
    difficulty: 'Easy',
    questionTemplate: 'What do we call animals that eat other animals?',
    correctAnswerFormula: 'Carnivores',
    wrongAnswers: ['Herbivores', 'Omnivores', 'Producers'],
    methodSteps: [
      'Animals that eat other animals are carnivores.',
      'Examples: lions, tigers, sharks, eagles.',
      'They are often called predators.',
    ],
  },
  {
    id: 'food-chain-omnivore',
    topic: 'Food Chains',
    category: 'Food Chains',
    difficulty: 'Medium',
    questionTemplate: 'What do we call animals that eat both plants and animals?',
    correctAnswerFormula: 'Omnivores',
    wrongAnswers: ['Herbivores', 'Carnivores', 'Producers'],
    methodSteps: [
      'Animals that eat both plants and animals are omnivores.',
      'Examples: bears, humans, pigs, chickens.',
      'They have a varied diet.',
    ],
  },
  {
    id: 'food-chain-rabbit-grass',
    topic: 'Food Chains',
    category: 'Food Chains',
    difficulty: 'Easy',
    questionTemplate: 'In the food chain: Grass → Rabbit → Fox, what is the rabbit?',
    correctAnswerFormula: 'Consumer (herbivore)',
    wrongAnswers: ['Producer', 'Decomposer', 'Predator'],
    methodSteps: [
      'The rabbit eats grass.',
      'Animals that eat plants are consumers.',
      'The rabbit is a herbivore consumer.',
    ],
  },
  {
    id: 'food-chain-energy-source',
    topic: 'Food Chains',
    category: 'Food Chains',
    difficulty: 'Medium',
    questionTemplate: 'Where does the energy in a food chain originally come from?',
    correctAnswerFormula: 'The Sun',
    wrongAnswers: ['Water', 'Soil', 'Air'],
    methodSteps: [
      'All energy in food chains comes from the Sun.',
      'Plants capture sunlight and make food.',
      'This energy passes through the food chain.',
    ],
  },
];

export function getComprehensiveScienceTemplates() {
  return comprehensiveScienceTemplates;
}

export function getComprehensiveScienceCategories() {
  const categories = new Set(comprehensiveScienceTemplates.map(t => t.category));
  return Array.from(categories);
}

