import { QuestionTemplate } from '@/types/question-template';

/**
 * Science Question Templates - Based on Actual Grade 3 Exam Papers
 * All answers verified against official marking schemes
 */
export const scienceExamTemplates: QuestionTemplate[] = [
  // ========== ANIMALS - EASY ==========
  {
    id: 'animals-pincers-exam',
    topic: 'Animals',
    category: 'Animals',
    difficulty: 'Easy',
    questionTemplate: 'Which animal has pincers?',
    correctAnswerFormula: 'Lobster',
    wrongAnswers: ['Moth', 'Worms', 'Snake'],
    methodSteps: [
      'Pincers are claw-like body parts used for grabbing.',
      'Lobsters and crabs have pincers.',
      'They use pincers to catch food and defend themselves.',
    ],
  },
  {
    id: 'animals-habitat-snails-exam',
    topic: 'Animals',
    category: 'Animals',
    difficulty: 'Easy',
    questionTemplate: 'Land snails prefer which type of habitat?',
    correctAnswerFormula: 'Shady and damp',
    wrongAnswers: ['Shady and dry', 'Hot and damp', 'Hot and dry'],
    methodSteps: [
      'Snails need moisture to survive.',
      'Shade protects them from drying out.',
      'A damp, shady environment is ideal for snails.',
    ],
  },
  {
    id: 'animals-classification-falcon-exam',
    topic: 'Animals',
    category: 'Animals',
    difficulty: 'Medium',
    questionTemplate: 'A falcon is grouped in which two animal groups?',
    correctAnswerFormula: 'Vertebrates and Birds',
    wrongAnswers: [
      'Invertebrates and Mammals',
      'Molluscs and Birds',
      'Mammals and Crustaceans',
    ],
    methodSteps: [
      'Vertebrates are animals with a backbone.',
      'Birds are warm-blooded vertebrates with feathers and wings.',
      'Falcons have a backbone and are birds, so they belong to both groups.',
    ],
  },
  {
    id: 'animals-habitat-polar-exam',
    topic: 'Animals',
    category: 'Animals',
    difficulty: 'Medium',
    questionTemplate: 'Where do polar bears live and are adapted to?',
    correctAnswerFormula: 'Arctic',
    wrongAnswers: ['Rain forest', 'Grassland', 'Desert'],
    methodSteps: [
      'Polar bears live in the Arctic region.',
      'They have thick fur and fat to keep warm in freezing temperatures.',
      'Their white color helps them blend with snow and ice.',
    ],
  },
  {
    id: 'animals-teeth-carnivore-exam',
    topic: 'Animals',
    category: 'Animals',
    difficulty: 'Hard',
    questionTemplate: 'Animals with sharp pointed teeth and large canines are called:',
    correctAnswerFormula: 'Carnivores',
    wrongAnswers: ['Herbivores', 'Omnivores', 'Insectivores'],
    methodSteps: [
      'Carnivores eat meat.',
      'They have sharp, pointed teeth for tearing flesh.',
      'Large canine teeth help them catch and kill prey.',
    ],
  },
  {
    id: 'animals-camouflage-exam',
    topic: 'Animals',
    category: 'Animals',
    difficulty: 'Medium',
    questionTemplate: 'What is the word for being a similar color to what is around you?',
    correctAnswerFormula: 'Camouflage',
    wrongAnswers: ['Adaptation', 'Migration', 'Hibernation'],
    methodSteps: [
      'Camouflage means blending in with surroundings.',
      'Animals use camouflage to hide from predators or prey.',
      'Example: polar bears are white to blend with snow.',
    ],
  },

  // ========== ROCKS AND SOILS - EASY TO MEDIUM ==========
  {
    id: 'rocks-impermeable-exam',
    topic: 'Rocks and Soils',
    category: 'Rocks and Soils',
    difficulty: 'Easy',
    questionTemplate: 'Which rock is impermeable (water cannot pass through)?',
    correctAnswerFormula: 'Slate',
    wrongAnswers: ['Pumice', 'Limestone', 'Chalk'],
    methodSteps: [
      'Impermeable means water cannot pass through.',
      'Slate is a hard, impermeable metamorphic rock.',
      'Permeable rocks like pumice allow water to pass through.',
    ],
  },
  {
    id: 'rocks-igneous-formation-exam',
    topic: 'Rocks and Soils',
    category: 'Rocks and Soils',
    difficulty: 'Easy',
    questionTemplate: 'Magma cools down and hardens to form which type of rocks?',
    correctAnswerFormula: 'Igneous rocks',
    wrongAnswers: ['Sedimentary rocks', 'Metamorphic rocks', 'Permeable rocks'],
    methodSteps: [
      'Igneous rocks form from cooling magma or lava.',
      'When hot molten rock cools, it solidifies.',
      'Examples: granite, basalt, pumice.',
    ],
  },
  {
    id: 'rocks-sedimentary-formation-exam',
    topic: 'Rocks and Soils',
    category: 'Rocks and Soils',
    difficulty: 'Medium',
    questionTemplate: 'How are sedimentary rocks formed?',
    correctAnswerFormula: 'By layers of sediments cementing together over time',
    wrongAnswers: [
      'When magma cools and hardens',
      'When rocks change due to heat and pressure',
      'When rocks melt underground',
    ],
    methodSteps: [
      'Sediments are small pieces of rock, sand, and shells.',
      'They settle in layers at the bottom of rivers and seas.',
      'Over time, these layers cement together to form sedimentary rocks.',
    ],
  },
  {
    id: 'rocks-metamorphic-formation-exam',
    topic: 'Rocks and Soils',
    category: 'Rocks and Soils',
    difficulty: 'Medium',
    questionTemplate: 'How are metamorphic rocks formed?',
    correctAnswerFormula: 'When another type of rock changes due to heat and pressure',
    wrongAnswers: [
      'When magma cools and hardens',
      'By layers cementing together',
      'When rocks dissolve in water',
    ],
    methodSteps: [
      'Metamorphic rocks form when existing rocks change.',
      'Heat and pressure deep underground cause the change.',
      'Example: slate forms from shale under pressure.',
    ],
  },
  {
    id: 'soils-drainage-exam',
    topic: 'Rocks and Soils',
    category: 'Rocks and Soils',
    difficulty: 'Hard',
    questionTemplate: 'Which type of soil drains water faster after rain?',
    correctAnswerFormula: 'Sandy soil',
    wrongAnswers: ['Clay soil', 'Muddy soil', 'Chalky soil'],
    methodSteps: [
      'Sandy soil has large particles with big spaces between them.',
      'Water drains quickly through these spaces.',
      'Clay soil has tiny particles that hold water longer.',
    ],
  },

  // ========== HUMAN BODY - TEETH ==========
  {
    id: 'teeth-molars-function-exam',
    topic: 'Human Body',
    category: 'Human Body',
    difficulty: 'Easy',
    questionTemplate: 'The molars are used to _____ the food.',
    correctAnswerFormula: 'Grind',
    wrongAnswers: ['Bite', 'Tear', 'Cut'],
    methodSteps: [
      'Molars are the large teeth at the back of your mouth.',
      'They have a flat surface.',
      'Molars grind and crush food into small pieces.',
    ],
  },
  {
    id: 'teeth-incisors-function-exam',
    topic: 'Human Body',
    category: 'Human Body',
    difficulty: 'Easy',
    questionTemplate: 'When you eat an apple, which type of teeth is used to bite into it?',
    correctAnswerFormula: 'Incisors',
    wrongAnswers: ['Molars', 'Canines', 'Premolars'],
    methodSteps: [
      'Incisors are the front teeth.',
      'They are sharp and flat, perfect for biting.',
      'You use incisors to bite into apples and other foods.',
    ],
  },
  {
    id: 'teeth-incisors-count-exam',
    topic: 'Human Body',
    category: 'Human Body',
    difficulty: 'Medium',
    questionTemplate: 'How many incisors are there in the human mouth?',
    correctAnswerFormula: '8',
    wrongAnswers: ['4', '6', '12'],
    methodSteps: [
      'Incisors are the front teeth used for biting.',
      'There are 4 incisors on the top jaw.',
      'There are 4 incisors on the bottom jaw, making 8 total.',
    ],
  },
  {
    id: 'mouth-saliva-exam',
    topic: 'Human Body',
    category: 'Human Body',
    difficulty: 'Easy',
    questionTemplate: 'What in our mouth makes the food soft and wet?',
    correctAnswerFormula: 'Saliva',
    wrongAnswers: ['Tongue', 'Lips', 'Teeth'],
    methodSteps: [
      'Saliva is the liquid in your mouth.',
      'It moistens food to make it easier to swallow.',
      'Saliva also starts breaking down food for digestion.',
    ],
  },

  // ========== HUMAN BODY - SENSES ==========
  {
    id: 'senses-count-exam',
    topic: 'Human Body',
    category: 'Human Body',
    difficulty: 'Easy',
    questionTemplate: 'How many senses do all humans have?',
    correctAnswerFormula: 'Five',
    wrongAnswers: ['Three', 'Four', 'Six'],
    methodSteps: [
      'Humans have 5 senses.',
      'The 5 senses are: sight, hearing, smell, taste, and touch.',
      'We use our senses to learn about the world.',
    ],
  },
  {
    id: 'senses-taste-exam',
    topic: 'Human Body',
    category: 'Human Body',
    difficulty: 'Easy',
    questionTemplate: 'We taste food with our:',
    correctAnswerFormula: 'Tongue',
    wrongAnswers: ['Mouth', 'Lips', 'Teeth'],
    methodSteps: [
      'The tongue has taste buds.',
      'Taste buds detect different flavors.',
      'The 5 basic tastes are sweet, sour, salty, bitter, and umami.',
    ],
  },
  {
    id: 'senses-observe-exam',
    topic: 'Human Body',
    category: 'Human Body',
    difficulty: 'Easy',
    questionTemplate: 'We observe the environment with our:',
    correctAnswerFormula: 'Eyes',
    wrongAnswers: ['Nose', 'Ears', 'Hands'],
    methodSteps: [
      'Our eyes allow us to see.',
      'We use sight to observe and understand our surroundings.',
      'Vision is one of the most important senses.',
    ],
  },
  {
    id: 'senses-smell-taste-exam',
    topic: 'Human Body',
    category: 'Human Body',
    difficulty: 'Medium',
    questionTemplate: 'Which two senses work together?',
    correctAnswerFormula: 'Smell and taste',
    wrongAnswers: ['Smell and sight', 'Taste and hearing', 'Touch and sight'],
    methodSteps: [
      'Smell and taste are closely connected.',
      'Your sense of smell affects how you taste food.',
      'When you have a cold and cannot smell, food tastes bland.',
    ],
  },
  {
    id: 'senses-danger-exam',
    topic: 'Human Body',
    category: 'Human Body',
    difficulty: 'Medium',
    questionTemplate: 'Animals use their sense of _____ to sense danger.',
    correctAnswerFormula: 'Smell',
    wrongAnswers: ['Taste', 'Hearing', 'Touch'],
    methodSteps: [
      'Many animals have a very strong sense of smell.',
      'They can smell predators from far away.',
      'This helps them detect danger and escape.',
    ],
  },
  {
    id: 'senses-underground-animals-exam',
    topic: 'Human Body',
    category: 'Human Body',
    difficulty: 'Medium',
    questionTemplate: 'Animals that live underground have poor:',
    correctAnswerFormula: 'Eyesight',
    wrongAnswers: ['Taste', 'Hearing', 'Smell'],
    methodSteps: [
      'Underground is dark with no light.',
      'Animals living there don\'t need good eyesight.',
      'They rely more on other senses like touch and smell.',
    ],
  },
  {
    id: 'senses-hunting-exam',
    topic: 'Human Body',
    category: 'Human Body',
    difficulty: 'Medium',
    questionTemplate: 'Land animals that hunt use which sense to find prey?',
    correctAnswerFormula: 'Eyesight',
    wrongAnswers: ['Taste', 'Touch', 'Hearing'],
    methodSteps: [
      'Hunters need to spot their prey from a distance.',
      'Good eyesight helps them see movement and track animals.',
      'Birds of prey like eagles have excellent vision.',
    ],
  },

  // ========== LIFE PROCESSES ==========
  {
    id: 'life-process-respiration-exam',
    topic: 'Living Things',
    category: 'Living Things',
    difficulty: 'Easy',
    questionTemplate: 'Animals breathing in oxygen is an example of which life process?',
    correctAnswerFormula: 'Respiration',
    wrongAnswers: ['Reproduction', 'Growth', 'Movement'],
    methodSteps: [
      'Respiration is the process of breathing.',
      'Animals breathe in oxygen and breathe out carbon dioxide.',
      'All living things need respiration to get energy.',
    ],
  },
  {
    id: 'life-process-nutrition-exam',
    topic: 'Living Things',
    category: 'Living Things',
    difficulty: 'Easy',
    questionTemplate: 'Plants making their own food is an example of which life process?',
    correctAnswerFormula: 'Nutrition',
    wrongAnswers: ['Respiration', 'Growth', 'Reproduction'],
    methodSteps: [
      'Nutrition is how living things get food.',
      'Plants make their own food using sunlight, water, and air.',
      'This process is called photosynthesis.',
    ],
  },
  {
    id: 'life-process-reproduction-exam',
    topic: 'Living Things',
    category: 'Living Things',
    difficulty: 'Medium',
    questionTemplate: 'Frogs laying eggs is an example of which life process?',
    correctAnswerFormula: 'Reproduction',
    wrongAnswers: ['Nutrition', 'Growth', 'Respiration'],
    methodSteps: [
      'Reproduction is how living things create offspring.',
      'Frogs reproduce by laying eggs in water.',
      'The eggs hatch into tadpoles which grow into frogs.',
    ],
  },
  {
    id: 'life-process-movement-exam',
    topic: 'Living Things',
    category: 'Living Things',
    difficulty: 'Medium',
    questionTemplate: 'Plants turning towards the sun is an example of which life process?',
    correctAnswerFormula: 'Movement',
    wrongAnswers: ['Nutrition', 'Growth', 'Respiration'],
    methodSteps: [
      'Movement is the ability to change position.',
      'Plants move slowly by growing towards light.',
      'This movement is called phototropism.',
    ],
  },
  {
    id: 'life-process-growth-exam',
    topic: 'Living Things',
    category: 'Living Things',
    difficulty: 'Medium',
    questionTemplate: 'A seed becoming a fully grown plant is an example of which life process?',
    correctAnswerFormula: 'Growth',
    wrongAnswers: ['Nutrition', 'Reproduction', 'Movement'],
    methodSteps: [
      'Growth is getting bigger and more complex.',
      'A seed grows into a seedling, then into a mature plant.',
      'All living things grow and develop over time.',
    ],
  },

  // ========== FOOD CHAINS ==========
  {
    id: 'food-chain-producer-exam',
    topic: 'Food Chains',
    category: 'Food Chains',
    difficulty: 'Easy',
    questionTemplate: 'In a food web with carrots, rabbits, and foxes, which is a producer?',
    correctAnswerFormula: 'Carrot',
    wrongAnswers: ['Rabbit', 'Fox', 'Mouse'],
    methodSteps: [
      'Producers make their own food.',
      'Plants like carrots are producers.',
      'They use sunlight to make food through photosynthesis.',
    ],
  },
  {
    id: 'food-chain-herbivores-exam',
    topic: 'Food Chains',
    category: 'Food Chains',
    difficulty: 'Medium',
    questionTemplate: 'In a food web, which are herbivores (plant-eaters)?',
    correctAnswerFormula: 'Rabbits and grasshoppers',
    wrongAnswers: [
      'Owls and foxes',
      'Grass and carrots',
      'Owls and grasshoppers',
    ],
    methodSteps: [
      'Herbivores eat only plants.',
      'Rabbits eat carrots and grass.',
      'Grasshoppers eat grass and grains.',
    ],
  },
  {
    id: 'food-chain-predators-exam',
    topic: 'Food Chains',
    category: 'Food Chains',
    difficulty: 'Medium',
    questionTemplate: 'In a food web, which are predators (hunters)?',
    correctAnswerFormula: 'Owls and foxes',
    wrongAnswers: [
      'Rabbits and mice',
      'Grass and carrots',
      'Grasshoppers and birds',
    ],
    methodSteps: [
      'Predators hunt and eat other animals.',
      'Owls hunt mice and small birds.',
      'Foxes hunt rabbits and mice.',
    ],
  },
  {
    id: 'food-chain-prey-exam',
    topic: 'Food Chains',
    category: 'Food Chains',
    difficulty: 'Easy',
    questionTemplate: 'In a food web, which animal is prey (hunted by others)?',
    correctAnswerFormula: 'Mice',
    wrongAnswers: ['Owls', 'Foxes', 'Carrots'],
    methodSteps: [
      'Prey are animals that are hunted and eaten.',
      'Mice are prey for owls and foxes.',
      'Prey animals are usually smaller than predators.',
    ],
  },
  {
    id: 'food-chain-consumers-exam',
    topic: 'Food Chains',
    category: 'Food Chains',
    difficulty: 'Medium',
    questionTemplate: 'In a food web, which are consumers?',
    correctAnswerFormula: 'Grasshoppers and foxes',
    wrongAnswers: [
      'Grass and carrots',
      'Only plants',
      'Only producers',
    ],
    methodSteps: [
      'Consumers eat other living things.',
      'They cannot make their own food.',
      'Both plant-eaters and meat-eaters are consumers.',
    ],
  },

  // ========== WATER CYCLE ==========
  {
    id: 'water-cycle-melting-exam',
    topic: 'Water Cycle',
    category: 'Water Cycle',
    difficulty: 'Easy',
    questionTemplate: 'Ice cubes changing into water is called:',
    correctAnswerFormula: 'Melting',
    wrongAnswers: ['Freezing', 'Evaporating', 'Condensing'],
    methodSteps: [
      'Melting is when a solid turns into a liquid.',
      'Ice melts when it gets warm.',
      'The melting point of ice is 0°C.',
    ],
  },
  {
    id: 'water-cycle-freezing-exam',
    topic: 'Water Cycle',
    category: 'Water Cycle',
    difficulty: 'Easy',
    questionTemplate: 'Water will _____ if we keep it in the freezer.',
    correctAnswerFormula: 'Freeze',
    wrongAnswers: ['Evaporate', 'Condense', 'Melt'],
    methodSteps: [
      'Freezing is when liquid turns into solid.',
      'Water freezes at 0°C or below.',
      'When water freezes, it becomes ice.',
    ],
  },

  // ========== MATERIALS ==========
  {
    id: 'materials-pots-exam',
    topic: 'Materials',
    category: 'Materials',
    difficulty: 'Easy',
    questionTemplate: 'Which material is suitable for making pots?',
    correctAnswerFormula: 'Clay',
    wrongAnswers: ['Metal', 'Wood', 'Glass'],
    methodSteps: [
      'Clay is soft when wet and can be shaped.',
      'When clay is heated in a kiln, it becomes hard.',
      'Clay pots are strong and can hold water.',
    ],
  },
  {
    id: 'materials-raincoats-exam',
    topic: 'Materials',
    category: 'Materials',
    difficulty: 'Easy',
    questionTemplate: 'A good material for making raincoats should be:',
    correctAnswerFormula: 'Light and waterproof',
    wrongAnswers: [
      'Heavy and rough',
      'Soft and stretchy',
      'Absorbent and shiny',
    ],
    methodSteps: [
      'Raincoats need to keep you dry.',
      'Waterproof materials don\'t let water through.',
      'Light materials are comfortable to wear.',
    ],
  },

  // ========== FORCES ==========
  {
    id: 'forces-twisted-exam',
    topic: 'Forces',
    category: 'Forces',
    difficulty: 'Easy',
    questionTemplate: 'A rope that has been turned around itself has been:',
    correctAnswerFormula: 'Twisted',
    wrongAnswers: ['Bent', 'Squeezed', 'Squashed'],
    methodSteps: [
      'Twisting is a turning force.',
      'When you twist a rope, you turn one end while holding the other.',
      'Twisted things wind around themselves.',
    ],
  },
];

export function getExamBasedScienceTemplates() {
  return scienceExamTemplates;
}
