import { QuestionTemplate } from '@/types/question-template';

/**
 * Sinhala Question Templates - Grade 3 (ශ්‍රේණිය 3)
 * Based on Lyceum Grade 3 Sinhala papers structure; PDFs often extract as image/romanized,
 * so these are curriculum-aligned MCQs in proper Sinhala Unicode.
 * Categories: Letters & Sounds, Vocabulary, Grammar, Comprehension, Word Meaning
 */

export const SINHALA_CATEGORIES = [
  'Letters and Sounds',
  'Vocabulary',
  'Grammar',
  'Comprehension',
  'Word Meaning',
] as const;

export const sinhalaTemplates: QuestionTemplate[] = [
  // ========== අක්ෂර / Letters and Sounds ==========
  {
    id: 'sin-letter-first',
    topic: 'අක්ෂර මාලාව',
    category: 'Letters and Sounds',
    difficulty: 'Easy',
    questionTemplate: 'සිංහල අක්ෂර මාලාවේ පළමු අක්ෂරය කුමක්ද?',
    correctAnswerFormula: 'අ',
    wrongAnswers: ['ආ', 'ඇ', 'ඉ'],
    methodSteps: ['සිංහල හෝඩිය අ කියවෙන අක්ෂරයෙන් ආරම්භ වේ.', 'පළමු අක්ෂරය අ වේ.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },
  {
    id: 'sin-letter-second',
    topic: 'අක්ෂර මාලාව',
    category: 'Letters and Sounds',
    difficulty: 'Easy',
    questionTemplate: 'සිංහල හෝඩියේ දෙවන අක්ෂරය කුමක්ද?',
    correctAnswerFormula: 'ආ',
    wrongAnswers: ['අ', 'ඇ', 'ඈ'],
    methodSteps: ['අ ට පසු ආ එනු ලැබේ.', 'දෙවන අක්ෂරය ආ වේ.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },
  {
    id: 'sin-letter-aa',
    topic: 'අක්ෂර',
    category: 'Letters and Sounds',
    difficulty: 'Easy',
    questionTemplate: '"අම්මා" යන වචනයේ අක්ෂර කීයක් තිබේද?',
    correctAnswerFormula: '4',
    wrongAnswers: ['3', '5', '2'],
    methodSteps: ['අ-ම්-මා = අක්ෂර 4 කි.', 'එක් එක් අක්ෂරය ගණන් කරන්න.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'sin-letter-sound',
    topic: 'ශබ්ද',
    category: 'Letters and Sounds',
    difficulty: 'Easy',
    questionTemplate: '"ඉ" අක්ෂරයේ ශබ්දය සමඟ ආරම්භ වන වචනය තෝරන්න.',
    correctAnswerFormula: 'ඉස්සර',
    wrongAnswers: ['අස්සර', 'එස්සර', 'ඔස්සර'],
    methodSteps: ['ඉ යන්නෙන් ආරම්භ වන වචනය ඉස්සර වේ.', 'අ, එ, ඔ වෙනත් ශබ්ද.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  // ========== වචන / Vocabulary ==========
  {
    id: 'sin-vocab-fruit',
    topic: 'වචන',
    category: 'Vocabulary',
    difficulty: 'Easy',
    questionTemplate: 'පළතුරක් නම් කරන්න.',
    correctAnswerFormula: 'අන්නාසි',
    wrongAnswers: ['පොත', 'මේසය', 'කුස්සිය'],
    methodSteps: ['පළතුරු යනු ගෙඩි, අන්නාසි, කෙසෙල් වැනි ආහාර වේ.', 'අන්නාසි පළතුරකි.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },
  {
    id: 'sin-vocab-animal',
    topic: 'වචන',
    category: 'Vocabulary',
    difficulty: 'Easy',
    questionTemplate: 'සතා නම් කරන්න.',
    correctAnswerFormula: 'අළු',
    wrongAnswers: ['ගස', 'පුළුන්', 'දිය'],
    methodSteps: ['සතා යනු ජීවීන්, අළු, ගොනා, කුකුලා වැනි.', 'අළු සතෙකි.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },
  {
    id: 'sin-vocab-color',
    topic: 'වර්ණ',
    category: 'Vocabulary',
    difficulty: 'Easy',
    questionTemplate: 'පාට නම් කරන්න.',
    correctAnswerFormula: 'නිල්',
    wrongAnswers: ['ගස', 'බත්', 'ජලය'],
    methodSteps: ['පාට යනු නිල්, රතු, කහ වැනි වර්ණ.', 'නිල් පාටකි.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },
  {
    id: 'sin-vocab-number',
    topic: 'ගණන',
    category: 'Vocabulary',
    difficulty: 'Easy',
    questionTemplate: 'එකට වැඩි කොටස කුමක්ද?',
    correctAnswerFormula: 'දෙක',
    wrongAnswers: ['එක', 'හිටිය', 'ශුන්‍යය'],
    methodSteps: ['එකට එක එකතු කළහොත් දෙක.', 'දෙක එකට වැඩියි.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },
  // ========== ව්යාකරණ / Grammar ==========
  {
    id: 'sin-grammar-singular',
    topic: 'ඒක වචන',
    category: 'Grammar',
    difficulty: 'Easy',
    questionTemplate: '"පොත" යනු ඒක වචනද බහු වචනද?',
    correctAnswerFormula: 'ඒක වචන',
    wrongAnswers: ['බහු වචන', 'නොවේ', 'දෙකම'],
    methodSteps: ['එක් දෙයක් පොත.', 'ඒක වචන එක් දෙයක් දක්වයි.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'sin-grammar-plural',
    topic: 'බහු වචන',
    category: 'Grammar',
    difficulty: 'Easy',
    questionTemplate: '"පොත්" යනු ඒක වචනද බහු වචනද?',
    correctAnswerFormula: 'බහු වචන',
    wrongAnswers: ['ඒක වචන', 'නොවේ', 'දෙකම'],
    methodSteps: ['පොත් යනු පොත බොහෝ.', 'බහු වචන බොහෝ දේ දක්වයි.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'sin-grammar-gender',
    topic: 'ලිංගය',
    category: 'Grammar',
    difficulty: 'Easy',
    questionTemplate: '"අම්මා" යනු පුරුෂ ලිංගයද ස්ත්‍රී ලිංගයද?',
    correctAnswerFormula: 'ස්ත්‍රී ලිංගය',
    wrongAnswers: ['පුරුෂ ලිංගය', 'නපුංසක ලිංගය', 'කිසිවක් නොවේ'],
    methodSteps: ['අම්මා යනු මව, ස්ත්‍රීයකි.', 'ස්ත්‍රී ලිංගය ස්ත්‍රීන්ට යොදයි.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'sin-grammar-that',
    topic: 'සර්වනාම',
    category: 'Grammar',
    difficulty: 'Easy',
    questionTemplate: '"ඒ" යනු කිසිදුකම් (සර්වනාම) වර්ගයක්ද?',
    correctAnswerFormula: 'ඔව්',
    wrongAnswers: ['නැත', 'හැකිය', 'නොදන්නා'],
    methodSteps: ['ඒ යනු දක්වන පදයකි (සර්වනාම).', 'දුර ස්ථානයක් හෝ දෙයක් දක්වයි.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'sin-grammar-past',
    topic: 'කාලය',
    category: 'Grammar',
    difficulty: 'Medium',
    questionTemplate: '"ඔහු ගියේ ය" යන වාක්යයේ ක්‍රියා පදය කුමක්ද?',
    correctAnswerFormula: 'ගියේ ය',
    wrongAnswers: ['ඔහු', 'ය', 'ගියේ'],
    methodSteps: ['ක්‍රියා පදය යනු ක්‍රියාව දක්වන පදය.', 'ගියේ ය = යාමේ ක්‍රියාව.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  // ========== අර්ථ / Word Meaning ==========
  {
    id: 'sin-meaning-opposite-hot',
    topic: 'විරුද්ධ පද',
    category: 'Word Meaning',
    difficulty: 'Easy',
    questionTemplate: '"උණුසුම්" යන වචනයට විරුද්ධ පදය කුමක්ද?',
    correctAnswerFormula: 'සීතල',
    wrongAnswers: ['උණුසුම්', 'උෂ්ණය', 'ගින්න'],
    methodSteps: ['උණුසුම් = උණු, සීතල = ශීතල.', 'විරුද්ධය සීතල වේ.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'sin-meaning-opposite-big',
    topic: 'විරුද්ධ පද',
    category: 'Word Meaning',
    difficulty: 'Easy',
    questionTemplate: '"මහත්" යන වචනයට විරුද්ධ පදය කුමක්ද?',
    correctAnswerFormula: 'කුඩා',
    wrongAnswers: ['මහත්', 'විශාල', 'දිග'],
    methodSteps: ['මහත් = විශාල, කුඩා = කුඩා.', 'විරුද්ධය කුඩා වේ.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'sin-meaning-opposite-day',
    topic: 'විරුද්ධ පද',
    category: 'Word Meaning',
    difficulty: 'Easy',
    questionTemplate: '"දවස" යන වචනයට විරුද්ධ පදය කුමක්ද?',
    correctAnswerFormula: 'රැය',
    wrongAnswers: ['දවස', 'උදෑසන', 'සවස'],
    methodSteps: ['දවස = උදාවේ සිට සන්ධ්‍යාව දක්වා.', 'රැය = රාත්‍රිය, විරුද්ධය.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'sin-meaning-same',
    topic: 'සමානාර්ථක',
    category: 'Word Meaning',
    difficulty: 'Easy',
    questionTemplate: '"සතුට" ට ආසන්න අර්ථය ඇති වචනය කුමක්ද?',
    correctAnswerFormula: 'සැපය',
    wrongAnswers: ['දුක', 'කෝපය', 'බය'],
    methodSteps: ['සතුට = සැපය, සන්තෝෂය.', 'සැපය සමාන අර්ථයක් දේ.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  // ========== කියවීම / Comprehension ==========
  {
    id: 'sin-comp-who',
    topic: 'කියවීම',
    category: 'Comprehension',
    difficulty: 'Easy',
    questionTemplate: 'කතාවක හෝ පාඨයක "කා" යනු අසන්නේ කුමක් දැන ගැනීමටද?',
    correctAnswerFormula: 'පුද්ගලයා',
    wrongAnswers: ['කොතැනද', 'කවදාද', 'මන්ද'],
    methodSteps: ['කා = පුද්ගලයා ගැන.', 'කා, කවුද යනු පුද්ගලයා ගැන ප්‍රශ්න.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'sin-comp-where',
    topic: 'කියවීම',
    category: 'Comprehension',
    difficulty: 'Easy',
    questionTemplate: '"කොහේද" යනු කුමක් ගැන ප්‍රශ්න කිරීමක්ද?',
    correctAnswerFormula: 'ස්ථානය',
    wrongAnswers: ['කාලය', 'පුද්ගලයා', 'ක්‍රියාව'],
    methodSteps: ['කොහේද = තැන, ස්ථානය ගැන.', 'උදා: කොහේ ගියේද?'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'sin-comp-when',
    topic: 'කියවීම',
    category: 'Comprehension',
    difficulty: 'Easy',
    questionTemplate: 'කියවීමේදී "කවදාද" යන්නෙන් අදහස් වන්නේ කුමක්ද?',
    correctAnswerFormula: 'කාලය',
    wrongAnswers: ['ස්ථානය', 'පුද්ගලයා', 'ප්‍රමාණය'],
    methodSteps: ['කවදාද = කාලය ගැන ප්‍රශ්න.', 'උදා: කවදා ආවේද?'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'sin-comp-main',
    topic: 'කියවීම',
    category: 'Comprehension',
    difficulty: 'Medium',
    questionTemplate: 'කතාවක මුල් අදහස හඳුන්වන්නේ කෙසේද?',
    correctAnswerFormula: 'මාතෘකාව හෝ මූලික කතාව',
    wrongAnswers: ['අවසාන වාක්යය පමණයි', 'ප්‍රශ්න පමණයි', 'රූප පමණයි'],
    methodSteps: ['මුල් අදහස = කතාව කියන්නේ කුමක් ගැනද යන්න.', 'මාතෘකාව හෝ සාරාංශය එය දක්වයි.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  // More Letters and Sounds
  {
    id: 'sin-letter-three',
    topic: 'අක්ෂර',
    category: 'Letters and Sounds',
    difficulty: 'Easy',
    questionTemplate: 'අ, ආ ට පසු එන අක්ෂරය කුමක්ද?',
    correctAnswerFormula: 'ඇ',
    wrongAnswers: ['අ', 'ආ', 'ඈ'],
    methodSteps: ['හෝඩියේ අනුපිළිවෙල: අ, ආ, ඇ, ඈ...', 'තෙවන අක්ෂරය ඇ වේ.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },
  {
    id: 'sin-vocab-body',
    topic: 'ශරීරය',
    category: 'Vocabulary',
    difficulty: 'Easy',
    questionTemplate: 'ශරීර අවයවයක් නම් කරන්න.',
    correctAnswerFormula: 'අත්',
    wrongAnswers: ['ගස', 'ගෙය', 'රථය'],
    methodSteps: ['ශරීර අවයව යනු අත්, පා, ඇස, කන වැනි.', 'අත් ශරීර අවයවයකි.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },
  {
    id: 'sin-vocab-family',
    topic: 'පවුල',
    category: 'Vocabulary',
    difficulty: 'Easy',
    questionTemplate: 'පවුලේ සාමාජිකයෙකු නම් කරන්න.',
    correctAnswerFormula: 'තාත්තා',
    wrongAnswers: ['පොත', 'බත්', 'වතුර'],
    methodSteps: ['පවුලේ සාමාජිකයන් තාත්තා, අම්මා, සහෝදරයන්.', 'තාත්තා පවුලේ සාමාජිකයෙකි.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },
  {
    id: 'sin-grammar-action',
    topic: 'ක්‍රියා',
    category: 'Grammar',
    difficulty: 'Easy',
    questionTemplate: '"දුවනවා" යනු කුමක් දක්වන පදයක්ද?',
    correctAnswerFormula: 'ක්‍රියාව',
    wrongAnswers: ['නාම පදය', 'විශේෂණය', 'සර්වනාමය'],
    methodSteps: ['දුවනවා යනු කරන දෙය, ක්‍රියාව.', 'ක්‍රියා පද ක්‍රියා දක්වයි.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'sin-meaning-opposite-good',
    topic: 'විරුද්ධ පද',
    category: 'Word Meaning',
    difficulty: 'Easy',
    questionTemplate: '"හොඳ" යන වචනයට විරුද්ධ පදය කුමක්ද?',
    correctAnswerFormula: 'නරක',
    wrongAnswers: ['හොඳ', 'ඉතා හොඳ', 'සාර්ථක'],
    methodSteps: ['හොඳ = යහපත්, නරක = අයහපත්.', 'විරුද්ධය නරක වේ.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'sin-meaning-opposite-come',
    topic: 'විරුද්ධ පද',
    category: 'Word Meaning',
    difficulty: 'Easy',
    questionTemplate: '"එනවා" යන වචනයට විරුද්ධ පදය කුමක්ද?',
    correctAnswerFormula: 'යනවා',
    wrongAnswers: ['එනවා', 'ඉන්නවා', 'බලනවා'],
    methodSteps: ['එනවා = මෙහි එයි, යනවා = එහි යයි.', 'විරුද්ධ ක්‍රියා.'],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'sin-comp-how',
    topic: 'කියවීම',
    category: 'Comprehension',
    difficulty: 'Easy',
    questionTemplate: '"කෙසේද" යන ප්‍රශ්නයෙන් අදහස් වන්නේ කුමක් දැන ගැනීමටද?',
    correctAnswerFormula: 'ආකාරය හෝ තත්වය',
    wrongAnswers: ['ස්ථානය', 'කාලය', 'පුද්ගලයා'],
    methodSteps: ['කෙසේද = කොහොමද, ආකාරය.', 'උදා: කෙසේ ගියේද?'],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
];

export function getSinhalaTemplates(): QuestionTemplate[] {
  return sinhalaTemplates;
}
