import { QuestionTemplate } from '@/types/question-template';

/**
 * Social Studies Question Templates - Grade 3
 * Includes: curriculum-aligned topics + exact questions from ALL Lyceum GRADE 3 papers with mark schemes
 * (Jan 2021–2024, May 2021–2023, Oct 2021–2022, March 2021–2024, July 2021–2024)
 */

export const SOCIAL_STUDIES_CATEGORIES = [
  'Community',
  'Family and Roles',
  'Rules and Laws',
  'Maps and Places',
  'Culture and Festivals',
  'Citizenship',
  'Environment',
  'Goods and Services',
  'History and Heritage',
  'Transport',
] as const;

export const socialStudiesTemplates: QuestionTemplate[] = [
  // ========== FROM EXAM PAPERS (exact questions + mark scheme answers) ==========
  // January 2024
  {
    id: 'exam-jan24-kala-wewa',
    topic: 'Sri Lankan History',
    category: 'History and Heritage',
    difficulty: 'Easy',
    questionTemplate: 'Who built the Kala Wewa?',
    correctAnswerFormula: 'King Dhathusena',
    wrongAnswers: ['King Dutugamunu', 'King Tissa', 'King Kashyapa'],
    methodSteps: [
      'Kala Wewa is an ancient reservoir in Sri Lanka.',
      'It was built by King Dhathusena who ruled in the 5th century.',
      'King Dhathusena also built the Yodha Wewa and other irrigation works.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'exam-jan24-transport-pollution',
    topic: 'Transport',
    category: 'Transport',
    difficulty: 'Easy',
    questionTemplate: 'Which mode of transport does not cause pollution?',
    correctAnswerFormula: 'Bicycles',
    wrongAnswers: ['Buses', 'Cars', 'Lorries'],
    methodSteps: [
      'Bicycles are powered by people, not fuel.',
      'They do not produce smoke or harmful gases.',
      'Using bicycles helps keep the air clean.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },
  {
    id: 'exam-jan24-global-warming',
    topic: 'Environment',
    category: 'Environment',
    difficulty: 'Easy',
    questionTemplate: 'What is the increase in temperature of the Earth called?',
    correctAnswerFormula: 'Global warming',
    wrongAnswers: ['Apartments', 'Vostok Station', 'Pollution'],
    methodSteps: [
      'Global warming is the gradual increase in the Earth\'s temperature.',
      'It is mainly caused by too much carbon dioxide and other gases.',
      'We can help by using less energy and planting trees.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'exam-jan24-sigiriya-builder',
    topic: 'Sri Lankan History',
    category: 'History and Heritage',
    difficulty: 'Easy',
    questionTemplate: 'Who built the Sigiriya rock fortress?',
    correctAnswerFormula: 'King Kashyapa',
    wrongAnswers: ['King Dutugamunu', 'King Dhathusena', 'King Walagamba'],
    methodSteps: [
      'Sigiriya is a famous rock fortress in Sri Lanka.',
      'King Kashyapa built it and the frescoes (wall paintings) there.',
      'It is now a UNESCO World Heritage Site.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'exam-jan24-sandakada-pahana',
    topic: 'Sri Lankan Heritage',
    category: 'History and Heritage',
    difficulty: 'Medium',
    questionTemplate: 'What is the Sandakada Pahana?',
    correctAnswerFormula: 'Moon Stone',
    wrongAnswers: ['A type of temple', 'A king\'s crown', 'A reservoir'],
    methodSteps: [
      'Sandakada Pahana is also known as the Moon Stone.',
      'It is a carved stone at the doorsteps of temples.',
      'You can see it at ancient temples in Sri Lanka.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  // January 2023
  {
    id: 'exam-jan23-father-of-nation',
    topic: 'Sri Lankan History',
    category: 'History and Heritage',
    difficulty: 'Easy',
    questionTemplate: 'Who is known as the "Father of the Nation"?',
    correctAnswerFormula: 'Don Stephen Senanayake',
    wrongAnswers: ['King Dutugemunu', 'King Kashyapa', 'Anagarika Dharmapala'],
    methodSteps: [
      'Don Stephen Senanayake was the first Prime Minister of Sri Lanka.',
      'He played an active role in the independence movement.',
      'He is called the "Father of the Nation" for his leadership.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'exam-jan23-sigiriya-frescoes',
    topic: 'Sri Lankan History',
    category: 'History and Heritage',
    difficulty: 'Easy',
    questionTemplate: 'Sigiriya rock fortress and frescoes were done by:',
    correctAnswerFormula: 'King Kashyapa',
    wrongAnswers: ['King Walagamba', 'King Dutugemunu', 'King Dhathusena'],
    methodSteps: [
      'King Kashyapa built the Sigiriya fortress and its famous frescoes.',
      'Frescoes are paintings on walls.',
      'Sigiriya is a UNESCO World Heritage Site.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'exam-jan23-country-ruled',
    topic: 'Sri Lankan History',
    category: 'History and Heritage',
    difficulty: 'Easy',
    questionTemplate: 'Our country was ________ by foreign nations in the past.',
    correctAnswerFormula: 'Ruled',
    wrongAnswers: ['Forgotten', 'Chased', 'Ignored'],
    methodSteps: [
      'Sri Lanka was ruled by foreign nations in the past.',
      'Three European nations invaded: Portuguese, Dutch, and British.',
      'Sri Lanka gained independence on 4th February 1948.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'exam-jan23-kala-wewa-king',
    topic: 'Sri Lankan History',
    category: 'History and Heritage',
    difficulty: 'Easy',
    questionTemplate: 'Kala Wewa was built by which king?',
    correctAnswerFormula: 'King Dhatusena',
    wrongAnswers: ['King Kashyapa', 'King Dutugemunu', 'King Walagamba'],
    methodSteps: [
      'Kala Wewa was built by King Dhatusena (also spelled Dhathusena).',
      'It is one of the great ancient reservoirs of Sri Lanka.',
      'Kings built reservoirs to store water for farming.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'exam-jan23-independence-year',
    topic: 'Sri Lankan History',
    category: 'History and Heritage',
    difficulty: 'Easy',
    questionTemplate: 'In which year did our country gain independence?',
    correctAnswerFormula: '1948',
    wrongAnswers: ['1945', '1950', '1940'],
    methodSteps: [
      'Sri Lanka gained independence on 4th February 1948.',
      'Don Stephen Senanayake became the first Prime Minister.',
      'This day is celebrated as Independence Day.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'exam-jan23-public-transport',
    topic: 'Transport',
    category: 'Transport',
    difficulty: 'Medium',
    questionTemplate: 'What is public transportation?',
    correctAnswerFormula: 'Transport available to everyone with set fares and fixed routes',
    wrongAnswers: [
      'Only cars and bikes',
      'Transport used only by kings',
      'Transport that is free for everyone',
    ],
    methodSteps: [
      'Public transportation is for everyone to use.',
      'It has set fares and fixed routes (e.g. buses, trains).',
      'It helps people travel without owning a vehicle.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 30,
  },
  {
    id: 'exam-jan23-global-warming',
    topic: 'Environment',
    category: 'Environment',
    difficulty: 'Medium',
    questionTemplate: 'What is global warming?',
    correctAnswerFormula: "It's the gradual increase in the Earth's temperature",
    wrongAnswers: [
      'When the weather is cold',
      'A type of house',
      'A name of a country',
    ],
    methodSteps: [
      'Global warming is the gradual increase in the Earth\'s temperature.',
      'It is linked to pollution and too much carbon dioxide.',
      'We can help by saving energy and planting trees.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  // October 2023 (from paper – standard geography)
  {
    id: 'exam-oct23-map-country',
    topic: 'Maps and Places',
    category: 'Maps and Places',
    difficulty: 'Easy',
    questionTemplate: 'This is a map of which country? (A small island in the Indian Ocean, nearest neighbour India)',
    correctAnswerFormula: 'Sri Lanka',
    wrongAnswers: ['India', 'Australia', 'Japan'],
    methodSteps: [
      'Sri Lanka is an island in the Indian Ocean.',
      'India is its nearest neighbour.',
      'Maps show where countries are located.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'exam-oct23-ocean',
    topic: 'Maps and Places',
    category: 'Maps and Places',
    difficulty: 'Easy',
    questionTemplate: 'Sri Lanka is a small island in which ocean?',
    correctAnswerFormula: 'Indian Ocean',
    wrongAnswers: ['Arctic Ocean', 'Pacific Ocean', 'Atlantic Ocean'],
    methodSteps: [
      'Sri Lanka is in the Indian Ocean.',
      'It is south of India.',
      'The Indian Ocean is one of the world\'s major oceans.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },
  {
    id: 'exam-oct23-equator',
    topic: 'Maps and Places',
    category: 'Maps and Places',
    difficulty: 'Easy',
    questionTemplate: 'Sri Lanka is located near the:',
    correctAnswerFormula: 'Equator',
    wrongAnswers: ['Arctic Circle', 'Antarctic Circle', 'North Pole'],
    methodSteps: [
      'Sri Lanka is near the Equator.',
      'The Equator is an imaginary line around the middle of the Earth.',
      'Countries near the Equator have a warm, tropical climate.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'exam-oct23-name-arabians',
    topic: 'Sri Lankan History',
    category: 'History and Heritage',
    difficulty: 'Medium',
    questionTemplate: 'Which name was given by Arabians to Sri Lanka?',
    correctAnswerFormula: 'Serendib',
    wrongAnswers: ['Thambapanni', 'Ceylon', 'Lanka'],
    methodSteps: [
      'Arab traders gave Sri Lanka the name Serendib.',
      'Ceylon was the name used during British rule.',
      'Thambapanni is an ancient name for the island.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'exam-oct23-nearest-neighbour',
    topic: 'Maps and Places',
    category: 'Maps and Places',
    difficulty: 'Easy',
    questionTemplate: 'Which is the nearest neighbour of Sri Lanka?',
    correctAnswerFormula: 'India',
    wrongAnswers: ['Russia', 'Canada', 'Australia'],
    methodSteps: [
      'India is the nearest country to Sri Lanka.',
      'Sri Lanka is separated from India by a narrow strip of sea.',
      'The two countries have had close ties for a long time.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },
  {
    id: 'exam-jan24-independence-true',
    topic: 'Sri Lankan History',
    category: 'History and Heritage',
    difficulty: 'Easy',
    questionTemplate: 'Sri Lanka got independence on 4th February 1948. True or False?',
    correctAnswerFormula: 'True',
    wrongAnswers: ['False'],
    methodSteps: [
      'Sri Lanka gained independence on 4th February 1948.',
      'This day is celebrated as Independence Day every year.',
      'Don Stephen Senanayake became the first Prime Minister.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },
  {
    id: 'exam-jan24-european-nations',
    topic: 'Sri Lankan History',
    category: 'History and Heritage',
    difficulty: 'Medium',
    questionTemplate: 'Sri Lanka was conquered and ruled by how many European nations in the past?',
    correctAnswerFormula: 'Three',
    wrongAnswers: ['One', 'Two', 'Four'],
    methodSteps: [
      'Three European nations ruled Sri Lanka: Portuguese, Dutch, and British.',
      'They came at different times in history.',
      'Sri Lanka became independent from British rule in 1948.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },

  // ----- Jan 2021 -----
  {
    id: 'exam-jan21-pearl-ocean',
    topic: 'Maps and Places',
    category: 'Maps and Places',
    difficulty: 'Easy',
    questionTemplate: 'Why is Sri Lanka called the Pearl of the Indian Ocean?',
    correctAnswerFormula: 'Because of its shape and natural beauty',
    wrongAnswers: ['Because it is next to Australia', 'Because of the splendid copper coloured beach'],
    methodSteps: [
      'Sri Lanka is known for its shape and natural beauty.',
      'It is an island with rich landscapes and wildlife.',
      'The name "Pearl of the Indian Ocean" reflects this.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'exam-jan21-hemisphere-land',
    topic: 'Maps and Places',
    category: 'Maps and Places',
    difficulty: 'Easy',
    questionTemplate: 'Which hemisphere has the most land?',
    correctAnswerFormula: 'Northern Hemisphere',
    wrongAnswers: ['Southern Hemisphere', 'Water Hemisphere', 'Eastern Hemisphere'],
    methodSteps: [
      'The Northern Hemisphere has more land than the Southern.',
      'Europe, Asia, North America, and most of Africa are in the Northern Hemisphere.',
      'The Southern Hemisphere has more ocean.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'exam-jan21-line-on-map',
    topic: 'Maps and Places',
    category: 'Maps and Places',
    difficulty: 'Easy',
    questionTemplate: 'What is the line drawn on the map that divides the Earth into two hemispheres?',
    correctAnswerFormula: 'Equator',
    wrongAnswers: ['Continent', 'Compass rose', 'Horizon'],
    methodSteps: [
      'The Equator is an imaginary line around the middle of the Earth.',
      'It divides the Earth into Northern and Southern Hemispheres.',
      'Sri Lanka is located north of the Equator.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'exam-jan21-globe-inventor',
    topic: 'Maps and Places',
    category: 'Maps and Places',
    difficulty: 'Medium',
    questionTemplate: 'Who invented the first globe?',
    correctAnswerFormula: 'Crates of Mallus',
    wrongAnswers: ['Soldiers', 'Ferdinand Magellan', 'Neil Armstrong'],
    methodSteps: [
      'Crates of Mallus (an ancient Greek) is credited with making the first globe.',
      'A globe is a sphere that shows a map of the world.',
      'Globes help us see the true shape of the Earth.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'exam-jan21-oceans-count',
    topic: 'Maps and Places',
    category: 'Maps and Places',
    difficulty: 'Easy',
    questionTemplate: 'How many oceans are there in the world?',
    correctAnswerFormula: 'Five',
    wrongAnswers: ['Seven', 'Three', 'Four'],
    methodSteps: [
      'There are five oceans: Pacific, Atlantic, Indian, Southern, and Arctic.',
      'Sri Lanka is in the Indian Ocean.',
      'Oceans are large bodies of salt water.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },
  {
    id: 'exam-jan21-sea-definition',
    topic: 'Maps and Places',
    category: 'Maps and Places',
    difficulty: 'Easy',
    questionTemplate: 'A _____ is a smaller part of an ocean.',
    correctAnswerFormula: 'Sea',
    wrongAnswers: ['Pond', 'Lake', 'River'],
    methodSteps: [
      'A sea is a smaller part of an ocean, often partly surrounded by land.',
      'Examples: Arabian Sea, Bay of Bengal.',
      'Sri Lanka is surrounded by the Indian Ocean and its seas.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },

  // ----- Jan 2022 -----
  {
    id: 'exam-jan22-horizon',
    topic: 'Maps and Places',
    category: 'Maps and Places',
    difficulty: 'Easy',
    questionTemplate: 'The line where the sky seems to meet the Earth is known as:',
    correctAnswerFormula: 'The horizon',
    wrongAnswers: ['The compass rose', 'The equator', 'The summit'],
    methodSteps: [
      'The horizon is where the sky and the Earth appear to meet.',
      'It is one way we can see that the Earth is round.',
      'When we look at the sea, we see the horizon.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'exam-jan22-vijaya-name',
    topic: 'History and Heritage',
    category: 'History and Heritage',
    difficulty: 'Easy',
    questionTemplate: 'What is the name given to Sri Lanka by Prince Vijaya?',
    correctAnswerFormula: 'Thambapanni',
    wrongAnswers: ['Mahathitha', 'Uruwela', 'Serendib'],
    methodSteps: [
      'Prince Vijaya is said to have named the island Thambapanni when he arrived.',
      'Thambapanni means "copper-coloured hands" (from the sandy beach).',
      'This is considered the starting point of Sri Lankan history.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'exam-jan22-granary',
    topic: 'History and Heritage',
    category: 'History and Heritage',
    difficulty: 'Medium',
    questionTemplate: 'Since Sri Lanka was so prosperous in the past, it was also known as:',
    correctAnswerFormula: 'Granary of the East',
    wrongAnswers: ['Pearl of the Indian Ocean', 'Serendib', 'Ceylon'],
    methodSteps: [
      'Sri Lanka was rich in rice and agriculture.',
      '"Granary of the East" means a storehouse of grain for the East.',
      'Ancient kings built reservoirs to grow more crops.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'exam-jan22-oldest-map',
    topic: 'Maps and Places',
    category: 'Maps and Places',
    difficulty: 'Medium',
    questionTemplate: 'The oldest known map was made in:',
    correctAnswerFormula: 'Ancient Babylon',
    wrongAnswers: ['Ancient Greece', 'India', 'China'],
    methodSteps: [
      'The oldest known map was made in ancient Babylon.',
      'Maps have been used for thousands of years.',
      'Today we use maps and globes to find places.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'exam-jan22-earth-covered',
    topic: 'Maps and Places',
    category: 'Maps and Places',
    difficulty: 'Easy',
    questionTemplate: 'The Earth is covered with:',
    correctAnswerFormula: 'Land and water',
    wrongAnswers: ['Only land', 'Only water', 'Only ice'],
    methodSteps: [
      'The Earth has large land masses (continents) and water (oceans).',
      'There are seven continents and five oceans.',
      'Sri Lanka is an island, so it is surrounded by water.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },
  {
    id: 'exam-jan22-compass-rose',
    topic: 'Maps and Places',
    category: 'Maps and Places',
    difficulty: 'Medium',
    questionTemplate: 'The compass rose is divided into ten major points. True or False?',
    correctAnswerFormula: 'False',
    wrongAnswers: ['True'],
    methodSteps: [
      'The compass rose shows directions on a map.',
      'It has four cardinal directions: North, South, East, West.',
      'It can have eight or more points, but "ten major points" is not correct.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'exam-jan22-crust-earth',
    topic: 'Maps and Places',
    category: 'Maps and Places',
    difficulty: 'Easy',
    questionTemplate: 'The crust is the _____ layer of the Earth.',
    correctAnswerFormula: 'Outer',
    wrongAnswers: ['Inner', 'Middle', 'Centre'],
    methodSteps: [
      'The crust is the outer layer of the Earth where we live.',
      'Below the crust are the mantle and the core.',
      'Mountains, soil, and oceans are on the crust.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'exam-jan22-eight-planets',
    topic: 'Maps and Places',
    category: 'Maps and Places',
    difficulty: 'Easy',
    questionTemplate: 'There are eight planets in the solar system. True or False?',
    correctAnswerFormula: 'True',
    wrongAnswers: ['False'],
    methodSteps: [
      'There are eight planets: Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus, Neptune.',
      'Pluto is now called a dwarf planet.',
      'Earth is the planet we live on.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },
  {
    id: 'exam-jan22-comet-rocky',
    topic: 'Maps and Places',
    category: 'Maps and Places',
    difficulty: 'Medium',
    questionTemplate: 'A comet is a rocky space object. True or False?',
    correctAnswerFormula: 'False',
    wrongAnswers: ['True'],
    methodSteps: [
      'A comet is a ball of dirty ice and snow in space.',
      'When it comes near the Sun, it can form a tail.',
      'Rocks in space are called asteroids or meteoroids.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },

  // ----- May 2021 -----
  {
    id: 'exam-may21-province',
    topic: 'History and Heritage',
    category: 'History and Heritage',
    difficulty: 'Easy',
    questionTemplate: 'Which is one of the nine provinces of Sri Lanka?',
    correctAnswerFormula: 'Sabaragamuwa',
    wrongAnswers: ['Rathnapura', 'Galle', 'Colombo'],
    methodSteps: [
      'Sri Lanka has nine provinces.',
      'Sabaragamuwa is one of them (Rathnapura is a district within it).',
      'Provinces help manage the land and people.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'exam-may21-ethnic-sinhalese',
    topic: 'Culture and Festivals',
    category: 'Culture and Festivals',
    difficulty: 'Easy',
    questionTemplate: 'The largest ethnic group in Sri Lanka is:',
    correctAnswerFormula: 'Sinhalese',
    wrongAnswers: ['Burghers', 'Tamils', 'Muslims'],
    methodSteps: [
      'Sinhalese are the largest ethnic group in Sri Lanka.',
      'Tamils and Muslims are also major groups.',
      'All ethnic groups are part of Sri Lankan society.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },

  // ----- May 2023 -----
  {
    id: 'exam-may23-mountain-range',
    topic: 'Maps and Places',
    category: 'Maps and Places',
    difficulty: 'Easy',
    questionTemplate: 'A chain of mountains linked to each other is known as a:',
    correctAnswerFormula: 'Mountain range',
    wrongAnswers: ['Mountain', 'Waterfall', 'Valley'],
    methodSteps: [
      'A mountain range is a chain of mountains connected to each other.',
      'In Sri Lanka we have ranges like the Knuckles and Central Highlands.',
      'Piduruthalagala is in the central highlands.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'exam-may23-estuary',
    topic: 'Maps and Places',
    category: 'Maps and Places',
    difficulty: 'Medium',
    questionTemplate: 'An estuary that can be seen in our country is:',
    correctAnswerFormula: 'Benthota',
    wrongAnswers: ['Pidurutalagala', 'Bambarakanda', 'Trincomalee'],
    methodSteps: [
      'An estuary is where a river meets the sea.',
      'Benthota is a well-known estuary in Sri Lanka.',
      'Pidurutalagala and Bambarakanda are mountains, not estuaries.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'exam-may23-mahaweli-starts',
    topic: 'Maps and Places',
    category: 'Maps and Places',
    difficulty: 'Medium',
    questionTemplate: 'Mahaweli river starts from the:',
    correctAnswerFormula: 'Namunukula Mountain',
    wrongAnswers: ['Sri Pada Mountain', 'Knuckles Mountain', 'Pidurutalagala'],
    methodSteps: [
      'The Mahaweli is the longest river in Sri Lanka.',
      'It starts from the Namunukula Mountain area.',
      'It flows through the central and eastern parts of the island.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'exam-may23-coastline-feature',
    topic: 'Maps and Places',
    category: 'Maps and Places',
    difficulty: 'Easy',
    questionTemplate: 'A feature that cannot be seen in the coastline of our country is:',
    correctAnswerFormula: 'Mountains',
    wrongAnswers: ['Lagoons', 'Bays', 'Estuaries'],
    methodSteps: [
      'Along the coast we find lagoons, bays, and estuaries.',
      'Mountains are in the central part of Sri Lanka, not on the coastline.',
      'The coast is where the land meets the sea.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'exam-may23-highest-waterfall',
    topic: 'Maps and Places',
    category: 'Maps and Places',
    difficulty: 'Medium',
    questionTemplate: 'What is the highest waterfall in Sri Lanka?',
    correctAnswerFormula: 'Bambarakanda',
    wrongAnswers: ['Bakers Falls', 'Devon Falls', 'Dunhinda'],
    methodSteps: [
      'Bambarakanda is the highest waterfall in Sri Lanka.',
      'It is in the Badulla district.',
      'Waterfalls form where water drops from a height.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'exam-may23-longest-river',
    topic: 'Maps and Places',
    category: 'Maps and Places',
    difficulty: 'Easy',
    questionTemplate: 'What is the longest river in Sri Lanka?',
    correctAnswerFormula: 'Mahaweli river',
    wrongAnswers: ['Kelani river', 'Kalu river', 'Walawe river'],
    methodSteps: [
      'The Mahaweli is the longest river in Sri Lanka.',
      'It is used for irrigation and hydroelectric power.',
      'Many ancient kings built canals from the Mahaweli.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'exam-may23-highest-mountain',
    topic: 'Maps and Places',
    category: 'Maps and Places',
    difficulty: 'Easy',
    questionTemplate: 'What is the highest mountain in Sri Lanka?',
    correctAnswerFormula: 'Piduruthalagala',
    wrongAnswers: ['Sri Pada', 'Knuckles', 'Namunukula'],
    methodSteps: [
      'Piduruthalagala (also spelled Pidurutalagala) is the highest mountain.',
      'It is in the Nuwara Eliya district.',
      'Sri Pada (Adam\'s Peak) is famous but not the highest.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'exam-may23-trincomalee',
    topic: 'Maps and Places',
    category: 'Maps and Places',
    difficulty: 'Medium',
    questionTemplate: 'The most important natural harbour on the eastern coast of Sri Lanka is:',
    correctAnswerFormula: 'Trincomalee',
    wrongAnswers: ['Colombo', 'Galle', 'Hambantota'],
    methodSteps: [
      'Trincomalee is a natural harbour on the east coast.',
      'It has been used for centuries by traders and navies.',
      'Colombo and Galle are on the west and south coasts.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },

  // ----- Oct 2021 -----
  {
    id: 'exam-oct21-earth-shape',
    topic: 'Maps and Places',
    category: 'Maps and Places',
    difficulty: 'Easy',
    questionTemplate: 'The Earth is _____ in shape.',
    correctAnswerFormula: 'Circular (round/spherical)',
    wrongAnswers: ['Square', 'Triangular', 'Flat'],
    methodSteps: [
      'The Earth is round like a ball (spherical).',
      'We say "circular" or "round" for its shape.',
      'Ferdinand Magellan\'s voyage proved the Earth is round.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },
  {
    id: 'exam-oct21-earth-believed-flat',
    topic: 'Maps and Places',
    category: 'Maps and Places',
    difficulty: 'Easy',
    questionTemplate: 'In the past, people believed that the Earth is:',
    correctAnswerFormula: 'Flat',
    wrongAnswers: ['Elliptical', 'Circular', 'Square'],
    methodSteps: [
      'Long ago many people thought the Earth was flat.',
      'Explorers like Ferdinand Magellan proved it is round.',
      'Now we know the Earth is a sphere.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'exam-oct21-earth-day',
    topic: 'Environment',
    category: 'Environment',
    difficulty: 'Medium',
    questionTemplate: 'The Earth Day is on 22nd May. True or False?',
    correctAnswerFormula: 'False',
    wrongAnswers: ['True'],
    methodSteps: [
      'Earth Day is on 22nd April, not May.',
      'It is a day to care for our planet.',
      'We should protect the environment every day.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'exam-oct21-outer-layer-mantle',
    topic: 'Maps and Places',
    category: 'Maps and Places',
    difficulty: 'Medium',
    questionTemplate: 'The outer layer of the Earth is known as the Mantle. True or False?',
    correctAnswerFormula: 'False',
    wrongAnswers: ['True'],
    methodSteps: [
      'The outer layer is the crust, not the mantle.',
      'The mantle is the layer below the crust.',
      'We live on the crust.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },

  // ----- Oct 2022 -----
  {
    id: 'exam-oct22-nearest-neighbour',
    topic: 'Maps and Places',
    category: 'Maps and Places',
    difficulty: 'Easy',
    questionTemplate: 'Which country is our nearest neighbour?',
    correctAnswerFormula: 'India',
    wrongAnswers: ['China', 'Australia', 'Maldives'],
    methodSteps: [
      'India is the closest country to Sri Lanka.',
      'The Palk Strait separates Sri Lanka from India.',
      'The two countries have close historical and cultural ties.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },
  {
    id: 'exam-oct22-samanala-kanda',
    topic: 'Maps and Places',
    category: 'Maps and Places',
    difficulty: 'Medium',
    questionTemplate: 'A famous mountain located in the central Highlands is:',
    correctAnswerFormula: 'Samanala Kanda',
    wrongAnswers: ['Bambarakanda', 'Galkanda', 'Pidurutalagala'],
    methodSteps: [
      'Samanala Kanda (Adam\'s Peak) is in the central highlands.',
      'It is a famous pilgrimage site.',
      'Four main rivers begin from this area.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'exam-oct22-country-located-near',
    topic: 'Maps and Places',
    category: 'Maps and Places',
    difficulty: 'Easy',
    questionTemplate: 'Our country is located near:',
    correctAnswerFormula: 'The Equator',
    wrongAnswers: ['The pearl', 'The pond', 'The Arctic'],
    methodSteps: [
      'Sri Lanka is near the Equator.',
      'That is why we have a warm, tropical climate.',
      'The Equator is an imaginary line around the middle of the Earth.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },

  // ----- March 2021 -----
  {
    id: 'exam-mar21-horizon',
    topic: 'Maps and Places',
    category: 'Maps and Places',
    difficulty: 'Easy',
    questionTemplate: 'What is the horizon?',
    correctAnswerFormula: "The line at which the Earth's surface and the sky appear to meet",
    wrongAnswers: [
      'The imaginary line which runs across Mars',
      'The rings around Saturn',
      'A type of compass',
    ],
    methodSteps: [
      'The horizon is where the sky and the Earth seem to meet.',
      'We see it when we look at the sea or a flat land.',
      'It helps prove that the Earth is round.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'exam-mar21-longest-river',
    topic: 'Maps and Places',
    category: 'Maps and Places',
    difficulty: 'Easy',
    questionTemplate: 'Which is the longest river in Sri Lanka?',
    correctAnswerFormula: 'Mahaweli river',
    wrongAnswers: ['Walawe river', 'Maduru river', 'Kelani river'],
    methodSteps: [
      'The Mahaweli is the longest river in Sri Lanka.',
      'It flows from the central highlands to the east.',
      'It is used for irrigation and power.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'exam-mar21-moon-landing',
    topic: 'Maps and Places',
    category: 'Maps and Places',
    difficulty: 'Medium',
    questionTemplate: 'Which two countries tried to be the first to land on the Moon?',
    correctAnswerFormula: 'Russia and the United States of America',
    wrongAnswers: ['India and Sri Lanka', 'Africa and Australia', 'China and Japan'],
    methodSteps: [
      'The USA and Russia (Soviet Union) had a "space race".',
      'The USA was first to land humans on the Moon (1969).',
      'Neil Armstrong was the first person on the Moon.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'exam-mar21-sri-lanka-pacific',
    topic: 'Maps and Places',
    category: 'Maps and Places',
    difficulty: 'Easy',
    questionTemplate: 'Our country is situated in the Pacific Ocean. True or False?',
    correctAnswerFormula: 'False',
    wrongAnswers: ['True'],
    methodSteps: [
      'Sri Lanka is in the Indian Ocean, not the Pacific.',
      'The Pacific Ocean is on the other side of Asia.',
      'India and Sri Lanka are both in the Indian Ocean region.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },
  {
    id: 'exam-mar21-nearest-australia',
    topic: 'Maps and Places',
    category: 'Maps and Places',
    difficulty: 'Easy',
    questionTemplate: 'Our nearest neighbour is Australia. True or False?',
    correctAnswerFormula: 'False',
    wrongAnswers: ['True'],
    methodSteps: [
      'Our nearest neighbour is India, not Australia.',
      'Australia is far from Sri Lanka.',
      'The Palk Strait is between Sri Lanka and India.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },
  {
    id: 'exam-mar21-british-ceylon',
    topic: 'History and Heritage',
    category: 'History and Heritage',
    difficulty: 'Easy',
    questionTemplate: 'During British rule, Sri Lanka was called Ceylon. True or False?',
    correctAnswerFormula: 'True',
    wrongAnswers: ['False'],
    methodSteps: [
      'The British called the island Ceylon.',
      'Sri Lanka became independent in 1948.',
      'The name was changed to Sri Lanka later.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },
  {
    id: 'exam-mar21-magellan',
    topic: 'Maps and Places',
    category: 'Maps and Places',
    difficulty: 'Medium',
    questionTemplate: 'Which Portuguese explorer proved that the Earth is round?',
    correctAnswerFormula: 'Ferdinand Magellan',
    wrongAnswers: ['Neil Armstrong', 'Christopher Columbus', 'Vasco da Gama'],
    methodSteps: [
      'Ferdinand Magellan led a voyage that went around the world.',
      'This proved the Earth is round.',
      'He was Portuguese but sailed for Spain.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'exam-mar21-natural-satellite',
    topic: 'Maps and Places',
    category: 'Maps and Places',
    difficulty: 'Easy',
    questionTemplate: 'What is the natural satellite of the Earth?',
    correctAnswerFormula: 'The Moon',
    wrongAnswers: ['The Sun', 'Mars', 'A star'],
    methodSteps: [
      'The Moon is the Earth\'s natural satellite.',
      'It orbits (goes around) the Earth.',
      'It has no light of its own; it reflects the Sun\'s light.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },

  // ----- March 2022 -----
  {
    id: 'exam-mar22-sri-lanka-hemisphere',
    topic: 'Maps and Places',
    category: 'Maps and Places',
    difficulty: 'Easy',
    questionTemplate: 'Sri Lanka belongs to the Southern Hemisphere. True or False?',
    correctAnswerFormula: 'False',
    wrongAnswers: ['True'],
    methodSteps: [
      'Sri Lanka is in the Northern Hemisphere (north of the Equator).',
      'The Equator divides the Earth into North and South.',
      'Countries like India and Sri Lanka are in the Northern Hemisphere.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'exam-mar22-globe-easier-map',
    topic: 'Maps and Places',
    category: 'Maps and Places',
    difficulty: 'Medium',
    questionTemplate: 'A globe is easier to use than a map. True or False?',
    correctAnswerFormula: 'False',
    wrongAnswers: ['True'],
    methodSteps: [
      'Maps are often easier to carry and use for finding places.',
      'A globe shows the whole Earth but is bulky.',
      'Maps can show a country or region in detail.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'exam-mar22-horizon-proves-round',
    topic: 'Maps and Places',
    category: 'Maps and Places',
    difficulty: 'Easy',
    questionTemplate: 'The horizon is one example to prove that the Earth is round in shape. True or False?',
    correctAnswerFormula: 'True',
    wrongAnswers: ['False'],
    methodSteps: [
      'When ships sail away, they disappear at the horizon.',
      'This happens because the Earth is curved.',
      'So the horizon helps prove the Earth is round.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'exam-mar22-delta-river-sea',
    topic: 'Maps and Places',
    category: 'Maps and Places',
    difficulty: 'Easy',
    questionTemplate: 'A delta forms at a place where a river meets the sea. True or False?',
    correctAnswerFormula: 'True',
    wrongAnswers: ['False'],
    methodSteps: [
      'A delta is land formed where a river meets the sea.',
      'The river deposits soil and sand there.',
      'Deltas are often good for farming.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'exam-mar22-earth-day',
    topic: 'Environment',
    category: 'Environment',
    difficulty: 'Easy',
    questionTemplate: 'When is Earth Day?',
    correctAnswerFormula: '22nd April',
    wrongAnswers: ['22nd May', '4th February', '1st January'],
    methodSteps: [
      'Earth Day is on 22nd April every year.',
      'It is a day to protect our planet.',
      'People plant trees and clean the environment.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'exam-mar22-highest-mountain',
    topic: 'Maps and Places',
    category: 'Maps and Places',
    difficulty: 'Easy',
    questionTemplate: 'What is the highest mountain in Sri Lanka?',
    correctAnswerFormula: 'Piduruthalagala',
    wrongAnswers: ['Sri Pada', 'Knuckles', 'Namunukula'],
    methodSteps: [
      'Piduruthalagala is the highest mountain in Sri Lanka.',
      'It is in the Nuwara Eliya district.',
      'Sri Pada (Adam\'s Peak) is more famous but not the highest.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'exam-mar22-waterfall-name',
    topic: 'Maps and Places',
    category: 'Maps and Places',
    difficulty: 'Easy',
    questionTemplate: 'What is the name given to a place where flowing water rapidly falls from a height?',
    correctAnswerFormula: 'A waterfall',
    wrongAnswers: ['A river', 'A lagoon', 'A delta'],
    methodSteps: [
      'A waterfall is where water drops from a height.',
      'Bambarakanda and Devon are famous waterfalls in Sri Lanka.',
      'They are often in hilly or mountainous areas.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },

  // ----- March 2023 -----
  {
    id: 'exam-mar23-direction-north-east',
    topic: 'Maps and Places',
    category: 'Maps and Places',
    difficulty: 'Easy',
    questionTemplate: 'The direction located between North and East is:',
    correctAnswerFormula: 'North East',
    wrongAnswers: ['South East', 'North West', 'South West'],
    methodSteps: [
      'North East is between North and East.',
      'The four main directions are North, South, East, West.',
      'We also use in-between directions like North East.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },
  {
    id: 'exam-mar23-british-name',
    topic: 'History and Heritage',
    category: 'History and Heritage',
    difficulty: 'Easy',
    questionTemplate: 'The name given to our country by the British is:',
    correctAnswerFormula: 'Ceylon',
    wrongAnswers: ['Taprobane', 'Thambapanni', 'Serendib'],
    methodSteps: [
      'The British called Sri Lanka Ceylon.',
      'Taprobane was used by the Greeks; Thambapanni by Prince Vijaya.',
      'Serendib was the name given by Arabs.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'exam-mar23-indigenous-descendants',
    topic: 'Culture and Festivals',
    category: 'Culture and Festivals',
    difficulty: 'Medium',
    questionTemplate: 'Indigenous people are the _____ of ancient tribal Sri Lankans.',
    correctAnswerFormula: 'Descendants',
    wrongAnswers: ['Ethnic groups', 'Inhabitants', 'Neighbours'],
    methodSteps: [
      'Indigenous people (Veddhas) are descendants of ancient tribes.',
      'Descendants means people who come from those who lived long ago.',
      'They have lived in Sri Lanka for thousands of years.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'exam-mar23-public-transport-available',
    topic: 'Transport',
    category: 'Transport',
    difficulty: 'Easy',
    questionTemplate: 'Public transportation is available to the general public. True or False?',
    correctAnswerFormula: 'True',
    wrongAnswers: ['False'],
    methodSteps: [
      'Buses and trains are examples of public transport.',
      'Anyone can use them by paying a fare.',
      'They run on fixed routes.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },
  {
    id: 'exam-mar23-endemic-birds-unique',
    topic: 'Environment',
    category: 'Environment',
    difficulty: 'Easy',
    questionTemplate: 'Endemic birds are unique to a particular country. True or False?',
    correctAnswerFormula: 'True',
    wrongAnswers: ['False'],
    methodSteps: [
      'Endemic means found only in one place or country.',
      'Sri Lankan Junglefowl is an endemic bird of Sri Lanka.',
      'We should protect endemic species.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },
  {
    id: 'exam-mar23-kings-self-sufficient',
    topic: 'History and Heritage',
    category: 'History and Heritage',
    difficulty: 'Easy',
    questionTemplate: 'Great kings in the past made our country self-sufficient. True or False?',
    correctAnswerFormula: 'True',
    wrongAnswers: ['False'],
    methodSteps: [
      'Ancient kings built reservoirs and grew enough rice.',
      'Self-sufficient means able to provide for ourselves.',
      'They developed irrigation and agriculture.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },

  // ----- March 2024 -----
  {
    id: 'exam-mar24-portuguese-name',
    topic: 'History and Heritage',
    category: 'History and Heritage',
    difficulty: 'Easy',
    questionTemplate: 'The name given to Sri Lanka by the Portuguese was:',
    correctAnswerFormula: 'Ceilao',
    wrongAnswers: ['Serendib', 'Taprobane', 'Thambapanni'],
    methodSteps: [
      'The Portuguese called Sri Lanka Ceilao.',
      'Serendib was the name given by Arabs.',
      'Taprobane was used by the Greeks.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'exam-mar24-migrant-birds-why',
    topic: 'Environment',
    category: 'Environment',
    difficulty: 'Medium',
    questionTemplate: 'Why do migrant birds come to Sri Lanka?',
    correctAnswerFormula: 'To avoid harsh winter in their native countries',
    wrongAnswers: ['To avoid their families', 'To find winter regions', 'To build nests only'],
    methodSteps: [
      'Migrant birds fly from cold countries in winter.',
      'They come to warmer places like Sri Lanka for food and shelter.',
      'They go back when the weather improves in their home.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'exam-mar24-national-anthem-composer',
    topic: 'History and Heritage',
    category: 'History and Heritage',
    difficulty: 'Medium',
    questionTemplate: 'Who composed the National Anthem of Sri Lanka?',
    correctAnswerFormula: 'Ananda Samarakoon',
    wrongAnswers: ['D.S. Senanayake', 'Anagarika Dharmapala', 'C.W.W. Kannangara'],
    methodSteps: [
      'Mr. Ananda Samarakoon composed the National Anthem.',
      'It became the official National Anthem in 1951.',
      'We should stand when the National Anthem is played.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },

  // ----- July 2021 -----
  {
    id: 'exam-jul21-past-society',
    topic: 'History and Heritage',
    category: 'History and Heritage',
    difficulty: 'Easy',
    questionTemplate: 'In the past, Sri Lanka was:',
    correctAnswerFormula: 'An agricultural society',
    wrongAnswers: ['An industrial society', 'A technological society', 'A fishing society'],
    methodSteps: [
      'People mainly grew crops and raised animals.',
      'Agriculture was the main way of life.',
      'Kings built reservoirs to support farming.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'exam-jul21-arab-name',
    topic: 'History and Heritage',
    category: 'History and Heritage',
    difficulty: 'Easy',
    questionTemplate: 'What was the name given by Arab traders to Sri Lanka in the past?',
    correctAnswerFormula: 'Serendib',
    wrongAnswers: ['Ceylon', 'Thambapanni', 'Taprobane'],
    methodSteps: [
      'Arab traders called Sri Lanka Serendib.',
      'Ceylon was the name used during British rule.',
      'Thambapanni was the name from Prince Vijaya\'s time.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'exam-jul21-first-pm',
    topic: 'History and Heritage',
    category: 'History and Heritage',
    difficulty: 'Easy',
    questionTemplate: 'Who was the first Prime Minister of Sri Lanka?',
    correctAnswerFormula: 'Mr. D.S. Senanayake',
    wrongAnswers: ['Mr. Ananda Samarakoon', 'Anagarika Dharmapala', 'King Vijaya'],
    methodSteps: [
      'Don Stephen Senanayake was the first Prime Minister.',
      'He became PM when Sri Lanka gained independence in 1948.',
      'He is called the "Father of the Nation".',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'exam-jul21-continents-shaded',
    topic: 'Maps and Places',
    category: 'Maps and Places',
    difficulty: 'Medium',
    questionTemplate: 'Which two continents are Africa and North America? (They are two of the seven continents.)',
    correctAnswerFormula: 'Africa and North America',
    wrongAnswers: ['Asia and Australia', 'South America and Europe', 'Europe and Asia'],
    methodSteps: [
      'There are seven continents on Earth.',
      'Africa and North America are two of them.',
      'Sri Lanka is on the continent of Asia.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'exam-jul21-national-flower',
    topic: 'History and Heritage',
    category: 'History and Heritage',
    difficulty: 'Easy',
    questionTemplate: 'What is the National flower of Sri Lanka?',
    correctAnswerFormula: 'Naa flower',
    wrongAnswers: ['Water Lily flower', 'Rose', 'Lotus'],
    methodSteps: [
      'The Naa flower (Ironwood flower) is the national flower.',
      'The national tree is the Naa tree (Iron wood).',
      'These are symbols of Sri Lanka.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'exam-jul21-british-first',
    topic: 'History and Heritage',
    category: 'History and Heritage',
    difficulty: 'Medium',
    questionTemplate: 'First, it was the British who established their rule in Sri Lanka. True or False?',
    correctAnswerFormula: 'False',
    wrongAnswers: ['True'],
    methodSteps: [
      'The Portuguese came first, then the Dutch, then the British.',
      'So the British were not the first to rule.',
      'Sri Lanka gained independence from the British in 1948.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'exam-jul21-magellan-flat',
    topic: 'Maps and Places',
    category: 'Maps and Places',
    difficulty: 'Easy',
    questionTemplate: 'Ferdinand Magellan proved that the Earth is flat. True or False?',
    correctAnswerFormula: 'False',
    wrongAnswers: ['True'],
    methodSteps: [
      'Magellan proved that the Earth is ROUND, not flat.',
      'His voyage sailed around the world.',
      'That showed the Earth is a sphere.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },
  {
    id: 'exam-jul21-prince-vijaya-indian',
    topic: 'History and Heritage',
    category: 'History and Heritage',
    difficulty: 'Medium',
    questionTemplate: 'Prince Vijaya was an _____ Prince.',
    correctAnswerFormula: 'Indian',
    wrongAnswers: ['Indonesian', 'Sri Lankan', 'Arabian'],
    methodSteps: [
      'Prince Vijaya is said to have come from India.',
      'He landed in Sri Lanka and met Kuveni.',
      'His arrival is considered the start of Sinhalese history.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'exam-jul21-kuveni',
    topic: 'History and Heritage',
    category: 'History and Heritage',
    difficulty: 'Medium',
    questionTemplate: 'Prince Vijaya met a woman called:',
    correctAnswerFormula: 'Kuveni',
    wrongAnswers: ['Kansaki', 'Disala', 'Yakkha'],
    methodSteps: [
      'Kuveni was a queen of the Yakkha clan.',
      'She helped Prince Vijaya when he arrived.',
      'This is part of the story of Sri Lankan history.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'exam-jul21-kuveni-clan',
    topic: 'History and Heritage',
    category: 'History and Heritage',
    difficulty: 'Medium',
    questionTemplate: 'The woman Prince Vijaya met was a queen who belonged to a clan called:',
    correctAnswerFormula: 'Yakkha',
    wrongAnswers: ['Nagha', 'Sinhalese', 'Veddha'],
    methodSteps: [
      'Kuveni was the queen of the Yakkha clan.',
      'She helped Vijaya when he landed at Mahathiththa.',
      'The Yakkhas were among the early inhabitants.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'exam-jul21-districts-count',
    topic: 'History and Heritage',
    category: 'History and Heritage',
    difficulty: 'Easy',
    questionTemplate: 'How many districts are there in Sri Lanka?',
    correctAnswerFormula: '25',
    wrongAnswers: ['9', '22', '30'],
    methodSteps: [
      'Sri Lanka is divided into 25 districts.',
      'Districts are smaller than provinces.',
      'There are 9 provinces in Sri Lanka.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },

  // ----- July 2022 -----
  {
    id: 'exam-jul22-closest-country',
    topic: 'Maps and Places',
    category: 'Maps and Places',
    difficulty: 'Easy',
    questionTemplate: 'What is the closest country to Sri Lanka?',
    correctAnswerFormula: 'India',
    wrongAnswers: ['Australia', 'China', 'Maldives'],
    methodSteps: [
      'India is the nearest country to Sri Lanka.',
      'The Palk Strait separates the two countries.',
      'They have close cultural and trade links.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },
  {
    id: 'exam-jul22-land-formation-mountain',
    topic: 'Maps and Places',
    category: 'Maps and Places',
    difficulty: 'Easy',
    questionTemplate: 'A land formation which rises above the surrounding land is known as a:',
    correctAnswerFormula: 'Mountain',
    wrongAnswers: ['Coast', 'River', 'Lagoon'],
    methodSteps: [
      'A mountain is land that rises high above the surrounding area.',
      'Sri Lanka has mountains in the central part.',
      'Piduruthalagala is the highest mountain.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'exam-jul22-coast-area-sea',
    topic: 'Maps and Places',
    category: 'Maps and Places',
    difficulty: 'Easy',
    questionTemplate: 'The coast is an area next to the sea. True or False?',
    correctAnswerFormula: 'True',
    wrongAnswers: ['False'],
    methodSteps: [
      'The coast is where the land meets the sea.',
      'Sri Lanka has a long coastline with beaches.',
      'Lagoons and bays are often found along the coast.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },
  {
    id: 'exam-jul22-british-first-capture',
    topic: 'History and Heritage',
    category: 'History and Heritage',
    difficulty: 'Medium',
    questionTemplate: 'The British were the first nation to capture our country. True or False?',
    correctAnswerFormula: 'False',
    wrongAnswers: ['True'],
    methodSteps: [
      'The Portuguese came first, then the Dutch, then the British.',
      'So the British were not the first.',
      'Sri Lanka gained independence from Britain in 1948.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'exam-jul22-earth-sustain-life',
    topic: 'Maps and Places',
    category: 'Maps and Places',
    difficulty: 'Easy',
    questionTemplate: 'The Earth is a planet which does not sustain life. True or False?',
    correctAnswerFormula: 'False',
    wrongAnswers: ['True'],
    methodSteps: [
      'The Earth DOES sustain life.',
      'We have air, water, and the right temperature.',
      'That is why we can live here.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },
  {
    id: 'exam-jul22-comet-ice-snow',
    topic: 'Maps and Places',
    category: 'Maps and Places',
    difficulty: 'Medium',
    questionTemplate: 'A comet is a ball of dirty ice and snow. True or False?',
    correctAnswerFormula: 'True',
    wrongAnswers: ['False'],
    methodSteps: [
      'Comets are made of ice, dust, and rock.',
      'When they come near the Sun, they can form a tail.',
      'They orbit the Sun in long paths.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },

  // ----- July 2023 -----
  {
    id: 'exam-jul23-sigiriya-king',
    topic: 'History and Heritage',
    category: 'History and Heritage',
    difficulty: 'Easy',
    questionTemplate: 'Sigiriya rock fortress and frescoes were done by:',
    correctAnswerFormula: 'King Kashyapa',
    wrongAnswers: ['King Parakramabahu', 'King Dhathusena', 'King Dutugemunu'],
    methodSteps: [
      'King Kashyapa built Sigiriya and its famous frescoes.',
      'Sigiriya is a UNESCO World Heritage Site.',
      'Frescoes are wall paintings.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'exam-jul23-did-not-capture',
    topic: 'History and Heritage',
    category: 'History and Heritage',
    difficulty: 'Medium',
    questionTemplate: 'A country which did NOT capture our country in the past is:',
    correctAnswerFormula: 'Australia',
    wrongAnswers: ['Holland', 'Portugal', 'Britain'],
    methodSteps: [
      'Portuguese, Dutch (Holland), and British ruled Sri Lanka.',
      'Australia never invaded or ruled Sri Lanka.',
      'So Australia is the one that did not capture our country.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'exam-jul23-kelani-ancient-name',
    topic: 'History and Heritage',
    category: 'History and Heritage',
    difficulty: 'Medium',
    questionTemplate: 'The ancient name given to Kelani river is:',
    correctAnswerFormula: 'Kalyani Nadee',
    wrongAnswers: ['Mahaweli Nadee', 'Kadamba Nadee', 'Walawe Nadee'],
    methodSteps: [
      'Kelani river was known as Kalyani Nadee in ancient times.',
      'Many rivers have old names in Sinhalese.',
      'Kelani flows near Colombo.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'exam-jul23-kumana-birds',
    topic: 'Environment',
    category: 'Environment',
    difficulty: 'Medium',
    questionTemplate: 'Which is one of the famous bird destinations in our country?',
    correctAnswerFormula: 'Kumana',
    wrongAnswers: ['Sigiriya', 'Kandy', 'Colombo'],
    methodSteps: [
      'Kumana (Kumana National Park) is famous for birds.',
      'Many migrant and endemic birds can be seen there.',
      'It is in the Eastern Province.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },

  // ----- July 2024 -----
  {
    id: 'exam-jul24-located-near',
    topic: 'Maps and Places',
    category: 'Maps and Places',
    difficulty: 'Easy',
    questionTemplate: 'Sri Lanka is located near the:',
    correctAnswerFormula: 'Equator',
    wrongAnswers: ['South America', 'Pacific Ocean', 'Arctic'],
    methodSteps: [
      'Sri Lanka is near the Equator.',
      'That is why we have a tropical climate.',
      'The Equator is an imaginary line around the middle of the Earth.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },
  {
    id: 'exam-jul24-highest-waterfall',
    topic: 'Maps and Places',
    category: 'Maps and Places',
    difficulty: 'Easy',
    questionTemplate: 'What is the highest waterfall in Sri Lanka?',
    correctAnswerFormula: 'Bambarakanda',
    wrongAnswers: ['Piduruthalagala', 'Thotupola', 'Devon Falls'],
    methodSteps: [
      'Bambarakanda is the highest waterfall in Sri Lanka.',
      'Piduruthalagala is the highest mountain, not a waterfall.',
      'Bambarakanda is in the Badulla district.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'exam-jul24-mountain-range-true',
    topic: 'Maps and Places',
    category: 'Maps and Places',
    difficulty: 'Easy',
    questionTemplate: 'When a chain of mountains is linked to each other, it is called a mountain range. True or False?',
    correctAnswerFormula: 'True',
    wrongAnswers: ['False'],
    methodSteps: [
      'A mountain range is a chain of mountains linked together.',
      'The Knuckles and Central Highlands are mountain ranges in Sri Lanka.',
      'They are in the central part of the island.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'exam-jul24-thotupola-highest',
    topic: 'Maps and Places',
    category: 'Maps and Places',
    difficulty: 'Medium',
    questionTemplate: 'Thotupola is the highest mountain in Sri Lanka. True or False?',
    correctAnswerFormula: 'False',
    wrongAnswers: ['True'],
    methodSteps: [
      'Piduruthalagala is the highest mountain, not Thotupola.',
      'Thotupola is the third highest peak.',
      'Both are in the central highlands.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'exam-jul24-european-influence',
    topic: 'History and Heritage',
    category: 'History and Heritage',
    difficulty: 'Easy',
    questionTemplate: 'Sri Lanka was not influenced by European countries in the past. True or False?',
    correctAnswerFormula: 'False',
    wrongAnswers: ['True'],
    methodSteps: [
      'Sri Lanka WAS influenced by Portuguese, Dutch, and British.',
      'They brought changes in law, language, and culture.',
      'We also got some positive things like roads and education.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'exam-jul24-coast-land-ocean',
    topic: 'Maps and Places',
    category: 'Maps and Places',
    difficulty: 'Easy',
    questionTemplate: 'The coast is the place where the land meets the ocean. True or False?',
    correctAnswerFormula: 'True',
    wrongAnswers: ['False'],
    methodSteps: [
      'The coast is where the land and the ocean meet.',
      'Sri Lanka has a long coastline.',
      'Beaches, lagoons, and bays are on the coast.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },
  {
    id: 'exam-jul24-bay-inlet',
    topic: 'Maps and Places',
    category: 'Maps and Places',
    difficulty: 'Medium',
    questionTemplate: 'A bay is a broad inlet of the sea where the land curves inward. True or False?',
    correctAnswerFormula: 'True',
    wrongAnswers: ['False'],
    methodSteps: [
      'A bay is where the sea goes into the land.',
      'The land curves inward around the water.',
      'Trincomalee is a natural harbour in a bay.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'exam-jul24-flag-national-identity',
    topic: 'History and Heritage',
    category: 'History and Heritage',
    difficulty: 'Easy',
    questionTemplate: 'The National Flag is not a symbol of national identity. True or False?',
    correctAnswerFormula: 'False',
    wrongAnswers: ['True'],
    methodSteps: [
      'The National Flag IS a symbol of national identity.',
      'We hoist it on Independence Day and at national events.',
      'We should respect the flag and stand when it is raised.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },
  {
    id: 'exam-jul24-mahaweli-longest',
    topic: 'Maps and Places',
    category: 'Maps and Places',
    difficulty: 'Easy',
    questionTemplate: 'The Mahaweli River is the longest river in Sri Lanka. True or False?',
    correctAnswerFormula: 'True',
    wrongAnswers: ['False'],
    methodSteps: [
      'The Mahaweli is the longest river in Sri Lanka.',
      'It flows from the central highlands to the east.',
      'It is used for irrigation and hydroelectric power.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },
  {
    id: 'exam-jul24-mahaweli-sri-pada',
    topic: 'Maps and Places',
    category: 'Maps and Places',
    difficulty: 'Medium',
    questionTemplate: 'The Mahaweli River starts from the Sri Pada mountain. True or False?',
    correctAnswerFormula: 'False',
    wrongAnswers: ['True'],
    methodSteps: [
      'The Mahaweli starts from the Namunukula area, not Sri Pada.',
      'Kelani, Kalu, and Walawe start from the Sri Pada region.',
      'Sri Pada is Adam\'s Peak.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'exam-jul24-foot-bicycle-eco',
    topic: 'Transport',
    category: 'Transport',
    difficulty: 'Easy',
    questionTemplate: 'Foot bicycle is not an eco-friendly transport mode. True or False?',
    correctAnswerFormula: 'False',
    wrongAnswers: ['True'],
    methodSteps: [
      'Foot and bicycle ARE eco-friendly.',
      'They do not produce pollution.',
      'Walking and cycling are good for health and the environment.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },

  // ========== COMMUNITY ==========
  {
    id: 'community-place-live',
    topic: 'Community',
    category: 'Community',
    difficulty: 'Easy',
    questionTemplate: 'What do we call the place where we live with our neighbours?',
    correctAnswerFormula: 'Community',
    wrongAnswers: ['Country', 'School', 'Shop'],
    methodSteps: [
      'A community is a group of people who live in the same area.',
      'Neighbours help each other and share the same place.',
      'Your village, town, or neighbourhood is your community.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'community-helpers-teacher',
    topic: 'Community',
    category: 'Community',
    difficulty: 'Easy',
    questionTemplate: 'Who helps us learn to read and write in the community?',
    correctAnswerFormula: 'Teacher',
    wrongAnswers: ['Doctor', 'Farmer', 'Driver'],
    methodSteps: [
      'Teachers work in schools.',
      'They help children learn subjects like reading, writing, and maths.',
      'Teachers are important community helpers.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },
  {
    id: 'community-helpers-doctor',
    topic: 'Community',
    category: 'Community',
    difficulty: 'Easy',
    questionTemplate: 'Who helps us when we are sick?',
    correctAnswerFormula: 'Doctor',
    wrongAnswers: ['Teacher', 'Postman', 'Baker'],
    methodSteps: [
      'Doctors and nurses work in hospitals and clinics.',
      'They check our health and give medicine when we are sick.',
      'Doctors are important community helpers.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },
  {
    id: 'community-public-places',
    topic: 'Community',
    category: 'Community',
    difficulty: 'Medium',
    questionTemplate: 'Which place do we go to to borrow books?',
    correctAnswerFormula: 'Library',
    wrongAnswers: ['Hospital', 'Market', 'Police station'],
    methodSteps: [
      'A library is a place where we can borrow books to read.',
      'Libraries are open to everyone in the community.',
      'We must return books so others can use them too.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'community-places-worship',
    topic: 'Community',
    category: 'Community',
    difficulty: 'Medium',
    questionTemplate: 'Where do people go to pray and worship?',
    correctAnswerFormula: 'A place of worship',
    wrongAnswers: ['Hospital', 'School', 'Market'],
    methodSteps: [
      'Different communities have different places of worship.',
      'People go there to pray and celebrate festivals.',
      'We should respect all places of worship.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },

  // ========== FAMILY AND ROLES ==========
  {
    id: 'family-nuclear',
    topic: 'Family',
    category: 'Family and Roles',
    difficulty: 'Easy',
    questionTemplate: 'A family with parents and their children is called a:',
    correctAnswerFormula: 'Nuclear family',
    wrongAnswers: ['Extended family', 'Big family', 'School family'],
    methodSteps: [
      'A nuclear family has mother, father, and children.',
      'An extended family includes grandparents, uncles, aunts, and cousins.',
      'Both types of families take care of each other.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'family-roles-parents',
    topic: 'Family',
    category: 'Family and Roles',
    difficulty: 'Easy',
    questionTemplate: 'Who in the family usually goes to work to earn money?',
    correctAnswerFormula: 'Parents',
    wrongAnswers: ['Children', 'Pets', 'Neighbours'],
    methodSteps: [
      'Parents work to earn money for the family.',
      'They use the money for food, house, and school.',
      'Children can help at home by doing small chores.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'family-extended',
    topic: 'Family',
    category: 'Family and Roles',
    difficulty: 'Medium',
    questionTemplate: 'Who are your grandparents?',
    correctAnswerFormula: 'Your parents’ parents',
    wrongAnswers: ['Your uncles and aunts', 'Your cousins', 'Your neighbours'],
    methodSteps: [
      'Grandparents are the mother and father of your parents.',
      'We have two grandmothers and two grandfathers.',
      'They often tell us stories and help take care of us.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'family-responsibilities',
    topic: 'Family',
    category: 'Family and Roles',
    difficulty: 'Medium',
    questionTemplate: 'What can children do to help at home?',
    correctAnswerFormula: 'Tidy their room and help with small chores',
    wrongAnswers: ['Go to work', 'Drive the car', 'Pay the bills'],
    methodSteps: [
      'Children can tidy their room and put toys away.',
      'They can help set the table or water plants.',
      'Helping at home makes the family happy.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },

  // ========== RULES AND LAWS ==========
  {
    id: 'rules-school',
    topic: 'Rules',
    category: 'Rules and Laws',
    difficulty: 'Easy',
    questionTemplate: 'Why do we have rules at school?',
    correctAnswerFormula: 'So everyone is safe and can learn well',
    wrongAnswers: ['To make children sad', 'To waste time', 'To punish everyone'],
    methodSteps: [
      'Rules help us know what to do and what not to do.',
      'School rules keep us safe and help us learn.',
      'Following rules is fair for everyone.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'rules-road',
    topic: 'Rules',
    category: 'Rules and Laws',
    difficulty: 'Easy',
    questionTemplate: 'Before crossing the road, we should:',
    correctAnswerFormula: 'Look both ways and use a crossing',
    wrongAnswers: ['Run quickly', 'Close our eyes', 'Ignore the traffic'],
    methodSteps: [
      'We look left and right to see if cars are coming.',
      'We use a zebra crossing or pedestrian crossing when possible.',
      'Road safety rules keep us safe.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'rules-laws-difference',
    topic: 'Rules',
    category: 'Rules and Laws',
    difficulty: 'Medium',
    questionTemplate: 'What is a law?',
    correctAnswerFormula: 'A rule that everyone in the country must follow',
    wrongAnswers: ['A rule only for children', 'A game we play', 'A suggestion'],
    methodSteps: [
      'Laws are rules made by the government.',
      'Everyone must follow laws to keep order and safety.',
      'Breaking a law can have serious consequences.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'rules-home',
    topic: 'Rules',
    category: 'Rules and Laws',
    difficulty: 'Medium',
    questionTemplate: 'Why do families have rules at home?',
    correctAnswerFormula: 'To keep everyone safe and happy',
    wrongAnswers: ['To make children cry', 'To have more work', 'To forget things'],
    methodSteps: [
      'Home rules might include bedtime, screen time, or helping with chores.',
      'Rules help everyone know what is expected.',
      'Good rules make home a better place for all.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },

  // ========== MAPS AND PLACES ==========
  {
    id: 'maps-what',
    topic: 'Maps',
    category: 'Maps and Places',
    difficulty: 'Easy',
    questionTemplate: 'What is a map?',
    correctAnswerFormula: 'A drawing that shows places and how to get there',
    wrongAnswers: ['A story book', 'A song', 'A type of food'],
    methodSteps: [
      'A map shows where places are and how they connect.',
      'We use maps to find directions and distances.',
      'Maps can show a room, a town, or the whole world.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'maps-symbols',
    topic: 'Maps',
    category: 'Maps and Places',
    difficulty: 'Easy',
    questionTemplate: 'On a map, what does a blue colour usually show?',
    correctAnswerFormula: 'Water (sea, river, or lake)',
    wrongAnswers: ['Forest', 'Desert', 'Mountains'],
    methodSteps: [
      'Map makers use colours and symbols to show different things.',
      'Blue usually means water: sea, river, or lake.',
      'Green often means land with plants or forest.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'maps-direction',
    topic: 'Maps',
    category: 'Maps and Places',
    difficulty: 'Medium',
    questionTemplate: 'Which direction is opposite to North?',
    correctAnswerFormula: 'South',
    wrongAnswers: ['East', 'West', 'Up'],
    methodSteps: [
      'The four main directions are North, South, East, and West.',
      'North and South are opposite; East and West are opposite.',
      'On a map, North is often at the top.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'places-landmark',
    topic: 'Maps',
    category: 'Maps and Places',
    difficulty: 'Medium',
    questionTemplate: 'What is a landmark?',
    correctAnswerFormula: 'A famous building or place that helps us find our way',
    wrongAnswers: ['A kind of animal', 'A type of food', 'A weather type'],
    methodSteps: [
      'A landmark is a well-known place like a temple, tower, or big building.',
      'We use landmarks to give directions: "Turn left at the temple."',
      'Landmarks help us know where we are.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },

  // ========== CULTURE AND FESTIVALS ==========
  {
    id: 'culture-festival',
    topic: 'Culture',
    category: 'Culture and Festivals',
    difficulty: 'Easy',
    questionTemplate: 'Why do people celebrate festivals?',
    correctAnswerFormula: 'To remember important events and spend time with family',
    wrongAnswers: ['To be sad', 'To forget things', 'To stay alone'],
    methodSteps: [
      'Festivals are special days that have meaning for a community.',
      'People celebrate with food, music, and family.',
      'Different communities have different festivals.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'culture-food',
    topic: 'Culture',
    category: 'Culture and Festivals',
    difficulty: 'Easy',
    questionTemplate: 'Different communities often have different:',
    correctAnswerFormula: 'Food, clothes, and customs',
    wrongAnswers: ['Same exact food everywhere', 'No festivals', 'No families'],
    methodSteps: [
      'Culture includes food, clothes, music, and how we celebrate.',
      'Respecting other cultures helps us live together peacefully.',
      'We can learn from each other’s traditions.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'culture-tradition',
    topic: 'Culture',
    category: 'Culture and Festivals',
    difficulty: 'Medium',
    questionTemplate: 'What is a tradition?',
    correctAnswerFormula: 'Something people have done for a long time and pass on',
    wrongAnswers: ['A new rule', 'A one-time event', 'A type of map'],
    methodSteps: [
      'Traditions are customs that families and communities keep over time.',
      'Examples: special foods on festivals, how we greet elders.',
      'Traditions help us remember our history and culture.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'culture-respect',
    topic: 'Culture',
    category: 'Culture and Festivals',
    difficulty: 'Medium',
    questionTemplate: 'How can we show respect for other people’s festivals?',
    correctAnswerFormula: 'By being kind and not making fun of their customs',
    wrongAnswers: ['By ignoring them', 'By laughing at them', 'By staying away always'],
    methodSteps: [
      'We can wish them well on their festival.',
      'We should not make fun of their clothes, food, or customs.',
      'Respecting others makes the community a better place.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },

  // ========== CITIZENSHIP ==========
  {
    id: 'citizenship-good',
    topic: 'Citizenship',
    category: 'Citizenship',
    difficulty: 'Easy',
    questionTemplate: 'A good citizen:',
    correctAnswerFormula: 'Follows rules and helps others',
    wrongAnswers: ['Litters everywhere', 'Ignores rules', 'Hurts others'],
    methodSteps: [
      'Good citizens follow rules at school, home, and in the community.',
      'They help others and care for shared places.',
      'Being a good citizen makes everyone’s life better.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'citizenship-rights',
    topic: 'Citizenship',
    category: 'Citizenship',
    difficulty: 'Easy',
    questionTemplate: 'Children have the right to:',
    correctAnswerFormula: 'Go to school and be safe',
    wrongAnswers: ['Work all day', 'Stay alone always', 'Never play'],
    methodSteps: [
      'Children have the right to education and to be safe.',
      'They also have the right to play and rest.',
      'Adults should protect these rights.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'citizenship-responsibility',
    topic: 'Citizenship',
    category: 'Citizenship',
    difficulty: 'Medium',
    questionTemplate: 'What is our responsibility towards public property?',
    correctAnswerFormula: 'To use it carefully and not damage it',
    wrongAnswers: ['To break it', 'To hide it', 'To keep it only for ourselves'],
    methodSteps: [
      'Public property belongs to everyone: parks, buses, schools.',
      'We should not draw on walls, break things, or litter.',
      'Taking care of public property helps the whole community.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'citizenship-voting',
    topic: 'Citizenship',
    category: 'Citizenship',
    difficulty: 'Medium',
    questionTemplate: 'When people vote, they:',
    correctAnswerFormula: 'Choose who will lead or make decisions',
    wrongAnswers: ['Play a game', 'Eat together', 'Ignore the result'],
    methodSteps: [
      'Voting is a way for people to choose their leaders.',
      'In a democracy, every vote counts.',
      'When we grow up, voting is an important responsibility.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },

  // ========== ENVIRONMENT ==========
  {
    id: 'environment-recycle',
    topic: 'Environment',
    category: 'Environment',
    difficulty: 'Easy',
    questionTemplate: 'Why should we recycle paper and plastic?',
    correctAnswerFormula: 'To reduce waste and help the environment',
    wrongAnswers: ['To make more rubbish', 'To waste water', 'To harm animals'],
    methodSteps: [
      'Recycling means using things again instead of throwing them away.',
      'It reduces the amount of waste and saves resources.',
      'We can recycle paper, plastic, and metal when possible.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'environment-litter',
    topic: 'Environment',
    category: 'Environment',
    difficulty: 'Easy',
    questionTemplate: 'What should we do with our rubbish when we are outdoors?',
    correctAnswerFormula: 'Put it in a bin or take it home',
    wrongAnswers: ['Throw it on the ground', 'Hide it under a tree', 'Leave it for animals'],
    methodSteps: [
      'Littering makes places dirty and can harm animals.',
      'We should use bins or carry rubbish until we find one.',
      'Keeping our environment clean is everyone’s job.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'environment-water',
    topic: 'Environment',
    category: 'Environment',
    difficulty: 'Medium',
    questionTemplate: 'Why should we save water?',
    correctAnswerFormula: 'Because clean water is limited and needed by everyone',
    wrongAnswers: ['To waste more', 'To make the sea bigger', 'To ignore the tap'],
    methodSteps: [
      'Fresh water is limited; not all water is safe to drink.',
      'Saving water means turning off the tap when not needed.',
      'Plants, animals, and people all need water to live.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'environment-plants',
    topic: 'Environment',
    category: 'Environment',
    difficulty: 'Medium',
    questionTemplate: 'How do trees help us?',
    correctAnswerFormula: 'They give us oxygen, shade, and help keep the air clean',
    wrongAnswers: ['They make more pollution', 'They take away oxygen', 'They are useless'],
    methodSteps: [
      'Trees take in carbon dioxide and give out oxygen.',
      'They provide shade and homes for some animals.',
      'Planting and caring for trees helps the environment.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },

  // ========== GOODS AND SERVICES ==========
  {
    id: 'goods-what',
    topic: 'Goods and Services',
    category: 'Goods and Services',
    difficulty: 'Easy',
    questionTemplate: 'What are goods?',
    correctAnswerFormula: 'Things we can buy and use, like food and clothes',
    wrongAnswers: ['Ideas only', 'Free things only', 'Things we cannot touch'],
    methodSteps: [
      'Goods are things we can touch and use: toys, books, food.',
      'We buy goods from shops or markets.',
      'Services are things people do for us, like teaching or healing.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'services-what',
    topic: 'Goods and Services',
    category: 'Goods and Services',
    difficulty: 'Easy',
    questionTemplate: 'What is a service?',
    correctAnswerFormula: 'Work that someone does for others, like a doctor or teacher',
    wrongAnswers: ['A thing you can hold', 'A type of food', 'A place only'],
    methodSteps: [
      'A service is when someone does something for you.',
      'Doctors, teachers, and bus drivers provide services.',
      'We often pay for services or they are provided by the community.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'goods-needs-wants',
    topic: 'Goods and Services',
    category: 'Goods and Services',
    difficulty: 'Medium',
    questionTemplate: 'What is the difference between a need and a want?',
    correctAnswerFormula: 'A need is necessary to live (e.g. food); a want is something we would like',
    wrongAnswers: [
      'They are the same',
      'Wants are more important than needs',
      'We only have wants',
    ],
    methodSteps: [
      'Needs are things we must have: food, water, shelter, clothes.',
      'Wants are things we would like: toys, extra sweets, games.',
      'We should take care of needs first.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 30,
  },
  {
    id: 'goods-money',
    topic: 'Goods and Services',
    category: 'Goods and Services',
    difficulty: 'Medium',
    questionTemplate: 'Why do people use money?',
    correctAnswerFormula: 'To buy goods and services and to save for later',
    wrongAnswers: ['To throw away', 'To hide only', 'To eat'],
    methodSteps: [
      'Money is used to pay for things we need and want.',
      'We can save money for the future.',
      'Different countries have different types of money.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },

  // ========== MORE EASY / MEDIUM FOR BALANCE ==========
  {
    id: 'community-police',
    topic: 'Community',
    category: 'Community',
    difficulty: 'Easy',
    questionTemplate: 'Who helps keep our community safe and catches people who break the law?',
    correctAnswerFormula: 'Police',
    wrongAnswers: ['Chef', 'Singer', 'Artist'],
    methodSteps: [
      'Police officers work to keep people safe.',
      'They help when there is an emergency or crime.',
      'We can ask police for help if we are lost or in danger.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'community-fire',
    topic: 'Community',
    category: 'Community',
    difficulty: 'Easy',
    questionTemplate: 'Who do we call when there is a fire?',
    correctAnswerFormula: 'Firefighters',
    wrongAnswers: ['Teacher', 'Baker', 'Driver'],
    methodSteps: [
      'Firefighters put out fires and rescue people.',
      'We should call the fire service in an emergency.',
      'We can also learn fire safety from them.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 15,
  },
  {
    id: 'family-love',
    topic: 'Family',
    category: 'Family and Roles',
    difficulty: 'Easy',
    questionTemplate: 'Families take care of each other with:',
    correctAnswerFormula: 'Love and support',
    wrongAnswers: ['Anger only', 'No help', 'Ignoring each other'],
    methodSteps: [
      'Family members love and support each other.',
      'They help when we are sad or sick.',
      'Spending time together makes families strong.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'rules-why',
    topic: 'Rules',
    category: 'Rules and Laws',
    difficulty: 'Easy',
    questionTemplate: 'What happens when everyone follows rules?',
    correctAnswerFormula: 'Everyone is safer and things run smoothly',
    wrongAnswers: ['Nothing', 'Everything gets worse', 'Only some people are happy'],
    methodSteps: [
      'Rules help us know what to expect from others.',
      'When we all follow rules, we are fair and safe.',
      'Rules at home, school, and road keep us protected.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'maps-compass',
    topic: 'Maps',
    category: 'Maps and Places',
    difficulty: 'Easy',
    questionTemplate: 'What do we use to find North, South, East, and West?',
    correctAnswerFormula: 'A compass',
    wrongAnswers: ['A watch', 'A pencil', 'A book'],
    methodSteps: [
      'A compass has a needle that points to North.',
      'Using North, we can find South, East, and West.',
      'Maps often have a small compass or arrow showing North.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'culture-clothes',
    topic: 'Culture',
    category: 'Culture and Festivals',
    difficulty: 'Easy',
    questionTemplate: 'Different communities sometimes wear different:',
    correctAnswerFormula: 'Traditional clothes',
    wrongAnswers: ['Same uniform only', 'No clothes', 'Only one colour'],
    methodSteps: [
      'Traditional clothes are part of a community’s culture.',
      'We wear them on special days and festivals.',
      'It is good to respect how others dress.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'citizenship-share',
    topic: 'Citizenship',
    category: 'Citizenship',
    difficulty: 'Easy',
    questionTemplate: 'Sharing and taking turns is part of being a good:',
    correctAnswerFormula: 'Citizen and friend',
    wrongAnswers: ['Only at home', 'Only when forced', 'Not important'],
    methodSteps: [
      'Good citizens share public spaces and resources.',
      'Taking turns is fair for everyone.',
      'We can share toys, space, and kindness.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
  {
    id: 'environment-animals',
    topic: 'Environment',
    category: 'Environment',
    difficulty: 'Easy',
    questionTemplate: 'Why should we not harm animals and their homes?',
    correctAnswerFormula: 'They are part of nature and we should care for them',
    wrongAnswers: ['They are not important', 'We can do anything', 'Only some matter'],
    methodSteps: [
      'Animals need their homes to live and have babies.',
      'Harming animals or destroying habitats is wrong.',
      'We can care for animals by being kind and not littering.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 25,
  },
  {
    id: 'goods-shop',
    topic: 'Goods and Services',
    category: 'Goods and Services',
    difficulty: 'Easy',
    questionTemplate: 'Where do we usually buy food and daily items?',
    correctAnswerFormula: 'Shop or market',
    wrongAnswers: ['Hospital', 'School', 'Police station'],
    methodSteps: [
      'Shops and markets sell goods like food, clothes, and soap.',
      'We pay money to buy what we need.',
      'Some people grow their own food or buy from local markets.',
    ],
    questionType: 'mcq',
    estimatedTimeSeconds: 20,
  },
];

export function getSocialStudiesTemplates(): QuestionTemplate[] {
  return socialStudiesTemplates;
}
